import Link from "next/link";
import { ArrowRight, Crown } from "lucide-react";
import type { MagazineCategoryContent, MagazineIssue } from "@/types";
import { CategoryNewsletter } from "@/components/category/category-newsletter";
import { PageContainer } from "@/components/layout/page-container";
import { MagazineCover } from "@/components/magazine/magazine-cover";
import { getMagazineIssueArticles } from "@/data/mock/magazines";
import { formatMagazineIssueDate } from "@/lib/magazine-issue-date";
import { getMagazineCategories, getMagazineCategoryHref, getMagazineReaderHref } from "@/lib/magazine-categories";
import { MagazineCategoryFeaturedIssue } from "./magazine-category-featured-issue";
import { MagazineCategoryHeader } from "./magazine-category-header";
import { MagazineCategoryIssueGrid } from "./magazine-category-issue-grid";
import { MagazineCategoryStoryCard } from "./magazine-category-story-card";

function ReaderEditions({ issues }: { issues: readonly MagazineIssue[] }) {
  if (issues.length === 0) return null;
  return <div className="bg-[#d8d0c2]"><PageContainer className="section-space" width="standard"><section aria-labelledby="magazine-category-reader-heading" className="grid gap-10 lg:grid-cols-[.62fr_1.38fr] lg:gap-20"><div><p className="eyebrow text-accent">Read Digitally</p><h2 className="type-display-lg mt-5" id="magazine-category-reader-heading">Complete editions, page by page.</h2><p className="type-deck mt-6 max-w-xl text-[#4d4a43]">Digital Reader availability is drawn directly from each issue record. Only complete, configured editions appear here.</p></div><ul className="grid gap-10 sm:grid-cols-2">{issues.map((issue) => {
    const readerHref = getMagazineReaderHref(issue);
    if (!readerHref) return null;
    return <li key={issue.id}><article className="grid grid-cols-[8rem_minmax(0,1fr)] gap-6 border-t-2 border-foreground pt-5 sm:grid-cols-1"><MagazineCover href={readerHref} issue={issue} variant="compact" /><div><p className="type-meta text-accent">{formatMagazineIssueDate(issue.publicationDate)} · Digital Reader</p><h3 className="mt-3 font-serif text-3xl leading-none">{issue.coverHeadline}</h3><p className="mt-4 text-sm leading-6 text-[#4d4a43]">{issue.description}</p><Link className="mt-5 inline-flex min-h-11 items-center gap-2 border-b border-foreground text-sm font-bold" href={readerHref}>Read Digital Edition <ArrowRight aria-hidden="true" className="size-4" /></Link></div></article></li>;
  })}</ul></section></PageContainer></div>;
}

function PremiumEditions({ issues }: { issues: readonly MagazineIssue[] }) {
  if (issues.length === 0) return null;
  return <div className="bg-[#171612] text-white"><PageContainer className="section-space" width="standard"><section aria-labelledby="magazine-category-premium-heading"><header className="grid gap-7 border-t border-white/35 pt-5 lg:grid-cols-[.68fr_1.32fr]"><div><p className="eyebrow text-premium">Premium Editions</p><h2 className="type-display-lg mt-5" id="magazine-category-premium-heading">Focused collections with greater depth.</h2></div><p className="type-deck max-w-3xl text-white/60">Longer interviews, original analysis and special editorial packages. Premium is an edition status here; access controls are not active.</p></header><ul className="mt-12 grid gap-10 md:grid-cols-2">{issues.map((issue) => <li key={issue.id}><article className="grid gap-7 border-t border-white/25 pt-6 sm:grid-cols-[10rem_minmax(0,1fr)]"><MagazineCover issue={issue} variant="compact" /><div><p className="type-meta inline-flex items-center gap-2 text-premium"><Crown aria-hidden="true" className="size-4" /> Premium Edition · {formatMagazineIssueDate(issue.publicationDate)}</p><h3 className="mt-4 font-serif text-3xl leading-none">{issue.coverHeadline}</h3><p className="mt-4 text-sm leading-6 text-white/60">{issue.description}</p><ul className="mt-5 border-t border-white/20">{getMagazineIssueArticles(issue).slice(0, 2).map((story) => <li className="border-b border-white/20" key={story.id}><Link className="block py-3 font-serif text-lg leading-tight hover:text-premium" href={`/article/${story.slug}`}>{story.title}</Link></li>)}</ul><Link className="mt-5 inline-flex min-h-11 items-center gap-2 border-b border-premium text-sm font-bold text-premium" href="/magazine#premium">Explore Premium <ArrowRight aria-hidden="true" className="size-4" /></Link></div></article></li>)}</ul></section></PageContainer></div>;
}

function HistoricalIssues({ categoryName, issues, archiveHref }: { categoryName: string; issues: readonly MagazineIssue[]; archiveHref: string }) {
  if (issues.length === 0) return null;
  return <PageContainer className="section-space" width="standard"><section aria-labelledby="magazine-category-history-heading" className="grid gap-12 lg:grid-cols-[.55fr_1.45fr] lg:gap-20"><div><p className="eyebrow text-accent">From the Archive</p><h2 className="type-display-lg mt-5" id="magazine-category-history-heading">Earlier editions, enduring questions.</h2><p className="type-body-lg mt-6 max-w-lg text-muted">Older {categoryName} issues give the category historical depth beyond the current publishing year.</p><Link className="mt-7 inline-flex min-h-11 items-center gap-2 border-b border-foreground text-sm font-bold hover:text-accent" href={archiveHref}>Browse Full Magazine Archive <ArrowRight aria-hidden="true" className="size-4" /></Link></div><ol className="grid gap-9 sm:grid-cols-2 xl:grid-cols-3">{issues.map((issue) => <li key={issue.id}><article className="border-t border-foreground pt-5"><MagazineCover href={getMagazineReaderHref(issue) ?? undefined} issue={issue} variant="compact" /><p className="type-meta mt-5 text-accent">{formatMagazineIssueDate(issue.publicationDate)}</p><h3 className="mt-3 font-serif text-3xl leading-none">{issue.coverHeadline}</h3><p className="mt-4 text-sm leading-6 text-muted">{issue.description}</p></article></li>)}</ol></section></PageContainer>;
}

function RelatedCategories({ content }: { content: MagazineCategoryContent }) {
  return <div className="bg-surface-subtle"><PageContainer className="section-space" width="standard"><section aria-labelledby="magazine-category-related-heading"><header className="grid gap-6 border-t-2 border-foreground pt-4 lg:grid-cols-[.65fr_1.35fr]"><div><p className="eyebrow text-accent">Explore More</p><h2 className="type-h2 mt-4" id="magazine-category-related-heading">Related Magazine categories</h2></div><p className="type-deck max-w-2xl text-muted">Move across the permanent themes that organize issues, special editions and stories throughout the publication.</p></header><nav aria-label="Related Magazine categories" className="mt-10"><ul className="grid md:grid-cols-2">{content.relatedCategories.map((category) => <li className="border-t border-border md:odd:pr-8 md:even:border-l md:even:pl-8 md:[&:nth-last-child(-n+2)]:border-b" key={category.id}><Link className="group flex min-h-32 items-center justify-between gap-6 py-6" href={getMagazineCategoryHref(category)}><span><span className="font-serif text-3xl leading-none group-hover:text-accent">{category.name}</span><span className="mt-3 block max-w-md text-sm leading-6 text-muted">{category.shortDescription}</span></span><ArrowRight aria-hidden="true" className="size-5 shrink-0 transition-transform group-hover:translate-x-1" /></Link></li>)}</ul></nav></section></PageContainer></div>;
}

function DiscoveryAndConversion({ content, archiveHref }: { content: MagazineCategoryContent; archiveHref: string }) {
  const { currentCoverage } = content.category;
  return <PageContainer className="section-space" width="standard"><div className="grid gap-8 lg:grid-cols-2"><section aria-labelledby="magazine-current-coverage-heading" className="flex min-h-[23rem] flex-col justify-between border-t-2 border-foreground bg-surface p-7 sm:p-10"><div><p className="eyebrow text-accent">{currentCoverage.eyebrow}</p><h2 className="type-h2 mt-5" id="magazine-current-coverage-heading">{currentCoverage.title}</h2><p className="type-body-lg mt-6 max-w-xl text-muted">{currentCoverage.description}</p></div><div className="mt-8"><Link className="inline-flex min-h-12 items-center gap-2 bg-foreground px-5 text-sm font-bold text-white hover:bg-accent" href={currentCoverage.href}>{currentCoverage.actionLabel} <ArrowRight aria-hidden="true" className="size-4" /></Link></div></section><section aria-labelledby="magazine-category-archive-cta" className="flex min-h-[23rem] flex-col justify-between bg-[#d8d0c2] p-7 sm:p-10"><div><p className="eyebrow text-accent">The Archive</p><h2 className="type-h2 mt-5" id="magazine-category-archive-cta">Every issue. Every theme.</h2><p className="type-body-lg mt-6 max-w-xl text-[#4d4a43]">Explore every issue, theme and cover story from The Perspective Magazine.</p></div><div className="mt-8 flex flex-wrap gap-3"><Link className="inline-flex min-h-12 items-center gap-2 bg-foreground px-5 text-sm font-bold text-white hover:bg-accent" href={archiveHref}>Browse Full Archive <ArrowRight aria-hidden="true" className="size-4" /></Link><Link className="inline-flex min-h-12 items-center border border-foreground px-5 text-sm font-bold hover:bg-foreground hover:text-white" href="/magazine">Latest Issue</Link></div></section></div><section aria-labelledby="magazine-category-subscribe-heading" className="mt-8 grid gap-10 bg-accent p-7 text-white sm:p-10 lg:grid-cols-[1.15fr_.85fr] lg:items-end"><div><p className="eyebrow text-white/70">Subscribe to The Perspective</p><h2 className="type-h2 mt-5" id="magazine-category-subscribe-heading">Stay close to the ideas shaping what comes next.</h2><p className="type-body-lg mt-6 max-w-2xl text-white/75">Read every issue and follow the ideas shaping business, leadership and technology.</p></div><div className="flex flex-wrap gap-3 lg:justify-end"><Link className="inline-flex min-h-12 items-center gap-2 bg-white px-5 text-sm font-bold text-foreground hover:bg-[#f3e6d0]" href="/magazine#subscribe">Subscription Options <ArrowRight aria-hidden="true" className="size-4" /></Link><Link className="inline-flex min-h-12 items-center border border-white px-5 text-sm font-bold hover:bg-white hover:text-foreground" href="/magazine#premium">Explore Premium</Link></div></section></PageContainer>;
}

export function MagazineCategoryPage({ content }: { content: MagazineCategoryContent }) {
  const archiveHref = `/magazine/archive?q=${encodeURIComponent(content.category.archiveQuery)}`;
  return <>
    <MagazineCategoryHeader categories={getMagazineCategories()} category={content.category} issueCount={content.matchingIssues.length} storyCount={content.storyCount} />
    <main>
      <MagazineCategoryFeaturedIssue category={content.category} issue={content.featuredIssue} stories={content.featuredIssueStories} />
      <div className="bg-surface" id="featured-stories"><PageContainer className="section-space" width="standard"><section aria-labelledby="magazine-category-featured-stories"><header className="grid gap-6 border-t-2 border-foreground pt-4 lg:grid-cols-[.62fr_1.38fr]"><div><p className="eyebrow text-accent">Featured Stories</p><h2 className="type-h2 mt-4" id="magazine-category-featured-stories">Cover stories and defining ideas</h2></div><p className="type-deck max-w-2xl text-muted">Canonical stories selected for their issue context and their lasting place in this Magazine category.</p></header><div className="mt-12 grid gap-x-9 gap-y-14 lg:grid-cols-2">{content.featuredStories.map((story, index) => <MagazineCategoryStoryCard lead={index === 0} key={story.article.id} story={story} />)}</div></section></PageContainer></div>
      <div className="bg-surface-subtle"><PageContainer className="section-space" width="standard"><MagazineCategoryIssueGrid categoryName={content.category.name} issues={content.matchingIssues} /></PageContainer></div>
      <PageContainer className="section-space" width="standard"><section aria-labelledby="magazine-category-archive-stories"><header className="grid gap-6 border-t-2 border-foreground pt-4 lg:grid-cols-[.62fr_1.38fr]"><div><p className="eyebrow text-accent">Stories from the Archive</p><h2 className="type-h2 mt-4" id="magazine-category-archive-stories">A Magazine index</h2></div><p className="type-deck max-w-2xl text-muted">A text-led index organized by issue context, newest first and deduplicated from the main featured selection.</p></header><ol className="mt-10">{content.archiveStories.map(({ article, issue, sectionLabel }, index) => <li className="grid gap-4 border-t border-border py-5 sm:grid-cols-[3rem_9rem_minmax(0,1fr)_auto] sm:items-start sm:gap-6" key={article.id}><span className="font-serif text-xl text-accent">{String(index + 1).padStart(2, "0")}</span><p className="type-meta text-muted">{formatMagazineIssueDate(issue.publicationDate)}<span className="mt-2 block text-[#76531b]">{sectionLabel}</span></p><div><Link className="font-serif text-2xl leading-tight hover:text-accent sm:text-3xl" href={`/article/${article.slug}`}>{article.title}</Link>{article.authors[0] ? <p className="type-meta mt-3 text-muted">By <Link className="hover:text-accent" href={`/author/${article.authors[0].slug}`}>{article.authors[0].name}</Link></p> : null}</div><p className="type-meta text-muted sm:text-right">{article.readingMinutes} min read</p></li>)}</ol></section></PageContainer>
      <ReaderEditions issues={content.readerIssues} />
      <PremiumEditions issues={content.premiumIssues} />
      <HistoricalIssues archiveHref={archiveHref} categoryName={content.category.name} issues={content.historicalIssues} />
      <RelatedCategories content={content} />
      <DiscoveryAndConversion archiveHref={archiveHref} content={content} />
      <div className="bg-surface"><PageContainer className="section-space" width="standard"><CategoryNewsletter description="New issues, cover stories and special editions from The Perspective." eyebrow="For readers who keep the long view" title="The Magazine Briefing" /></PageContainer></div>
    </main>
  </>;
}
