import Link from "next/link";
import { ArrowRight, BookOpen, Check } from "lucide-react";
import type { MagazineSubscriptionContent } from "@/types";
import { CategoryNewsletter } from "@/components/category/category-newsletter";
import { PageContainer } from "@/components/layout/page-container";
import { MagazineCover } from "@/components/magazine/magazine-cover";
import { SubscriptionComparison } from "./subscription-comparison";
import { SubscriptionPageHeader } from "./subscription-page-header";
import { SubscriptionPlanSelector } from "./subscription-plan-selector";

const valuePoints = ["Thoughtful editorial selection", "Complete digital issues", "Premium special editions", "A growing archive", "Long-form interviews and analysis"];
const supportedWork = ["Original interviews", "Long-form features", "Magazine design and production", "Digital Reader development", "Archive preservation", "Contributor essays and analysis"];
const reassurancePoints = ["Focused issue reading", "Accessible Text View", "Cross-device experience", "Curated editorial archive"];

export function MagazineSubscriptionPage({ content }: { content: MagazineSubscriptionContent }) {
  const readerHref = `/magazine/read/${content.readerIssue.slug}`;
  const entitlementMap = new Map(content.entitlements.map((entitlement) => [entitlement.key, entitlement]));
  const years = Object.entries(content.archiveYearCounts).sort(([left], [right]) => Number(right) - Number(left));

  return <>
    <SubscriptionPageHeader readerHref={readerHref} />

    <PageContainer className="section-space-lg" width="standard"><section aria-labelledby="subscription-value-heading" className="grid gap-12 lg:grid-cols-[minmax(0,1.25fr)_minmax(18rem,.75fr)] lg:gap-20"><div><p className="eyebrow text-accent">The Perspective, without the noise</p><h2 className="mt-5 max-w-5xl font-serif text-[clamp(3.2rem,7vw,6.5rem)] leading-[.88] tracking-[-.055em]" id="subscription-value-heading">Context over volume. Reading over distraction.</h2><p className="type-deck mt-7 max-w-3xl text-muted">Reporting, interviews, magazines and ideas designed for readers who value context over volume.</p></div><ul className="border-t-2 border-foreground">{valuePoints.map((point, index) => <li className="grid min-h-16 grid-cols-[2.5rem_minmax(0,1fr)] items-center gap-3 border-b border-border py-3" key={point}><span className="font-serif text-xl text-accent">{String(index + 1).padStart(2, "0")}</span><span className="font-serif text-xl">{point}</span></li>)}</ul></section></PageContainer>

    <div className="bg-surface-subtle"><PageContainer className="section-space" width="standard"><SubscriptionPlanSelector plans={content.plans} /></PageContainer></div>

    <PageContainer className="section-space" width="standard"><SubscriptionComparison comparisonKeys={content.comparisonKeys} entitlements={content.entitlements} plans={content.plans} /></PageContainer>

    <div className="bg-[#171612] text-white"><PageContainer className="section-space" width="standard"><section aria-labelledby="subscription-support-heading" className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:gap-20"><div><p className="eyebrow text-[#e7c785]">What you’re subscribing to</p><h2 className="type-display-lg mt-5" id="subscription-support-heading">The work behind a complete issue.</h2><p className="type-body-lg mt-6 max-w-xl text-white/60">A subscription is designed to sustain the reporting, editing, design and preservation that give ideas the space to become useful.</p></div><ul className="grid sm:grid-cols-2">{supportedWork.map((item) => <li className="flex min-h-16 items-center gap-3 border-t border-white/20 py-4 text-white/75" key={item}><Check aria-hidden="true" className="size-4 text-[#e7c785]" />{item}</li>)}</ul></section></PageContainer></div>

    <PageContainer className="section-space-lg" width="standard"><section aria-labelledby="digital-experience-heading" className="grid gap-14 lg:grid-cols-[minmax(16rem,.7fr)_minmax(0,1.3fr)] lg:items-center lg:gap-20"><div className="mx-auto w-[76%] max-w-sm lg:w-full"><MagazineCover href={readerHref} issue={content.readerIssue} variant="large" /></div><div><p className="eyebrow text-accent">The complete digital issue</p><h2 className="type-display-lg mt-5" id="digital-experience-heading">A Magazine designed for focused reading.</h2><p className="type-deck mt-7 max-w-3xl text-muted">Digital subscribers will receive access to complete Magazine editions designed for focused reading across desktop, tablet and mobile.</p><div aria-label="Preview of the Digital Reader interface" className="mt-9 border border-border bg-[#d8d0c2] p-4 shadow-[0_18px_50px_rgb(0_0_0/10%)]" role="img"><div className="grid min-h-64 grid-cols-[5rem_minmax(0,1fr)] gap-4 bg-[#24231f] p-4 text-white sm:grid-cols-[8rem_minmax(0,1fr)]"><div className="border-r border-white/20 pr-3"><p className="type-meta text-[#e7c785]">Contents</p><ol className="mt-5 space-y-4 text-xs text-white/65"><li>Cover</li><li>Leaders</li><li>Business</li><li>Ideas</li></ol></div><div className="bg-surface p-5 text-foreground sm:p-8"><p className="type-meta text-accent">August 2026</p><p className="mt-5 max-w-xl font-serif text-3xl leading-[.95] sm:text-5xl">The Architects of Tomorrow</p><div className="mt-8 space-y-3"><span className="block h-px w-full bg-border" /><span className="block h-px w-4/5 bg-border" /><span className="block h-px w-11/12 bg-border" /></div></div></div></div><ul className="mt-8 grid gap-x-7 sm:grid-cols-2">{["Interactive Reader", "Page navigation and Contents", "Accessible Text View", "Responsive mobile reading"].map((item) => <li className="flex min-h-12 items-center gap-3 border-t border-border text-sm" key={item}><Check aria-hidden="true" className="size-4 text-accent" />{item}</li>)}</ul><Link className="mt-8 inline-flex min-h-12 items-center gap-2 bg-foreground px-5 text-sm font-bold text-white hover:bg-accent" href={readerHref}><BookOpen aria-hidden="true" className="size-4" /> Preview Digital Reader <ArrowRight aria-hidden="true" className="size-4" /></Link></div></section></PageContainer>

    <div className="bg-[#e3ddd1]"><PageContainer className="section-space" width="standard"><section aria-labelledby="subscription-premium-heading" className="grid gap-12 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:gap-20"><div><p className="eyebrow text-[#76531b]">Go deeper with Premium</p><h2 className="type-display-lg mt-5" id="subscription-premium-heading">The deepest editions in the publication.</h2><p className="type-deck mt-7 max-w-3xl text-[#575146]">Premium adds the publication’s deeper editorial editions—special interviews, analysis and complete editorial packages—to the standard Digital experience.</p><Link className="mt-8 inline-flex min-h-12 items-center gap-2 bg-foreground px-5 text-sm font-bold text-white hover:bg-accent" href="/magazine/premium">Explore Premium Editions <ArrowRight aria-hidden="true" className="size-4" /></Link></div><div className="grid grid-cols-2 items-end gap-5">{content.premiumIssues.map((issue, index) => <MagazineCover className={index === 0 ? "mb-8" : ""} issue={issue} key={issue.id} variant="compact" />)}</div></section></PageContainer></div>

    <PageContainer className="section-space" width="standard"><section aria-labelledby="subscription-archive-heading" className="grid gap-12 lg:grid-cols-[.62fr_1.38fr] lg:gap-20"><div><p className="eyebrow text-accent">Archive access</p><h2 className="type-display-lg mt-5" id="subscription-archive-heading">A growing Magazine archive.</h2><p className="type-body-lg mt-6 text-muted">Digital and Premium plans are designed to unlock deeper archive access once membership infrastructure is connected. Existing routes remain publicly available today.</p><Link className="mt-7 inline-flex min-h-12 items-center gap-2 border border-foreground px-5 text-sm font-bold hover:bg-foreground hover:text-white" href="/magazine/archive">Browse current archive <ArrowRight aria-hidden="true" className="size-4" /></Link></div><div><div className="grid grid-cols-3 border-y border-border"><div className="py-7"><p className="font-serif text-4xl">{content.archiveIssueCount}</p><p className="type-meta mt-2 text-muted">Issues</p></div><div className="border-l border-border px-5 py-7"><p className="font-serif text-4xl">{content.readerIssueCount}</p><p className="type-meta mt-2 text-muted">Reader-ready</p></div><div className="border-l border-border pl-5 py-7"><p className="font-serif text-4xl">{content.premiumIssueCount}</p><p className="type-meta mt-2 text-muted">Premium</p></div></div><ol className="mt-8">{years.map(([year, count]) => <li className="grid grid-cols-[6rem_minmax(0,1fr)_auto] items-center gap-5 border-t border-border py-5 last:border-b" key={year}><span className="font-serif text-3xl">{year}</span><span className="text-sm text-muted">Standard, Premium and Reader issue states</span><span className="type-meta text-muted">{count} issues</span></li>)}</ol></div></section></PageContainer>

    <div className="bg-surface-subtle"><PageContainer className="section-space" width="standard"><section aria-labelledby="reading-style-heading"><header className="max-w-3xl"><p className="eyebrow text-accent">Find your reading style</p><h2 className="type-display-lg mt-5" id="reading-style-heading">Choose depth, not a demographic.</h2><p className="type-deck mt-6 text-muted">Each level reflects how much of the Magazine experience you want—not who we think you are.</p></header><ol className="mt-12 grid gap-7 lg:grid-cols-3">{content.audiences.map((audience, index) => <li className="border-t-2 border-foreground bg-surface p-7 sm:p-9" key={audience.tier}><p className="font-serif text-3xl text-accent">{String(index + 1).padStart(2, "0")}</p><h3 className="mt-6 font-serif text-4xl">{audience.name}</h3><p className="mt-5 text-sm leading-6 text-muted">{audience.description}</p></li>)}</ol></section></PageContainer></div>

    <PageContainer className="section-space" width="standard"><section aria-labelledby="entitlement-preview-heading"><header className="grid gap-6 border-t-2 border-foreground pt-5 lg:grid-cols-[.62fr_1.38fr]"><div><p className="eyebrow text-accent">What each level unlocks</p><h2 className="type-display-lg mt-5" id="entitlement-preview-heading">A clear access model.</h2></div><p className="type-deck max-w-3xl text-muted">This matrix defines the future product relationship. It does not currently lock routes, identify users or enforce membership.</p></header><div className="mt-12 grid lg:grid-cols-3">{content.plans.map((plan, planIndex) => <article className={plan.slug === "premium" ? "bg-[#171612] p-7 text-white sm:p-9" : "border-y border-border p-7 sm:p-9 lg:border-r"} key={plan.id}><p className={plan.slug === "premium" ? "type-meta text-[#e7c785]" : "type-meta text-accent"}>{plan.accessTier}</p><h3 className="mt-4 font-serif text-4xl">{plan.name}</h3><ul className="mt-7">{plan.entitlementKeys.filter((key) => planIndex === 0 || !content.plans[planIndex - 1]?.entitlementKeys.includes(key)).map((key) => <li className={plan.slug === "premium" ? "border-t border-white/20 py-3 text-sm text-white/70" : "border-t border-border py-3 text-sm text-muted"} key={key}>{entitlementMap.get(key)?.label}</li>)}</ul></article>)}</div></section></PageContainer>

    <div className="bg-[#efe9de]"><PageContainer className="section-space" width="standard"><section aria-labelledby="subscription-faq-heading" className="grid gap-12 lg:grid-cols-[.55fr_1.45fr] lg:gap-20"><div><p className="eyebrow text-accent">Frequently asked questions</p><h2 className="type-display-lg mt-5" id="subscription-faq-heading">Before membership begins.</h2><p className="type-body-lg mt-6 text-muted">Clear answers about the intended plans and what remains for the future account and billing phase.</p></div><div>{content.faqs.map((faq) => <details className="group border-t border-[#aaa292] last:border-b" key={faq.id}><summary className="flex min-h-16 cursor-pointer list-none items-center justify-between gap-5 py-4 font-serif text-xl focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus sm:text-2xl"><span>{faq.question}</span><span aria-hidden="true" className="text-accent group-open:rotate-45">+</span></summary><p className="max-w-3xl pb-6 pr-10 text-sm leading-7 text-muted">{faq.answer}</p></details>)}</div></section></PageContainer></div>

    <PageContainer className="section-space" width="standard"><section aria-labelledby="subscription-reassurance-heading" className="grid gap-10 border-t-2 border-foreground pt-5 lg:grid-cols-[.72fr_1.28fr]"><div><p className="eyebrow text-accent">Built around reading, not distraction</p><h2 className="type-display-lg mt-5" id="subscription-reassurance-heading">A quieter way through the issue.</h2></div><ul className="grid sm:grid-cols-2">{reassurancePoints.map((point) => <li className="flex min-h-16 items-center gap-3 border-t border-border py-4 text-sm" key={point}><Check aria-hidden="true" className="size-4 text-accent" />{point}</li>)}</ul></section></PageContainer>

    <div className="bg-accent text-white" id="subscription-status"><PageContainer className="section-space-lg" width="standard"><section aria-labelledby="subscription-final-heading" className="grid gap-10 lg:grid-cols-[1.15fr_.85fr] lg:items-end"><div><p className="eyebrow text-white/70">Subscription status</p><h2 className="type-display-lg mt-5" id="subscription-final-heading">Read more. Understand more.</h2><p className="type-deck mt-7 max-w-3xl text-white/75">Choose the level of The Perspective that fits how you want to read today—and be ready when full membership access launches.</p><p className="mt-7 max-w-2xl text-sm leading-6 text-white/70">Subscription checkout and account access will be enabled in the membership phase. No payment or user-state change occurs on this page.</p></div><div className="flex flex-wrap gap-3 lg:justify-end"><Link className="inline-flex min-h-12 items-center gap-2 bg-white px-5 text-sm font-bold text-foreground hover:bg-[#f3e6d0]" href="#plan-digital">View Digital <ArrowRight aria-hidden="true" className="size-4" /></Link><Link className="inline-flex min-h-12 items-center gap-2 border border-white px-5 text-sm font-bold hover:bg-white hover:text-foreground" href="/magazine/premium">View Premium</Link></div></section></PageContainer></div>

    <div className="bg-surface"><PageContainer className="section-space" width="standard"><CategoryNewsletter description="New issues, Premium editions, interviews and special features from The Perspective." eyebrow="For readers who keep the long view" title="The Magazine Briefing" /></PageContainer></div>
  </>;
}
