import Image from "next/image";
import Link from "next/link";
import { Bookmark, CalendarDays, ChevronRight, Headphones, Lightbulb, Mail, MapPin, Share2 } from "lucide-react";
import type { Article, ArticleContentBlock, ArticleDetail } from "@/types";
import { getArticlesByAuthor } from "@/data/mock/articles";
import { articleHeadingId, getArticleTableOfContents } from "@/lib/article-content";
import { formatEditorialDate } from "@/lib/editorial-date";
import styles from "./article-redesign.module.css";

function Breaking(){return <section className={styles.breaking}><div className={styles.shell}><strong>Breaking</strong><div><Link href="/article/markets-optimism">Markets reassess the path for interest rates</Link><Link href="/article/industrial-investment-strategy">Industrial investment returns to the center of strategy</Link><Link href="/article/global-computing-capacity">Computing capacity becomes a global priority</Link></div><span><i/>Live</span></div></section>}
function Avatar({article,size="45px"}:{article:ArticleDetail;size?:string}){const author=article.authors[0];return author?.avatar?<Image alt={`Portrait of ${author.name}`} fill sizes={size} src={author.avatar.src}/>:null}
function ArticleBody({content}:{content:readonly ArticleContentBlock[]}){return <div className={styles.articleBody}>{content.map((block,index)=>{const key=`${block.type}-${index}`;if(block.type==="paragraph")return <p className={index===0?styles.leadParagraph:undefined} key={key}>{block.text}</p>;if(block.type==="heading")return block.level===2?<h2 id={articleHeadingId(block.text)} key={key}>{block.text}</h2>:<h3 id={articleHeadingId(block.text)} key={key}>{block.text}</h3>;if(block.type==="pullQuote")return <figure className={styles.pullQuote} key={key}><blockquote>“{block.quote}”</blockquote>{block.attribution?<figcaption>— {block.attribution}</figcaption>:null}</figure>;if(block.type==="callout")return <aside className={styles.callout} key={key}><Lightbulb/><div><b>{block.label}</b><p>{block.text}</p></div></aside>;if(block.type==="image")return <figure className={styles.inlineImage} key={key}><div><Image alt={block.image.alt} fill sizes="760px" src={block.image.src}/></div><figcaption><span>{block.caption}</span><span>{block.credit}</span></figcaption></figure>;if(block.type==="bulletList"||block.type==="numberedList"){const Tag=block.type==="bulletList"?"ul":"ol";return <Tag key={key}>{block.items.map(item=><li key={item}>{item}</li>)}</Tag>}return <hr key={key}/>})}</div>}
function ShareRail({article}:{article:ArticleDetail}){const toc=getArticleTableOfContents(article.content);return <aside className={styles.shareRail}><section><h2>In This Story</h2>{toc.slice(0,7).map(item=><a href={`#${item.id}`} key={item.id}>{item.text}</a>)}</section><section><h2>Share This Story</h2><div><a aria-label="Share on Facebook" href="https://facebook.com" target="_blank" rel="noreferrer">f</a><a aria-label="Share on X" href="https://x.com" target="_blank" rel="noreferrer">X</a><a aria-label="Share on LinkedIn" href="https://linkedin.com" target="_blank" rel="noreferrer">in</a><a aria-label="Share by email" href={`mailto:?subject=${encodeURIComponent(article.title)}`}><Mail/></a></div></section><section><h2>Save For Later</h2><Link href={`/search?q=saved+${encodeURIComponent(article.title)}`}><Bookmark/>Add to Reading List</Link></section></aside>}
function Ranked({articles}:{articles:readonly Article[]}){return <section className={styles.ranked}><h2>Most Read</h2>{articles.slice(0,5).map((story,index)=><Link href={`/article/${story.slug}`} key={story.id}><b>{String(index+1).padStart(2,"0")}</b>{story.heroImage?<span><Image alt="" fill sizes="55px" src={story.heroImage.src}/></span>:null}<h3>{story.title}</h3></Link>)}</section>}
function SummitPromo(){return <section className={styles.summit}><Image alt="Leadership summit auditorium" fill sizes="290px" src="/images/events/leadership-summit-hero.png"/><span/><div><p>The Perspective.</p><h2>Leadership Summit 2026</h2><h3>Where Ideas, Leaders &amp;<br/>Industries Meet.</h3><ul><li><CalendarDays/>May 29–30, 2026</li><li><MapPin/>New Delhi, India</li></ul><Link href="/events">Register Now</Link><Link href="/events#agenda">View Agenda</Link></div></section>}
function AuthorSide({article}:{article:ArticleDetail}){const author=article.authors[0];if(!author)return null;const more=getArticlesByAuthor(author.id).filter(item=>item.id!==article.id).slice(0,3);return <><section className={styles.authorSide}><h2>About the Author</h2><div><span><Avatar article={article} size="60px"/></span><p><b>{author.name}</b><small>{author.role}</small></p></div><p>{author.biography}</p><Link href={`/author/${author.slug}`}>View All Articles <ChevronRight/></Link></section>{more.length?<section className={styles.moreAuthor}><h2>More From This Author</h2>{more.map(story=><Link href={`/article/${story.slug}`} key={story.id}>{story.heroImage?<span><Image alt="" fill sizes="70px" src={story.heroImage.src}/></span>:null}<div><h3>{story.title}</h3><time>{formatEditorialDate(story.publishedAt??story.updatedAt)}</time></div></Link>)}</section>:null}</>}
function Related({articles}:{articles:readonly Article[]}){return <section className={styles.related}><header><h2>Related Stories</h2><Link href="/latest">View All Stories <ChevronRight/></Link></header><div>{articles.slice(0,4).map(story=><article key={story.id}>{story.heroImage?<Link className={styles.relatedImage} href={`/article/${story.slug}`}><Image alt={story.heroImage.alt} fill sizes="250px" src={story.heroImage.src}/></Link>:null}<p>{story.subcategory??story.category.name}</p><h3><Link href={`/article/${story.slug}`}>{story.title}</Link></h3><small>{formatEditorialDate(story.publishedAt??story.updatedAt)} · {story.readingMinutes} min read</small></article>)}</div></section>}
function Briefing(){return <section className={styles.briefing}><div><h2>The Perspective<br/>Briefing</h2><p>The best essays, opinions and insights delivered to your inbox every week.</p><form action="/search"><input aria-label="Email address" name="q" placeholder="Enter your email address" type="email"/><button>Subscribe</button></form></div><span>☕</span></section>}
function BottomCta(){return <section className={`${styles.bottomCta} ${styles.shell}`}><article><div><h2>Enjoy Exclusive Analysis &amp; Deep Dives</h2><p>Go beyond the headlines with premium stories, expert interviews and in-depth research.</p><Link href="/magazine/premium">Explore Premium</Link></div></article><article><span>♛</span><div><h2>Share Your Perspective</h2><p>Join the global conversation. Publish your ideas and reach leaders who care about impact.</p><Link href="/search?q=submit+opinion">Submit an Opinion</Link></div></article></section>}

export function ArticleRedesign({article,relatedStories,mostRead}:{article:ArticleDetail;relatedStories:readonly Article[];mostRead:readonly Article[]}){const author=article.authors[0];const published=article.publishedAt??article.updatedAt;return <div className={styles.page}><Breaking/><div className={styles.shell}><nav className={styles.breadcrumb}><Link href="/">Home</Link><ChevronRight/><Link href={`/${article.category.slug}`}>{article.category.name}</Link><ChevronRight/><span>{article.title}</span></nav><header className={styles.articleHeader}><p>{article.category.name}</p><h1>{article.title}</h1><h2>{article.dek??article.excerpt}</h2><div className={styles.byline}><div><span><Avatar article={article}/></span><p><b>By <Link href={`/author/${author?.slug}`}>{author?.name??"The Perspective"}</Link></b><small>{author?.role??"The Perspective newsroom"}</small></p></div><p><time dateTime={published}>{formatEditorialDate(published)}</time><i/> {article.readingMinutes} min read</p><nav><Link href="#article-content"><Headphones/>Listen to Article</Link><Link href="/search?q=saved"><Bookmark/>Save</Link><Link href={`mailto:?subject=${encodeURIComponent(article.title)}`}><Share2/>Share</Link></nav></div></header><div className={styles.articleGrid}><ShareRail article={article}/><main><figure className={styles.heroImage}>{article.heroImage?<Image alt={article.heroImage.alt} fill priority sizes="(max-width:850px) 100vw, 700px" src={article.heroImage.src}/>:null}</figure><figcaption className={styles.heroCaption}><span>{article.imageCaption??article.heroImage?.alt}</span><span>{article.imageCredit??"Image: The Perspective"}</span></figcaption><div id="article-content"><ArticleBody content={article.content}/></div></main><aside className={styles.rightRail}><Ranked articles={mostRead}/><SummitPromo/><AuthorSide article={article}/></aside></div><div className={styles.afterArticle}><Related articles={relatedStories}/><Briefing/></div></div><BottomCta/><section className={styles.archive}><div className={styles.shell}><p>Complete article experience</p><h2>Continue with the original long-form reader.</h2><p>The current article design, complete body, tags, author biography and discovery sidebar remain available below.</p></div></section></div>}
