"use client";

import Image from "next/image";
import Link from "next/link";
import {
  Activity, ArrowRight, BellRing, BookOpen, CalendarDays, Check, CircleDollarSign,
  Clock3, Download, ExternalLink, FileCheck2, FileImage, FileText, Film, FolderOpen,
  Gauge, Headphones, ImageIcon, Mail, Mic2,
  MoreHorizontal, PenLine, Plus, Search, Send, ShieldCheck, Sparkles,
  Upload, UserRound, Users, Video,
} from "lucide-react";
import styles from "./delivery.module.css";

type Tone = "green" | "orange" | "red" | "blue" | "purple";
type Action = { label: string; href: string; icon?: React.ComponentType<{ size?: number }> };
type ListEntry = { title: string; meta: string; status?: string; tone?: Tone; time?: string };

const people = {
  arjun: "/images/home/arjun-mehta-cutout.png",
  sarah: "/images/authors/ananya-mehta-featured.png",
  michael: "/images/articles/daniel-kim.png",
  emma: "/images/home/elena-rossi-cutout.png",
  david: "/images/articles/marcus-chen.png",
};

const cover = "/images/personal-magazines/sophia-reynolds-cover-v2.png";
const eventHero = "/images/events/leadership-summit-hero.png";
const podcastHero = "/images/podcasts/naveen-malhotra-hero.webp";
const videoHero = "/images/videos/naveen-malhotra-featured-interview.png";

function Button({ label, href, primary, tone = "" }: { label: string; href: string; primary?: boolean; tone?: "danger" | "success" | "" }) {
  return <Link className={`${styles.button} ${primary ? styles.primary : ""} ${tone ? styles[tone] : ""}`} href={href}>{label}{primary && <ArrowRight size={14} />}</Link>;
}

function Header({ eyebrow, title, subtitle, actions }: { eyebrow: string; title: string; subtitle: string; actions: Action[] }) {
  return <header className={styles.header}><div><p className={styles.eyebrow}>{eyebrow}</p><h1>{title}</h1><p>{subtitle}</p></div><div className={styles.headerActions}>{actions.map((a, i) => <Button key={a.label} label={a.label} href={a.href} primary={i === actions.length - 1} />)}</div></header>;
}

function Status({ children, tone = "blue" }: { children: React.ReactNode; tone?: Tone }) {
  return <span className={styles.status} data-tone={tone}>{children}</span>;
}

function Panel({ title, link, href = "#", children, className = "" }: { title: string; link?: string; href?: string; children: React.ReactNode; className?: string }) {
  return <section className={`${styles.panel} ${className}`}><header className={styles.panelHeader}><h2>{title}</h2>{link && <Link href={href}>{link}</Link>}</header>{children}</section>;
}

function Tabs({ items }: { items: string[] }) {
  return <nav className={styles.tabs} aria-label="Workspace sections">{items.map((item) => <button type="button" key={item}>{item}</button>)}</nav>;
}

function Ring({ value, label = "Healthy" }: { value: number; label?: string }) {
  return <div className={styles.ring} style={{ "--value": value } as React.CSSProperties}><b>{value}%</b><small>{label}</small></div>;
}

function Person({ name, role, image = people.arjun }: { name: string; role: string; image?: string }) {
  return <div className={styles.person}><Image src={image} alt="" width={34} height={34} /><p><b>{name}</b><small>{role}</small></p></div>;
}

function Hero({ image, initials, title, subtitle, stats }: { image?: string; initials?: string; title: string; subtitle: string; stats: { label: string; value: React.ReactNode; meta?: string }[] }) {
  return <section className={styles.hero}><div className={styles.identity}>{image ? <Image src={image} alt="" width={74} height={86} /> : <span>{initials}</span>}<div><h2>{title}</h2><p>{subtitle}</p><Link href="#overview">View full profile <ExternalLink size={10} /></Link></div></div>{stats.map((s) => <div className={styles.heroStat} key={s.label}><small>{s.label}</small><strong>{s.value}</strong>{s.meta && <span>{s.meta}</span>}</div>)}</section>;
}

function Rows({ entries }: { entries: ListEntry[] }) {
  return <div className={styles.rows}>{entries.map((entry) => <div className={styles.row} key={`${entry.title}-${entry.meta}`}><div><b>{entry.title}</b><small>{entry.meta}</small></div>{entry.status ? <Status tone={entry.tone}>{entry.status}</Status> : <span />}{entry.time && <time>{entry.time}</time>}</div>)}</div>;
}

function TaskList({ items }: { items: ListEntry[] }) {
  return <div>{items.map((item) => <div className={styles.listItem} key={item.title}><i /><div><b>{item.title}</b><small>{item.meta}</small></div>{item.status ? <Status tone={item.tone}>{item.status}</Status> : <time>{item.time}</time>}</div>)}</div>;
}

function Progress({ value, tone = "" }: { value: number; tone?: "green" | "orange" | "red" | "" }) {
  return <div className={`${styles.progress} ${tone ? styles[tone] : ""}`}><i style={{ width: `${value}%` }} /></div>;
}

function Workflow({ stages, current }: { stages: string[]; current: number }) {
  return <section className={styles.workflow}>{stages.map((stage, i) => <article className={i < current ? styles.done : i === current ? styles.current : ""} key={stage}><i>{i < current ? <Check size={13} /> : i + 1}</i><b>{stage}</b><small>{i < current ? "Completed" : i === current ? "In progress" : "Pending"}</small></article>)}</section>;
}

function Actions({ items }: { items: Action[] }) {
  return <div className={styles.actionGrid}>{items.map((item) => { const Icon = item.icon ?? Plus; return <Link href={item.href} key={item.label}><Icon size={20} /><span>{item.label}</span></Link>; })}</div>;
}

function Files({ compact = false }: { compact?: boolean }) {
  const items = [
    ["Magazine_Layout_01.indd", cover], ["Draft_Article_Arjun.pdf", "/images/articles/global-leadership.png"],
    ["Cover_Concept_02.jpg", cover], ["Interview_Notes.docx", "/images/articles/arjun-mehta.png"],
    ["Brand_Guidelines.pdf", "/images/articles/computing-infrastructure.png"],
  ];
  return <div className={styles.files}>{items.slice(0, compact ? 4 : 5).map(([name, src]) => <article className={styles.file} key={name}><div className={styles.filePreview}><Image src={src} alt="" width={180} height={100} /></div><b>{name}</b><small>Updated May 15, 2024</small></article>)}</div>;
}

const clientActions: Action[] = [
  { label: "Create Project", href: "/app/projects/personal-magazine-arjun-mehta-q2", icon: FolderOpen },
  { label: "Send Message", href: "/app/inbox", icon: Mail },
  { label: "Schedule Meeting", href: "/app/meetings", icon: CalendarDays },
  { label: "Create Contract", href: "/app/contracts/cont-2024-0087", icon: FileCheck2 },
  { label: "Create Invoice", href: "/app/invoices/inv-2024-0031", icon: CircleDollarSign },
  { label: "Upload Asset", href: "/app/files", icon: Upload },
  { label: "Request Approval", href: "/app/approvals", icon: ShieldCheck },
  { label: "Open Client Portal", href: "/client", icon: ExternalLink },
];

export function Client360Screen() {
  return <main className={styles.page} id="overview"><Header eyebrow="CLIENTS / NEXTPAY TECHNOLOGIES / CLIENT 360" title="NextPay Technologies Inc." subtitle="Strategic client · Premium package · Active since May 15, 2024" actions={[{ label: "Send Message", href: "/app/inbox" }, { label: "Schedule Meeting", href: "/app/meetings" }, { label: "Open Client Portal", href: "/client" }]} />
    <Hero initials="N" title="NextPay Technologies Inc." subtitle="Financial Technology · Payments Infrastructure · California, USA" stats={[
      { label: "Primary Contact", value: "Arjun Mehta", meta: "Founder & CEO" }, { label: "Account Manager", value: "Sarah Johnson", meta: "Sales Director" },
      { label: "Client Health", value: <Ring value={85} /> }, { label: "Lifetime Value", value: "$185,000", meta: "USD" },
      { label: "Active Projects", value: "4" }, { label: "Outstanding", value: "$46,200", meta: "2 invoices" },
    ]} />
    <Tabs items={["Overview", "Contacts 6", "Communication", "Meetings 8", "Deals 3", "Projects 4", "Contracts 2", "Invoices 6", "Payments 6", "Assets 32", "Approvals 5", "Publishing", "Distribution", "Reports", "Renewals 1", "Activity"]} />
    <div className={styles.grid4}>
      <Panel title="About NextPay Technologies"><p>NextPay is a fast-growing fintech company building modern payment infrastructure for businesses worldwide.</p><div className={styles.compactMeta}><p><small>Industry</small><b>Financial Technology</b></p><p><small>Company size</small><b>201–500 employees</b></p><p><small>Headquarters</small><b>San Francisco, USA</b></p><p><small>Founded</small><b>2018</b></p></div></Panel>
      <Panel title="Active Projects (4)" link="View all projects" href="/app/projects/personal-magazine-arjun-mehta-q2"><Rows entries={[{ title: "Personal Magazine — Arjun Mehta", meta: "Premium Magazine", status: "In Production", tone: "blue" }, { title: "Podcast — Fintech Leadership", meta: "Podcast Production", status: "Recording", tone: "purple" }, { title: "Executive Founder Interview", meta: "Video Production", status: "Editing", tone: "orange" }]} /></Panel>
      <Panel title="Financial Overview" link="View financials" href="/app/invoices/inv-2024-0031"><div className={styles.summaryCards}><div className={styles.summaryCard}><small>Total invoiced</small><strong>$154,000</strong></div><div className={styles.summaryCard}><small>Total paid</small><strong>$107,800</strong></div><div className={styles.summaryCard}><small>Outstanding</small><strong>$46,200</strong></div></div><Rows entries={[{ title: "INV-2024-0031", meta: "Due May 30, 2024", status: "Open", tone: "orange" }]} /></Panel>
      <Panel title="Relationship & Health" link="View details"><div className={styles.inline}><Ring value={85} /><TaskList items={[{ title: "On-time payments", meta: "Healthy" }, { title: "Active engagement", meta: "High" }, { title: "Projects on track", meta: "4 of 4" }]} /></div></Panel>
      <Panel title="Key Contacts (6)" link="View all contacts"><Rows entries={[{ title: "Arjun Mehta", meta: "Founder & CEO", status: "Primary", tone: "green" }, { title: "Sarah Parker", meta: "COO", status: "Decision Maker", tone: "blue" }, { title: "David Wilson", meta: "Finance Director", status: "Finance", tone: "purple" }]} /></Panel>
      <Panel title="Recent Communication" link="View all" href="/app/inbox"><Rows entries={[{ title: "Follow up on proposal", meta: "Email · May 15, 2:45 PM" }, { title: "Magazine draft feedback", meta: "Email · May 14, 11:30 AM" }, { title: "Project update — Podcast", meta: "Message · May 13, 4:10 PM" }]} /></Panel>
      <Panel title="Approvals (5)" link="View all approvals" href="/app/approvals"><Rows entries={[{ title: "Magazine Draft v1", meta: "Requested May 15", status: "Pending", tone: "orange" }, { title: "Podcast Episode Outline", meta: "Requested May 14", status: "Pending", tone: "orange" }, { title: "Photo Selection", meta: "Requested May 13", status: "Approved", tone: "green" }]} /></Panel>
      <Panel title="Recent Activity" link="View all activity"><TaskList items={[{ title: "Invoice sent", meta: "INV-2024-0031", time: "3:20 PM" }, { title: "Payment received", meta: "PAY-2024-0012", time: "2:25 PM" }, { title: "Magazine draft uploaded", meta: "by Sarah Johnson", time: "11:15 AM" }]} /></Panel>
    </div><Panel title="Quick Actions"><Actions items={clientActions} /></Panel>
  </main>;
}

export function ClientOnboardingScreen() {
  const stages = ["Commercial Complete", "Client Access", "Editorial Setup", "Assets & Content", "Internal Setup", "Kickoff & Start", "Onboarding Complete"];
  return <main className={styles.page}><Header eyebrow="CLIENTS / NEXTPAY / ONBOARDING" title="Client Onboarding Workspace" subtitle="ONB-2024-0021 · Target completion May 30, 2024 · 15 days left" actions={[{ label: "Invite to Portal", href: "/client" }, { label: "Send Questionnaire", href: "/client/questionnaires" }, { label: "Schedule Kickoff", href: "/app/meetings" }]} />
    <Hero initials="N" title="NextPay Technologies Inc." subtitle="Premium Magazine onboarding" stats={[{ label: "Account Manager", value: "Sarah Johnson", meta: "Sales Director" }, { label: "Onboarding Owner", value: "Michael Chen" }, { label: "Contract", value: <Status tone="green">Signed</Status>, meta: "May 13, 2024" }, { label: "Payment", value: <Status tone="green">Paid</Status>, meta: "$46,200" }, { label: "Portal", value: <Status tone="orange">Invited</Status> }, { label: "Overall Progress", value: <Ring value={68} label="In progress" /> }]} />
    <Tabs items={["Onboarding Overview", "Tasks & Checklist", "Questionnaire", "Assets", "Team & Access", "Kickoff", "Documents", "Activity"]} />
    <div className={styles.overview}><div className={styles.mainStack}><div className={styles.grid3}>
      <Panel title="Client Primary Contact"><Person name="Arjun Mehta" role="Founder & CEO" /><TaskList items={[{ title: "arjun.mehta@nextpay.com", meta: "+1 (415) 555-0176" }, { title: "500 California Street", meta: "San Francisco, CA" }]} /></Panel>
      <Panel title="Onboarding Progress & Checklist" className={styles.gridSpan2}>{stages.map((stage, i) => <div className={styles.row} key={stage}><div><b>{i + 1}. {stage}</b><small>{i < 1 ? "All requirements complete" : i < 5 ? "Tasks are actively progressing" : "Scheduled after dependencies"}</small></div><Progress value={[100, 67, 50, 20, 60, 0, 0][i]} tone={i === 3 ? "red" : i < 1 ? "green" : "orange"} /><Status tone={i < 1 ? "green" : i < 5 ? "orange" : "blue"}>{i < 1 ? "Completed" : i < 5 ? "In Progress" : "Pending"}</Status></div>)}</Panel>
    </div><div className={styles.taskColumns}><Panel title="Pending Client Actions" link="View all"><TaskList items={[{ title: "Complete questionnaire", meta: "Due May 18", status: "High", tone: "red" }, { title: "Upload company logo", meta: "Due May 18", status: "High", tone: "red" }, { title: "Provide executive bio", meta: "Due May 20", status: "Medium", tone: "orange" }, { title: "Confirm image usage rights", meta: "Due May 20", status: "Medium", tone: "orange" }]} /></Panel><Panel title="Pending Internal Actions" link="View all"><TaskList items={[{ title: "Review questionnaire", meta: "After client submission" }, { title: "Confirm asset quality", meta: "Due May 20" }, { title: "Assign editor & designer", meta: "Due May 20" }]} /></Panel></div>
    <Panel title="Onboarding Timeline"><Workflow stages={["Not Started", "Portal Invited", "Portal Activated", "Commercial Complete", "Questionnaire", "Assets", "Kickoff", "In Progress", "Completed"]} current={4} /></Panel></div>
    <aside className={styles.rail}><Panel title="Key Dates"><Rows entries={[{ title: "Onboarding started", meta: "May 15, 2024" }, { title: "Target completion", meta: "May 30, 2024", status: "15 days left", tone: "red" }, { title: "Kickoff meeting", meta: "May 20, 11:00 AM" }, { title: "Estimated project start", meta: "June 1, 2024" }]} /></Panel><Panel title="Blockers"><TaskList items={[{ title: "Questionnaire not completed", meta: "Cannot proceed without it", status: "High", tone: "red" }, { title: "Required assets pending", meta: "Headshot, logo and bio", status: "High", tone: "red" }]} /></Panel><Panel title="Recent Activity"><TaskList items={[{ title: "Contract signed", meta: "by Arjun Mehta", time: "May 13" }, { title: "Payment received", meta: "$46,200", time: "May 14" }, { title: "Portal invitation sent", meta: "by Michael Chen", time: "May 15" }]} /></Panel><Panel title="Project Summary"><p>Future project will be created after onboarding completion.</p><div className={styles.compactMeta}><p><small>Project type</small><b>Personal Magazine</b></p><p><small>Target delivery</small><b>July 30, 2024</b></p></div><Button label="Create Project After Onboarding" href="/app/projects/personal-magazine-arjun-mehta-q2" /></Panel></aside></div>
  </main>;
}

export function Project360Screen() {
  return <main className={styles.page}><Header eyebrow="PROJECTS / PERSONAL MAGAZINE / PROJECT 360" title="Project Workspace / Project 360" subtitle="PRJ-2024-0042 · Personal Magazine Classic · Created May 15, 2024" actions={[{ label: "Update Stage", href: "#workflow" }, { label: "Add Task", href: "#actions" }, { label: "Request Approval", href: "/app/approvals" }]} />
    <Hero image={cover} title="Personal Magazine — Arjun Mehta Q2" subtitle="NextPay Technologies Inc. · Premium Package" stats={[{ label: "Project Owner", value: "Sarah Johnson", meta: "Editorial Director" }, { label: "Account Manager", value: "Michael Chen" }, { label: "Health", value: <Ring value={82} /> }, { label: "Progress", value: "58%", meta: "Design in progress" }, { label: "Budget / Spent", value: "$15,000", meta: "$6,750 used" }, { label: "Due Date", value: "Jun 30, 2024", meta: "46 days left" }]} />
    <Tabs items={["Overview", "Workflow", "Tasks 18", "Team 8", "Messages 12", "Meetings 4", "Files 35", "Editorial 7", "Design / Media 12", "Approvals 5", "Publishing", "Distribution", "Reports", "Activity"]} />
    <div className={styles.overview}><div className={styles.mainStack}><Panel title="Workflow Stage" link="View full workflow"><Workflow stages={["Kickoff", "Content", "Design", "Review", "Final Approval", "Publish"]} current={2} /></Panel><div className={styles.taskColumns}><Panel title="Pending Client Actions" link="View all"><TaskList items={[{ title: "Review cover concepts", meta: "Due May 17", status: "High", tone: "red" }, { title: "Provide final bio & quotes", meta: "Due May 18", status: "High", tone: "red" }, { title: "Review magazine draft", meta: "Due June 18", status: "Medium", tone: "orange" }]} /></Panel><Panel title="Pending Internal Actions" link="View all"><TaskList items={[{ title: "Finalize page layouts 10–20", meta: "Due May 16", status: "High", tone: "red" }, { title: "Prepare design proofs", meta: "Due June 10", status: "Medium", tone: "orange" }, { title: "Generate final PDF proofs", meta: "Due June 18", status: "Medium", tone: "orange" }]} /></Panel></div><Panel title="Recent Files" link="View all files" href="/app/files"><Files /></Panel></div>
      <aside className={styles.rail}><Panel title="Project Progress"><div className={styles.inline}><Ring value={58} label="Progress" /><div><b>7 completed</b><p>3 in progress · 2 pending</p></div></div></Panel><Panel title="Milestones"><TaskList items={[{ title: "Kickoff & Questionnaire", meta: "May 15", status: "Completed", tone: "green" }, { title: "Content & Drafting", meta: "May 28", status: "Completed", tone: "green" }, { title: "Design & Layout", meta: "June 05", status: "In Progress", tone: "blue" }, { title: "Client Review & Proofs", meta: "June 20", status: "Pending", tone: "orange" }]} /></Panel><Panel title="Assigned Team" link="View team"><Rows entries={[{ title: "Sarah Johnson", meta: "Project Owner" }, { title: "Michael Chen", meta: "Account Manager" }, { title: "Emma Davis", meta: "Senior Designer" }, { title: "David Wilson", meta: "Editor" }]} /></Panel><Panel title="Recent Activity"><TaskList items={[{ title: "Cover concept v2 uploaded", meta: "by Emma Davis", time: "3:20 PM" }, { title: "Page layouts completed", meta: "by David Wilson", time: "11:15 AM" }, { title: "Portal invitation sent", meta: "by Michael Chen", time: "9:20 AM" }]} /></Panel></aside></div>
    <Panel title="Quick Actions"><Actions items={[{ label: "Update Stage", href: "#workflow" }, { label: "Add Task", href: "#actions" }, { label: "Assign Team", href: "#team", icon: Users }, { label: "Schedule Meeting", href: "/app/meetings", icon: CalendarDays }, { label: "Upload File", href: "/app/files", icon: Upload }, { label: "Request Client Action", href: "/client/tasks", icon: UserRound }, { label: "Request Approval", href: "/app/approvals", icon: ShieldCheck }, { label: "Open Editorial", href: "/app/editorial/projects/future-of-leadership", icon: PenLine }]} /></Panel>
  </main>;
}

export function EditorialWorkflowScreen() {
  const editorialStages = ["Brief", "Questionnaire", "Research", "Writer Assigned", "Drafting", "Internal Review", "Client Review", "Revisions", "Client Approved", "SEO Review", "Publication Ready"];
  return <main className={styles.page}><Header eyebrow="PROJECTS / EDITORIAL / ARTICLE" title="Editorial Project / Editorial Workflow" subtitle="Executive Feature · English · 1,500–2,000 words · Draft v2.1" actions={[{ label: "Assign Writer", href: "#team" }, { label: "Request Client Review", href: "/client/drafts" }, { label: "Request Approval", href: "/app/approvals" }]} />
    <Hero image={cover} title="The Future of Leadership" subtitle="Exclusive feature with Arjun Mehta, Founder & CEO" stats={[{ label: "Client", value: "NextPay Technologies" }, { label: "Project Owner", value: "Sarah Johnson", meta: "Editorial Director" }, { label: "Writer", value: "David Wilson", meta: "Senior Writer" }, { label: "Priority", value: <Status tone="red">High</Status> }, { label: "Deadline", value: "May 30, 2024", meta: "15 days left" }, { label: "Current Stage", value: <Status tone="purple">Client Review</Status>, meta: "SEO 72%" }]} />
    <Tabs items={["Overview", "Brief", "Questionnaire", "Research", "Drafts 4", "Internal Review 2", "Client Review 1", "Revisions 3", "Approvals 2", "Assets 6", "SEO 1", "Publication", "Activity"]} />
    <Workflow stages={editorialStages} current={6} />
    <div className={styles.overview}><div className={styles.mainStack}><div className={styles.grid3}><Panel title="Editorial Brief"><div className={styles.compactMeta}><p><small>Topic</small><b>The Future of Leadership</b></p><p><small>Angle</small><b>Leadership, technology and purpose</b></p><p><small>Audience</small><b>C-level executives</b></p><p><small>Tone</small><b>Authoritative and insightful</b></p></div></Panel><Panel title="Current Stage"><Status tone="purple">Client Review</Status><p style={{ marginTop: 12 }}>The draft has been shared with the client. Feedback and approval are required before SEO review.</p><TaskList items={[{ title: "Client review deadline", meta: "May 24, 2024", status: "4 days", tone: "red" }, { title: "Address client feedback", meta: "Next action" }]} /></Panel><Panel title="Drafts & Versions" link="Compare versions"><Rows entries={[{ title: "Draft v2.1", meta: "Shared with client", status: "Current", tone: "purple" }, { title: "Draft v2.0", meta: "Internal revision" }, { title: "Draft v1.0", meta: "Initial draft" }, { title: "Outline v1.0", meta: "Approved" }]} /></Panel></div><div className={styles.taskColumns}><Panel title="Pending Client Actions"><TaskList items={[{ title: "Review Draft v2.1", meta: "Due May 24", status: "High", tone: "red" }, { title: "Provide missing assets", meta: "Headshot and company logo", status: "Medium", tone: "orange" }, { title: "Confirm key message", meta: "Validate quotes", status: "Medium", tone: "orange" }]} /></Panel><Panel title="Pending Internal Actions"><TaskList items={[{ title: "Address client feedback", meta: "Due May 25", status: "High", tone: "red" }, { title: "Fact check & verify data", meta: "Due May 26", status: "Medium", tone: "orange" }, { title: "Optimize for SEO", meta: "After client approval", status: "Low", tone: "green" }]} /></Panel></div><Panel title="Blockers & Risks"><div className={styles.grid3}><div className={styles.notice}><b>Missing Assets</b><span>Headshot and logo required</span></div><div className={styles.notice}><b>Client Approval Pending</b><span>May affect timeline</span></div><div className={styles.notice}><b>SEO Optimization</b><span>Blocked until approval</span></div></div></Panel></div>
    <aside className={styles.rail}><Panel title="Publication Readiness"><div className={styles.inline}><Ring value={72} label="Ready" /><TaskList items={[{ title: "Content quality", meta: "85%" }, { title: "Fact check", meta: "60%" }, { title: "Assets", meta: "50%" }, { title: "Approvals", meta: "30%" }]} /></div></Panel><Panel title="Upcoming Deadlines"><Rows entries={[{ title: "Client review", meta: "May 24", status: "4 days", tone: "red" }, { title: "Revision deadline", meta: "May 27", status: "7 days", tone: "orange" }, { title: "Publication ready", meta: "May 30", status: "10 days", tone: "blue" }]} /></Panel><Panel title="Key Actions"><Actions items={[{ label: "Create Questionnaire", href: "/app/editorial/questionnaires" }, { label: "Start Draft", href: "/app/editorial/drafts", icon: PenLine }, { label: "Internal Review", href: "/app/editorial/reviews", icon: FileCheck2 }, { label: "Client Review", href: "/client/drafts", icon: Users }, { label: "Request Approval", href: "/app/approvals", icon: ShieldCheck }, { label: "Mark Ready", href: "#publication", icon: Send }]} /></Panel></aside></div>
  </main>;
}

type ProductionConfig = { kind: string; title: string; subtitle: string; image: string; stages: string[]; current: number; tabs: string[]; statusRows: ListEntry[]; milestones: ListEntry[]; actions: Action[]; progress: number };

function ProductionWorkspace({ config }: { config: ProductionConfig }) {
  return <main className={styles.page}><Header eyebrow={`PROJECTS / ${config.kind.toUpperCase()} PRODUCTION`} title={config.title} subtitle={config.subtitle} actions={config.actions.slice(0, 3)} />
    <Hero image={config.image} title={config.kind === "Podcast" ? "Ep. 12 — Leading with Purpose" : config.kind === "Video" ? "Executive Insights — Arjun Mehta" : "The Perspective — Arjun Mehta Q2"} subtitle="NextPay Technologies Inc. · Premium production" stats={[{ label: "Project Owner", value: "Sarah Johnson" }, { label: config.kind === "Magazine" ? "Designer" : "Producer", value: "Emma Davis" }, { label: "Overall Progress", value: <Ring value={config.progress} label="Progress" /> }, { label: "Current Stage", value: <Status tone="blue">In Production</Status> }, { label: "Priority", value: <Status tone="red">High</Status> }, { label: "Publish Target", value: "May 30, 2024", meta: "10 days left" }]} />
    <Tabs items={config.tabs} />
    <div className={styles.productionGrid}><Panel title="Production Workflow"><div className={styles.stageList}>{config.stages.map((stage, i) => <div className={`${styles.stage} ${i < config.current ? styles.done : i === config.current ? styles.current : ""}`} key={stage}><i>{i < config.current ? <Check size={10} /> : i + 1}</i><b>{stage}</b><Status tone={i < config.current ? "green" : i === config.current ? "blue" : "orange"}>{i < config.current ? "Completed" : i === config.current ? "In Progress" : "Pending"}</Status></div>)}</div></Panel>
      <div className={styles.mainStack}><div className={styles.grid3}><Panel title={`${config.kind} Summary`}><div className={styles.compactMeta}><p><small>Project</small><b>{config.title.replace(" Workspace", "")}</b></p><p><small>Client</small><b>NextPay Technologies</b></p><p><small>Language</small><b>English</b></p><p><small>Format</small><b>{config.kind === "Magazine" ? "Digital + Print" : config.kind === "Podcast" ? "Video Podcast" : "4K Video"}</b></p></div><Progress value={config.progress} tone="green" /></Panel><Panel title="Content & Production Status"><Rows entries={config.statusRows} /></Panel><Panel title="Upcoming Milestones" link="View all"><Rows entries={config.milestones} /></Panel></div><div className={styles.grid3}><Panel title={config.kind === "Magazine" ? "Recent Proofs" : config.kind === "Video" ? "Latest Footage" : "Recent Files"}><Files compact /></Panel><Panel title="Pending Approvals" link="View all" href="/app/approvals"><Rows entries={[{ title: `${config.kind} internal review`, meta: "Requested by Sarah Johnson", status: "High", tone: "red" }, { title: "Client review package", meta: "Due May 28", status: "Pending", tone: "orange" }, { title: "Final production approval", meta: "Due May 29", status: "High", tone: "red" }]} /></Panel><Panel title="Recent Activity"><TaskList items={[{ title: "New production version uploaded", meta: "by Emma Davis", time: "2:30 PM" }, { title: "Internal notes added", meta: "by David Wilson", time: "11:15 AM" }, { title: "Client review requested", meta: "by Sarah Johnson", time: "9:45 AM" }]} /></Panel></div></div>
      <aside className={styles.rail}><Panel title="Production Health"><div className={styles.inline}><Ring value={82} /><TaskList items={[{ title: "Schedule", meta: "85%" }, { title: "Budget", meta: "78%" }, { title: "Quality", meta: "90%" }, { title: "Risk score", meta: "Low" }]} /></div></Panel><Panel title="Tasks Overview"><div className={styles.summaryCards}><div className={styles.summaryCard}><small>Total</small><strong>24</strong></div><div className={styles.summaryCard}><small>In progress</small><strong>7</strong></div><div className={styles.summaryCard}><small>Blocked</small><strong>2</strong></div></div></Panel><Panel title="Quick Actions"><Actions items={config.actions} /></Panel></aside></div>
  </main>;
}

export function MagazineProductionScreen() { return <ProductionWorkspace config={{ kind: "Magazine", title: "Personal Magazine Production Workspace", subtitle: "Q2 2024 Edition · Digital + Print · Executive Magazine v2", image: cover, progress: 64, current: 7, stages: ["Questionnaire & Brief", "Interview & Content", "Article Drafting", "Editorial Approval", "Assets Collection", "Cover Concepts", "Cover Approval", "Page Design", "Internal Design Review", "Client Design Review", "Revisions", "Final Proof", "Final Approval", "Digital Reader Build", "Publication", "Distribution & Delivery"], tabs: ["Overview", "Cover 5", "Articles 10", "Page Layouts 40", "Assets 68", "Proofs 3", "Internal Review 2", "Client Review 3", "Approvals 2", "Digital Reader", "Publishing", "Distribution", "Files", "Tasks 24", "Team", "Activity"], statusRows: [{ title: "Articles", meta: "7 / 10", status: "70%", tone: "green" }, { title: "Page layouts", meta: "28 / 40", status: "70%", tone: "blue" }, { title: "Images / visuals", meta: "42 / 60", status: "70%", tone: "orange" }, { title: "Infographics", meta: "6 / 10", status: "60%", tone: "purple" }], milestones: [{ title: "Client design review", meta: "May 22", status: "2 days", tone: "red" }, { title: "Final revisions", meta: "May 24", status: "4 days", tone: "red" }, { title: "Digital Reader build", meta: "May 29", status: "9 days", tone: "blue" }], actions: [{ label: "Preview Magazine", href: "/magazine/read/august-2026", icon: BookOpen }, { label: "Request Approval", href: "/app/approvals", icon: ShieldCheck }, { label: "Upload Assets", href: "/app/files", icon: Upload }, { label: "Create Revision", href: "#revisions", icon: PenLine }, { label: "Client Review", href: "/client/designs", icon: Users }, { label: "Update Stage", href: "#workflow", icon: Activity }] }} />; }

export function PodcastProductionScreen() { return <ProductionWorkspace config={{ kind: "Podcast", title: "Podcast Production Workspace", subtitle: "The Visionary Leader · Episode 12 · Video Podcast · English", image: podcastHero, progress: 62, current: 7, stages: ["Guest Confirmed", "Guest Onboarding", "Bio & Assets", "Topic Finalized", "Talking Points Approved", "Recording Scheduled", "Recording Completed", "Editing", "Internal Review", "Guest Review", "Guest Approved", "Publication Ready", "Published", "Distributed", "Completed"], tabs: ["Overview", "Guest", "Brief", "Talking Points", "Schedule", "Recording", "Audio", "Transcript", "Internal Review 2", "Guest Review 1", "Approvals 2", "Clips 8", "Publishing", "Distribution", "Files", "Tasks 18", "Activity"], statusRows: [{ title: "Guest bio", meta: "Complete", status: "100%", tone: "green" }, { title: "Talking points", meta: "Approved", status: "100%", tone: "green" }, { title: "Audio editing", meta: "Active", status: "70%", tone: "blue" }, { title: "Transcript", meta: "Generated", status: "50%", tone: "orange" }], milestones: [{ title: "Recording completed", meta: "May 20", status: "Completed", tone: "green" }, { title: "Internal review", meta: "May 22", status: "1 day", tone: "red" }, { title: "Guest review", meta: "May 23", status: "2 days", tone: "orange" }], actions: [{ label: "Schedule Recording", href: "/app/meetings", icon: CalendarDays }, { label: "Send Guest Brief", href: "/app/inbox", icon: Send }, { label: "Request Assets", href: "/client/assets", icon: Upload }, { label: "Upload Recording", href: "/app/files", icon: Mic2 }, { label: "Create Edit", href: "#editing", icon: PenLine }, { label: "Request Approval", href: "/app/approvals", icon: ShieldCheck }] }} />; }

export function VideoProductionScreen() { return <ProductionWorkspace config={{ kind: "Video", title: "Video Production Workspace", subtitle: "Executive Interview · 4K Video · 16:9 · English", image: videoHero, progress: 58, current: 6, stages: ["Idea / Brief", "Guest Confirmed", "Script", "Pre-Production", "Shoot Scheduled", "Shoot / Recording", "Editing", "Internal Review", "Client Review", "Client Approved", "Thumbnail Ready", "Metadata Ready", "Publication Ready", "Published", "Clips Created", "Distributed", "Completed"], tabs: ["Overview", "Brief", "Script", "Pre-Production", "Schedule", "Shoot", "Footage", "Editing", "Internal Review 2", "Client Review 1", "Approvals 2", "Thumbnail", "Captions", "Clips 6", "Publishing", "Distribution", "Files", "Tasks 21", "Activity"], statusRows: [{ title: "Script", meta: "Approved", status: "100%", tone: "green" }, { title: "Shot list", meta: "36 / 45", status: "80%", tone: "green" }, { title: "Editing progress", meta: "Rough cut v2", status: "55%", tone: "blue" }, { title: "Captions / transcript", meta: "English", status: "60%", tone: "purple" }], milestones: [{ title: "Shoot date", meta: "May 22", status: "Completed", tone: "green" }, { title: "Internal review", meta: "May 26", status: "Today", tone: "red" }, { title: "Client review", meta: "May 28", status: "2 days", tone: "red" }], actions: [{ label: "Schedule Shoot", href: "/app/meetings", icon: CalendarDays }, { label: "Upload Script", href: "/app/files", icon: Upload }, { label: "Request Assets", href: "/client/assets", icon: FileImage }, { label: "Upload Footage", href: "/app/files", icon: Film }, { label: "Client Review", href: "/client/designs", icon: Users }, { label: "Request Approval", href: "/app/approvals", icon: ShieldCheck }] }} />; }

export function EventProductionScreen() {
  const stages = ["Planning", "Speaker Outreach", "Speakers Confirmed", "Partner Outreach", "Agenda Building", "Registration Open", "Pre-Event", "Live Event", "Post-Event", "Reporting", "Distribution"];
  return <main className={styles.page}><Header eyebrow="PROJECTS / EVENTS / GLOBAL LEADERSHIP SUMMIT" title="Event Production / Event Operations Workspace" subtitle="Leadership Summit · Hybrid · English · May 30–June 1, 2024" actions={[{ label: "Invite Speaker", href: "/app/inbox" }, { label: "Add Partner", href: "#partners" }, { label: "Open Registration", href: "/events/leadership-summit-2026" }]} />
    <Hero image={eventHero} title="Global Leadership Summit 2024" subtitle="Inspire. Connect. Lead the Future. · San Francisco, CA" stats={[{ label: "Budget", value: "$285,000", meta: "57% spent" }, { label: "Revenue", value: "$412,000", meta: "60% received" }, { label: "Registrations", value: "1,124 / 1,500", meta: "75% of target" }, { label: "Speakers", value: "31 / 40", meta: "Confirmed" }, { label: "Days to Event", value: "18" }, { label: "Overall Progress", value: <Ring value={64} label="On track" /> }]} />
    <Tabs items={["Overview", "Speakers", "Partners", "Agenda", "Registrations", "Logistics", "Production", "Assets", "Approvals 2", "Marketing", "Publishing", "Distribution", "Reports", "Files", "Tasks 38", "Team", "Activity"]} />
    <Workflow stages={stages} current={5} />
    <div className={styles.grid4}><Panel title="Agenda At a Glance" link="View agenda"><Rows entries={[{ title: "Opening Keynote", meta: "May 30 · 9:00 AM" }, { title: "Leadership Panel", meta: "May 30 · 11:00 AM" }, { title: "Networking Lunch", meta: "May 30 · 12:30 PM" }, { title: "Investor Forum", meta: "May 31 · 2:00 PM" }]} /></Panel><Panel title="Speakers Pipeline" link="View all"><div className={styles.summaryCards}><div className={styles.summaryCard}><small>Invited</small><strong>40</strong></div><div className={styles.summaryCard}><small>Confirmed</small><strong>31</strong></div><div className={styles.summaryCard}><small>Pending</small><strong>3</strong></div></div><Rows entries={[{ title: "Arjun Mehta", meta: "Founder & CEO", status: "Confirmed", tone: "green" }, { title: "Maria Rodriguez", meta: "CEO, FutureLabs", status: "Confirmed", tone: "green" }]} /></Panel><Panel title="Production Status"><Rows entries={[{ title: "Stage & AV setup", meta: "Production", status: "80%", tone: "green" }, { title: "Streaming setup", meta: "Hybrid platform", status: "60%", tone: "orange" }, { title: "On-site operations", meta: "Run of show", status: "70%", tone: "blue" }]} /></Panel><Panel title="Registration Overview"><div className={styles.inline}><Ring value={75} label="Target" /><TaskList items={[{ title: "General admission", meta: "642" }, { title: "VIP", meta: "228" }, { title: "Virtual only", meta: "96" }]} /></div></Panel><Panel title="Key Documents & Files" link="View all files" href="/app/files"><Files compact /></Panel><Panel title="Recent Activity"><TaskList items={[{ title: "Agenda v3 uploaded", meta: "by Michael Chen", time: "3:00 PM" }, { title: "Speaker confirmed", meta: "Lisa Chen", time: "1:15 PM" }, { title: "Production task updated", meta: "Stage & AV 80%", time: "11:45 AM" }]} /></Panel><Panel title="Top Risks"><TaskList items={[{ title: "Keynote speaker travel delay", meta: "Logistics", status: "Medium", tone: "orange" }, { title: "Low VIP registration", meta: "Marketing", status: "High", tone: "red" }, { title: "AV equipment delivery", meta: "Production", status: "Medium", tone: "orange" }]} /></Panel><Panel title="Next Actions"><Actions items={[{ label: "Invite Speaker", href: "/app/inbox", icon: Users }, { label: "Add Partner", href: "#partners" }, { label: "Open Registration", href: "/events/leadership-summit-2026", icon: ExternalLink }, { label: "Request Approval", href: "/app/approvals", icon: ShieldCheck }, { label: "Upload Files", href: "/app/files", icon: Upload }]} /></Panel></div>
  </main>;
}

const approvals = [
  ["Magazine Cover — v3", "Magazine Cover", "Executive Insights Magazine", "Emma Davis", "Sarah Johnson", "May 15", "Pending", "High"],
  ["Article Draft — The Future of Leadership", "Article Draft", "The Perspective Magazine", "David Wilson", "Michael Chen", "Today", "In Review", "High"],
  ["Page Layout — 10 Pages", "Page Layout", "Executive Insights Magazine", "Emma Davis", "Sarah Johnson", "May 16", "Changes Requested", "Medium"],
  ["Podcast Episode — Ep.12", "Audio Edit", "The Visionary Leader", "Emma Davis", "Arjun Mehta", "Overdue", "Pending", "High"],
  ["Interview Video — Final Cut", "Video Edit", "Executive Interview Series", "David Wilson", "Sarah Johnson", "Today", "In Review", "High"],
  ["Event Agenda — Final", "Event Agenda", "Global Leadership Summit", "James Wilson", "Sarah Johnson", "May 15", "Pending", "Medium"],
];

export function ApprovalCenterScreen() {
  return <main className={styles.page}><Header eyebrow="HOME / APPROVALS" title="Approval Center" subtitle="Review, approve and track all content, designs and deliverables in one place." actions={[{ label: "Approval Settings", href: "#settings" }, { label: "Approval Workflows", href: "#workflows" }, { label: "New Approval", href: "#new" }]} />
    <div className={styles.metricGrid}>{[["Total Approvals", "186", ShieldCheck], ["Pending", "52", Clock3], ["In Review", "31", FileCheck2], ["Approved", "68", Check], ["Changes Requested", "21", PenLine], ["Rejected", "8", Activity]].map(([label, value, Icon]) => <div className={styles.metric} key={String(label)}><span>{typeof Icon !== "string" && <Icon size={19} />}</span><div><small>{String(label)}</small><strong>{String(value)}</strong></div></div>)}</div>
    <Tabs items={["All Approvals", "My Approvals 18", "Team Approvals 67", "Client Approvals 43", "Overdue 9", "High Priority 12"]} />
    <div className={styles.approvalLayout}><div className={styles.mainStack}><div className={styles.filters}><label><Search size={15} /><input placeholder="Search title, project, client, type..." /></label>{["All Types", "All Projects", "All Requesters", "All Approvers", "All Statuses", "Any Time"].map((x) => <label key={x}><select aria-label={x}><option>{x}</option></select></label>)}</div><div className={`${styles.panel} ${styles.tableWrap}`}><table className={styles.table}><thead><tr><th>Item & Details</th><th>Type</th><th>Project / Client</th><th>Requester</th><th>Approver</th><th>Due Date</th><th>Status</th><th>Priority</th></tr></thead><tbody>{approvals.map((a) => <tr key={a[0]}><td><b>{a[0]}</b><small>Version 3 · May 2024</small></td><td><Status tone="blue">{a[1]}</Status></td><td><b>{a[2]}</b><small>NextPay Technologies</small></td><td>{a[3]}</td><td>{a[4]}</td><td>{a[5]}</td><td><Status tone={a[6] === "In Review" ? "blue" : a[6] === "Changes Requested" ? "orange" : "orange"}>{a[6]}</Status></td><td><Status tone={a[7] === "High" ? "red" : "orange"}>{a[7]}</Status></td></tr>)}</tbody></table></div><div className={styles.grid3}><Panel title="Approvals by Type"><div className={styles.inline}><Ring value={68} label="Approved" /><TaskList items={[{ title: "Articles", meta: "45 (24%)" }, { title: "Magazine", meta: "38 (20%)" }, { title: "Videos", meta: "28 (15%)" }]} /></div></Panel><Panel title="Approval SLA"><Rows entries={[{ title: "On time", meta: "82%", status: "Healthy", tone: "green" }, { title: "At risk", meta: "12%", status: "Watch", tone: "orange" }, { title: "Missed", meta: "6%", status: "Action", tone: "red" }]} /></Panel><Panel title="Activity Feed"><TaskList items={[{ title: "Magazine Cover v2 approved", meta: "by Sarah Johnson", time: "11:45 AM" }, { title: "Changes requested", meta: "Article Draft v2", time: "10:20 AM" }, { title: "Video v2 uploaded", meta: "by David Wilson", time: "9:15 AM" }]} /></Panel></div></div>
      <aside className={styles.drawer}><header><h2>Approval Details</h2><MoreHorizontal size={18} /></header><div className={styles.cover}><Image src={cover} alt="Magazine cover v3" width={240} height={320} /></div><div><h2>Magazine Cover — v3</h2><p>Executive Insights Magazine · Q2 2024</p></div>{[["Type", "Magazine Cover"], ["Version", "v3"], ["Requested by", "Emma Davis"], ["Approver", "Sarah Johnson"], ["Due date", "May 15, 2024"], ["Priority", "High"]].map(([a,b]) => <div className={styles.detail} key={a}><span>{a}</span><b>{b}</b></div>)}<Panel title="Version Preview"><div className={styles.grid2}><div className={styles.cover}><Image src={cover} alt="v2" width={130} height={170} /></div><div className={styles.cover}><Image src={cover} alt="v3" width={130} height={170} /></div></div></Panel><Button label="Review & Take Action" href="/client/approvals" primary /></aside></div>
  </main>;
}

const assets = [
  ["Arjun_Mehta_Headshot.jpg", people.arjun, "Image", "Approved"], ["Executive Insights Q2 Cover.jpg", cover, "Magazine Cover", "Approved"],
  ["NDA_NextPay_Technologies.pdf", "/images/articles/global-leadership.png", "Document", "Approved"], ["Interview_Arjun_Mehta.mp4", videoHero, "Video", "In Review"],
  ["NextPay_Logo_Primary.png", "/images/articles/arjun-mehta.png", "Brand Asset", "Approved"], ["Executive_Insights_Layout_03.indd", cover, "Layout", "Changes Requested"],
  ["Podcast_Ep12_Master.wav", podcastHero, "Audio", "Approved"], ["Summit_SanFrancisco_Venue.jpg", eventHero, "Photo", "Approved"],
  ["Event_Budget_2024.xlsx", "/images/articles/computing-infrastructure.png", "Document", "Approved"], ["B_Roll_Mountains_01.mp4", "/images/articles/global-growth.png", "Video", "Internal Only"],
  ["Visionary_Leader_Ep12_Cover.jpg", podcastHero, "Podcast Cover", "Approved"], ["Service_Agreement_NextPay.pdf", "/images/articles/global-leadership.png", "Contract", "Approved"],
];

export function AssetLibraryScreen() {
  return <main className={styles.page}><Header eyebrow="FILES & ASSETS" title="Asset & File Library" subtitle="Organize, manage, version and share every file and asset in one secure place." actions={[{ label: "Duplicate Scan", href: "#duplicates" }, { label: "Missing Assets", href: "#missing" }, { label: "Upload", href: "#upload" }]} />
    <div className={styles.metricGrid}>{[["Total Assets", "8,742", FolderOpen], ["Images", "3,120", ImageIcon], ["Documents", "2,186", FileText], ["Videos", "1,458", Video], ["Audio", "842", Headphones], ["Storage Used", "1.42 TB / 5 TB", Gauge]].map(([label, value, Icon]) => <div className={styles.metric} key={String(label)}><span>{typeof Icon !== "string" && <Icon size={19} />}</span><div><small>{String(label)}</small><strong>{String(value)}</strong></div></div>)}</div>
    <Tabs items={["All Assets", "Recent", "Favorites", "My Uploads", "Shared with Client", "Internal Only", "Trash"]} />
    <div className={styles.filters}><label><Search size={15} /><input placeholder="Search assets..." /></label>{["All Clients", "All Projects", "All Types", "All Statuses", "All Visibility", "Any Time"].map((x) => <label key={x}><select aria-label={x}><option>{x}</option></select></label>)}</div>
    <div className={styles.assetLayout}><Panel title="Folders & Collections" className={styles.folderNav}>{["All Assets", "Favorites", "Uncategorized", "01. Clients", "02. Projects", "Editorial", "Magazine", "Podcast", "Video", "Events", "03. Brand Assets", "04. Templates", "05. Legal & Finance", "Archive", "Trash"].map((x, i) => <button type="button" key={x}><span>{x}</span><b>{[8742,128,56,2341,4892,1245,1102,864,942,739,532,412,287,275,86][i]}</b></button>)}</Panel>
      <section className={styles.assetGrid}>{assets.map(([name, src, type, status]) => <article className={styles.assetCard} key={name}><div className={styles.filePreview}><Image src={src} alt="" width={240} height={140} /></div><Status tone={status === "Approved" ? "green" : status === "In Review" ? "blue" : status === "Internal Only" ? "purple" : "orange"}>{type}</Status><b>{name}</b><small>Client: NextPay Technologies</small><small>Project: Executive Insights</small><footer><Status tone={status === "Approved" ? "green" : status === "In Review" ? "blue" : status === "Internal Only" ? "purple" : "orange"}>{status}</Status><MoreHorizontal size={15} /></footer></article>)}</section>
      <aside className={styles.drawer}><header><Status tone="green">Image</Status><MoreHorizontal size={18} /></header><div className={styles.cover}><Image src={cover} alt="Executive Insights Q2 cover" width={260} height={340} /></div><div><h2>Executive Insights Q2 Cover.jpg</h2><p>Approved · Magazine Cover · v4</p></div>{[["Client", "NextPay Technologies"], ["Project", "Executive Insights"], ["Uploaded by", "Emma Davis"], ["Size", "6.8 MB"], ["Visibility", "CLIENT_VISIBLE"], ["Usage Rights", "Licensed"]].map(([a,b]) => <div className={styles.detail} key={a}><span>{a}</span><b>{b}</b></div>)}<Tabs items={["Preview", "Metadata", "Versions 4", "Approval", "Comments 3", "Activity"]} /><Actions items={[{ label: "Download", href: "#download", icon: Download }, { label: "Share", href: "#share", icon: Send }, { label: "Replace File", href: "#replace", icon: Upload }, { label: "Request Update", href: "/app/approvals", icon: BellRing }]} /><Panel title="Version History"><Rows entries={[{ title: "v4 · Current", meta: "May 11 · Emma Davis" }, { title: "v3", meta: "May 9 · David Wilson" }, { title: "v2", meta: "May 6 · Emma Davis" }]} /></Panel><Button label="Open in New Tab" href={cover} primary /></aside></div>
    <Panel title="Selected Asset Actions"><Actions items={[{ label: "Share", href: "#share", icon: Send }, { label: "Download", href: "#download", icon: Download }, { label: "Move", href: "#move", icon: FolderOpen }, { label: "Tag", href: "#tag", icon: Sparkles }, { label: "Make Internal", href: "#internal", icon: ShieldCheck }, { label: "Archive", href: "#archive", icon: FileCheck2 }]} /></Panel>
  </main>;
}
