import Image from "next/image";
import Link from "next/link";
import {
  Activity, AlertTriangle, ArrowDownRight, ArrowRight, ArrowUpRight,
  BadgeCheck, BarChart3, BriefcaseBusiness, CalendarDays, Check, CheckCircle2,
  CircleDollarSign, CircleGauge, Clock3, CloudUpload, ContactRound, CreditCard,
  Database, Download, FileSearch, FileText, Filter, FolderKanban,
  Gauge, Globe2, HandCoins, Landmark, ListChecks, Mail, Merge,
  MessageSquare, Pause, Phone, Plus, ReceiptText, RefreshCw, Search,
  ShieldCheck, Upload, UserPlus, Users, WalletCards,
  XCircle,
} from "lucide-react";
import styles from "./workspace.module.css";

type IconType = React.ComponentType<{ size?: number }>;
type Metric = { label: string; value: string; trend?: string; direction?: "up" | "down"; icon: IconType; tone?: string; note?: string };

const people = [
  "/images/articles/arjun-mehta.png",
  "/images/articles/elena-rossi.png",
  "/images/articles/daniel-kim.png",
  "/images/articles/marcus-chen.png",
];

function ScreenHeader({ title, subtitle, children }: { title: string; subtitle: string; children?: React.ReactNode }) {
  return <div className={styles.opsHeader}><div><h1>{title}</h1><p>{subtitle}</p></div><div className={styles.opsHeaderActions}>{children}</div></div>;
}

function Button({ children, primary = false }: { children: React.ReactNode; primary?: boolean }) {
  return <button className={primary ? styles.opsPrimaryButton : styles.opsButton} type="button">{children}</button>;
}

function MetricCard({ metric }: { metric: Metric }) {
  const Icon = metric.icon;
  const down = metric.direction === "down";
  return <article className={styles.opsMetric}><span className={`${styles.opsMetricIcon} ${styles[metric.tone || "blueTone"]}`}><Icon size={20} /></span><div><small>{metric.label}</small><strong>{metric.value}</strong>{metric.trend && <em className={down ? styles.down : styles.up}>{down ? <ArrowDownRight size={12} /> : <ArrowUpRight size={12} />}{metric.trend}</em>}<p>{metric.note || "vs. previous 7 days"}</p></div></article>;
}

function Box({ title, action, children, className = "" }: { title: string; action?: string; children: React.ReactNode; className?: string }) {
  return <section className={`${styles.opsBox} ${className}`}><header><h2>{title}</h2>{action && <button type="button">{action}<ArrowRight size={12} /></button>}</header>{children}</section>;
}

function DateActions() {
  return <><Button><CalendarDays size={15} /> May 12 – May 18, 2026</Button><Button><Filter size={15} /> Filters</Button><Button><CircleGauge size={15} /> Customize</Button></>;
}

function MiniDonut({ value, label, kind = "health" }: { value: string; label: string; kind?: "health" | "types" | "finance" | "quality" }) {
  const legend = kind === "types" ? [["Magazine","34"],["Articles / Blogs","28"],["Podcast","18"],["Video","16"],["Events","14"]] : kind === "finance" ? [["Personal magazines","43%"],["Subscriptions","23%"],["Podcast","15%"],["Video","11%"],["Events","8%"]] : kind === "quality" ? [["Excellent","86"],["Good","102"],["Fair","46"],["Poor","16"]] : [["On track","82"],["At risk","18"],["Blocked","9"],["Completed","19"]];
  return <div className={styles.opsDonutWrap}><div className={`${styles.opsDonut} ${styles[`opsDonut${kind}`]}`}><span><b>{value}</b><small>{label}</small></span></div><div className={styles.opsLegend}>{legend.map((x,i)=><div key={x[0]}><i data-i={i}/><span>{x[0]}</span><b>{x[1]}</b></div>)}</div></div>;
}

function OpsBarChart() {
  const bars = [24,22,28,20,16,8,10];
  return <div className={styles.opsBarChart}>{bars.map((v,i)=><div key={i}><span><i style={{height:`${v*3}px`}} /></span><b>{v}</b><small>{["Intake","Planning","In progress","Review","Client review","Approvals","Publishing"][i]}</small></div>)}</div>;
}

function RowList({ rows, variant = "plain" }: { rows: string[][]; variant?: "plain" | "dates" | "activity" }) {
  return <div className={`${styles.opsRows} ${styles[`opsRows${variant}`]}`}>{rows.map((r,i)=><div key={`${r[0]}-${i}`}>{variant === "dates" && <span className={styles.opsDate}><small>May</small><b>{r[0]}</b></span>}{variant === "activity" && <span className={`${styles.opsRowIcon} ${styles[`queueTone${i%5}`]}`}>{i%3===0?<FolderKanban size={15}/>:i%3===1?<CheckCircle2 size={15}/>:<AlertTriangle size={15}/>}</span>}<p><b>{r[variant === "dates" ? 1 : 0]}</b><small>{r[variant === "dates" ? 2 : 1]}</small></p>{r.slice(variant === "dates" ? 3 : 2).map((x,j)=><em key={j}>{x}</em>)}</div>)}</div>;
}

const operationsMetrics: Metric[] = [
  {label:"Active projects",value:"128",trend:"12.6%",icon:FolderKanban},
  {label:"Projects on track",value:"82",trend:"64.1%",icon:CheckCircle2,tone:"greenTone"},
  {label:"At-risk projects",value:"18",trend:"14.1%",direction:"down",icon:AlertTriangle,tone:"orangeTone"},
  {label:"Blocked projects",value:"9",trend:"7.0%",direction:"down",icon:XCircle,tone:"redTone"},
  {label:"Overdue tasks",value:"36",trend:"8.3%",direction:"down",icon:Clock3,tone:"redTone"},
  {label:"Pending approvals",value:"24",trend:"9.1%",icon:Users,tone:"purpleTone"},
  {label:"SLA breaches",value:"5",trend:"2",direction:"down",icon:Gauge,tone:"orangeTone"},
  {label:"On-time delivery",value:"89.2%",trend:"6.7%",icon:BadgeCheck,tone:"greenTone"},
];

export function OperationsDashboard() {
  return <div className={styles.opsPage}><ScreenHeader title="Operations Dashboard" subtitle="End-to-end overview of projects, resources, risks and delivery health."><DateActions /></ScreenHeader>
    <div className={styles.opsMetricGrid}>{operationsMetrics.map(m=><MetricCard metric={m} key={m.label}/>)}</div>
    <div className={styles.opsTopGrid}><Box title="Project Health Overview" action="View all projects"><MiniDonut value="128" label="Total projects"/></Box><Box title="Projects by Stage" action="View stage report"><OpsBarChart/></Box><Box title="Projects by Type" action="View type report"><MiniDonut value="128" label="Total projects" kind="types"/></Box><Box title="Operational Reminders" action="View all"><RowList variant="activity" rows={[["7 projects have missing updates","Update required","10m"],["4 tasks are past due","Immediate attention","25m"],["3 client actions pending","Waiting for client","40m"],["2 approvals blocked","Action needed","1h"],["SLA breach in 5 projects","Review required","2h"]]}/></Box></div>
    <div className={styles.opsFourGrid}><Box title="Overdue Milestones" action="View all"><RowList rows={[["Personal Magazine — May 2026","Client review","8 days"],["Podcast Ep. 23","Recording","7 days"],["Brand Film — Corporate Story","Final delivery","6 days"],["Leadership Summit 2026","Content approval","5 days"]]}/></Box><Box title="Blocked Projects" action="View all"><RowList rows={[["Magazine Archive Issue","Client content missing","Emma"],["Podcast Ep. 24","Guest confirmation","James"],["Video Series Ep. 3","Script approval","Priya"],["Investor Meet","Venue confirmation","Rohit"]]}/></Box><Box title="Pending Client Actions" action="View all"><RowList rows={[["Personal Magazine — May 2026","Approve draft","May 14"],["Brand Film — Corporate Story","Provide feedback","May 14"],["Podcast Ep. 23","Approve artwork","May 15"],["Q2 Magazine Issue","Verify content","May 15"]]}/></Box><Box title="Pending Internal Actions" action="View all"><RowList rows={[["Assign proofreader","Magazine issue","May 20"],["Upload final assets","Brand film","May 20"],["Send approval request","Podcast Ep. 23","May 21"],["Prepare publish checklist","Q2 Magazine","May 21"]]}/></Box></div>
    <div className={styles.opsBottomGrid}><Box title="Team Workload Overview" action="View workload report"><WorkloadTable/></Box><Box title="Upcoming Deadlines" action="View calendar"><RowList variant="dates" rows={[["20","Article Series — Future of Work","Editorial review","2 days","High"],["21","Personal Magazine — May 2026","Client approval","3 days","High"],["22","Podcast Ep. 23","Publish","4 days","Medium"],["23","Brand Film — Corporate Story","Final delivery","5 days","High"]]}/></Box><Box title="Recent Operational Activity" action="View all"><RowList variant="activity" rows={[["Project moved to Client Review","AI in Business","10m"],["Task completed","Approve podcast artwork","25m"],["New approval request","Brand Film","40m"],["Milestone completed","Podcast recording","1h"],["Risk status updated","2 projects","2h"]]}/></Box><Box title="Quick Actions"><QuickActionGrid mode="operations"/></Box></div>
  </div>;
}

function WorkloadTable(){return <div className={styles.opsWorkload}>{[["Editorial",32,156,78],["Design",18,112,92],["Video",14,86,72],["Podcast",10,64,68],["Events",8,48,60],["Distribution",12,72,66]].map((x,i)=><div key={x[0]}><span className={`${styles.opsTinyIcon} ${styles[`queueTone${i%5}`]}`}><Users size={13}/></span><b>{x[0]}</b><small>{x[1]} projects</small><small>{x[2]} tasks</small><i><em style={{width:`${x[3]}%`}}/></i><strong>{x[3]}%</strong></div>)}</div>}

function QuickActionGrid({mode}:{mode:"operations"|"finance"}){const data=mode==="finance"?[["Create invoice",ReceiptText],["Record payment",HandCoins],["Issue credit",FileText],["Client billing",CreditCard],["Download report",Download],["Export transactions",Upload],["Tax report",Landmark],["Balance sheet",BarChart3]]:[["Create project",FolderKanban],["Add task",ListChecks],["Schedule meeting",CalendarDays],["Assign owner",UserPlus],["Escalate blocker",AlertTriangle],["Request approval",ShieldCheck],["Upload file",CloudUpload],["View workload",Users]];return <div className={styles.opsQuickGrid}>{data.map(([n,I],i)=>{const Icon=I as IconType;return <button type="button" key={n as string}><span className={styles[`queueTone${i%5}`]}><Icon size={18}/></span>{n as string}</button>})}</div>}

const financeMetrics: Metric[]=[
  {label:"Total revenue",value:"$1.82M",trend:"18.6%",icon:CircleDollarSign,tone:"greenTone"},
  {label:"Collected revenue",value:"$1.27M",trend:"16.4%",icon:TrendingIcon,tone:"greenTone"},
  {label:"Outstanding invoices",value:"$432K",trend:"12.9%",icon:ReceiptText},
  {label:"Overdue invoices",value:"$148K",trend:"8.7%",direction:"down",icon:FileText,tone:"redTone"},
  {label:"Payments received",value:"$1.21M",trend:"17.8%",icon:Users,tone:"purpleTone"},
  {label:"Upcoming receivables",value:"$583K",icon:WalletCards,tone:"orangeTone",note:"Next 30 days"},
  {label:"Refunds / credits",value:"$24.6K",trend:"4.6%",direction:"down",icon:ShieldCheck,tone:"orangeTone"},
  {label:"Average deal size",value:"$33,097",trend:"6.2%",icon:BriefcaseBusiness},
];
function TrendingIcon({size=20}:{size?:number}){return <BarChart3 size={size}/>}

export function FinanceDashboard(){return <div className={styles.opsPage}><ScreenHeader title="Finance Dashboard" subtitle="Real-time overview of financial performance, cash flow and collections."><DateActions/></ScreenHeader><div className={styles.opsMetricGrid}>{financeMetrics.map(m=><MetricCard metric={m} key={m.label}/>)}</div><div className={styles.financeTop}><Box title="Revenue Trend" action="This month"><FinanceChart/></Box><Box title="Revenue by Product / Service" action="This month"><MiniDonut value="$1.82M" label="Total revenue" kind="finance"/></Box><Box title="Revenue by Client" action="Top 6"><RankBars names={["Acme Corporation","BluePeak Partners","Globex Industries","InnovateX Solutions","Greenfield Ltd.","Future Labs"]}/></Box><Box title="Revenue by Salesperson" action="This month"><RankBars people names={["Sarah Miller","John Smith","Alex Johnson","Priya Patel","James Wilson","Mark Davis"]}/></Box></div><div className={styles.financeTables}>{[["Recent Invoices",["INV-2026-1087|Acme Corporation|$48,500|Paid","INV-2026-1086|BluePeak Partners|$32,000|Partial","INV-2026-1085|Globex Industries|$28,750|Sent","INV-2026-1084|InnovateX Solutions|$22,000|Paid"]],["Recent Payments",["REC-2026-559|Acme Corporation|$48,500|Bank transfer","REC-2026-558|BluePeak Partners|$16,000|Credit card","REC-2026-557|Globex Industries|$28,750|Bank transfer","REC-2026-556|InnovateX Solutions|$22,000|UPI"]],["Overdue Invoices",["INV-2026-1041|Vertix Systems|22 days|$12,600","INV-2026-1048|Horizon Enterprises|18 days|$8,750","INV-2026-1055|NextGen Labs|15 days|$6,500","INV-2026-1059|BrightWave Media|9 days|$4,250"]],["Upcoming Billing",["Acme Corporation|INV-2026-1088|$52,000|May 25","BluePeak Partners|INV-2026-1089|$32,000|May 27","Future Labs|INV-2026-1090|$16,750|May 28","InnovateX Solutions|INV-2026-1091|$24,200|May 29"]]].map(x=><Box title={x[0] as string} action="View all" key={x[0] as string}><FinanceTable rows={x[1] as string[]}/></Box>)}</div><div className={styles.financeBottom}><Box title="Cash Flow Overview" action="This month"><CashFlow/></Box><Box title="Revenue vs Collection" action="This month"><CollectionHealth/></Box><Box title="Financial Health"><HealthRows/></Box><Box title="Quick Actions"><QuickActionGrid mode="finance"/></Box></div></div>}

function FinanceChart(){const h=[30,42,48,51,57,52,63,68,62,74,81,92];return <div className={styles.financeChart}><div>{h.map((v,i)=><i key={i} style={{height:`${v}%`}}><b/></i>)}</div><footer><span>May 1</span><span>May 7</span><span>May 13</span><span>May 19</span></footer></div>}
function RankBars({names,people:showPeople=false}:{names:string[];people?:boolean}){return <div className={styles.rankBars}>{names.map((n,i)=><div key={n}>{showPeople&&<Image alt="" src={people[i%4]} width={24} height={24}/>}<span>{n}</span><i><em style={{width:`${95-i*10}%`}}/></i><b>{["$286K","$192K","$148K","$126K","$98K","$86K"][i]}</b></div>)}</div>}
function FinanceTable({rows}:{rows:string[]}){return <div className={styles.financeMiniTable}>{rows.map((r,i)=><div key={r}><Link href="/app/finance">{r.split("|")[0]}</Link>{r.split("|").slice(1).map((x,j)=><span key={j}>{x}</span>)}<em className={i===1?styles.warningPill:styles.successPill}>{r.split("|").at(-1)}</em></div>)}</div>}
function CashFlow(){return <div className={styles.cashFlow}><div>{[["Opening balance","$325K"],["Cash inflow","$1.26M"],["Cash outflow","$892K"],["Closing balance","$698K"]].map(x=><p key={x[0]}><small>{x[0]}</small><b>{x[1]}</b></p>)}</div><section>{[28,84,66,48].map((x,i)=><i key={i} style={{height:`${x}%`}}><span>{["Opening","Revenue","Expenses","Closing"][i]}</span></i>)}</section></div>}
function CollectionHealth(){return <div className={styles.collectionHealth}><div><p>Revenue<strong>$1.82M</strong></p><p>Collected<strong>$1.27M</strong></p></div><label>Collection rate <b>69.8%</b></label><i><em/></i><small>Target: 75%</small><p>Uncollected revenue <strong>$546K</strong></p></div>}
function HealthRows(){return <div className={styles.healthRows}>{[["Outstanding invoices ratio","23.7%","Medium"],["Overdue invoices ratio","8.1%","High"],["Collection rate","69.8%","Medium"],["Payment success rate","97.6%","Good"],["Average days to collect","28 days","Good"],["Monthly recurring revenue","$312K","Good"]].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><em>{x[2]}</em></div>)}</div>}

const finderRows=[
  ["Michael Chen","CEO & Co-Founder","NovaAI","LinkedIn","92","San Francisco, USA"],
  ["Sarah Johnson","President","HealthLytics","Company Website","88","New York, USA"],
  ["Arjun Mehta","Founder & CEO","NextPay","Crunchbase","85","Austin, USA"],
  ["David Wilson","VP of Strategy","Globex Corp","Press & News","82","Chicago, USA"],
  ["Emily Park","Co-Founder","FutureLabs AI","Events & Conf.","79","Boston, USA"],
  ["James Anderson","Director of Innovation","BluePeak Partners","LinkedIn","76","Seattle, USA"],
  ["Lisa Rodriguez","CEO","QuantumX","Podcast Guests","75","Miami, USA"],
];

export function LeadFinder(){return <div className={styles.opsPage}><ScreenHeader title="Lead Finder" subtitle="Discover high-value prospects from trusted sources and build your pipeline."><Button><FileSearch size={15}/> Saved searches</Button><Button>Save search</Button><Button primary><Search size={15}/> Search</Button></ScreenHeader><SearchBuilder/><div className={styles.finderLayout}><aside className={styles.refinePanel}><header>Refine results <button>Clear all</button></header><label>Fit score<input type="range" defaultValue="78"/><span>70 – 100</span></label>{[["Contact availability",["Has Email","Has Phone","Has LinkedIn","Has Social Profile"]],["Fit for business",["Personal Magazine","Podcast Guest","Article / Blog","Video / Interview","Event Speaker","Partnership"]]].map(g=><fieldset key={g[0] as string}><legend>{g[0] as string}</legend>{(g[1] as string[]).map((x,i)=><label key={x}><input type="checkbox" defaultChecked={i===0}/>{x}<small>{(8642-i*731).toLocaleString()}</small></label>)}</fieldset>)}<label>Exclude keywords<input placeholder="student, intern, job seeker"/></label></aside><section className={styles.leadResults}><header><div><h2>12,842 Leads Found</h2><p>Showing 1–25 of 12,842 results</p></div><Button>Bulk actions</Button><Button>Add to list</Button><Button primary><Download size={15}/> Export</Button></header><LeadTable rows={finderRows}/></section></div><Workflow steps={[["Search & discover","Find ideal prospects"],["Select leads","Choose high-fit leads"],["Extract data","Pull raw data from sources"],["Enrich contacts","Add emails, phones, social"],["Add to leads","Send to Lead CRM"],["Assign & outreach","Reach out"]]}/></div>}

function SearchBuilder(){const fields=[["Search keywords","Name, company, title, industry..."],["Target persona","CEO, Founder, President, VP"],["Lead sources","6 sources selected"],["Geography","United States"],["Industry","Technology, Media, Fintech"],["Company size","51 – 1,000 employees"],["Seniority level","C-Level, VP, Director"],["Funding / revenue","$1M+ Revenue"],["Best for","Personal Magazine, Podcast, Article"]];return <section className={styles.searchBuilder}><div>{fields.map(x=><label key={x[0]}>{x[0]}<span>{x[0]==="Search keywords"&&<Search size={14}/>}<input placeholder={x[1]}/></span></label>)}</div><footer>{[[ContactRound,"LinkedIn","12.4K"],[Database,"Crunchbase","8.7K"],[Globe2,"Company Website","6.2K"],[FileText,"Press & News","9.1K"],[CalendarDays,"Events & Conferences","3.8K"]].map(([I,n,c])=>{const Icon=I as IconType;return <button key={n as string}><Icon size={17}/><span><b>{n as string}</b><small>{c as string}</small></span><Check size={13}/></button>})}</footer></section>}
function LeadTable({rows}:{rows:string[][]}){return <div className={styles.leadTable}><div className={styles.leadHead}><span/><span>Lead / Company</span><span>Title</span><span>Company</span><span>Source</span><span>Fit</span><span>Contact</span><span>Best for</span><span>Location</span></div>{rows.map((r,i)=><div key={r[0]}><input type="checkbox" defaultChecked={i<2}/><span className={styles.personCell}><Image alt="" src={people[i%4]} width={34} height={34}/><b>{r[0]}</b><small>{r[0].toLowerCase().replace(" ",".")}@example.com</small></span><span>{r[1]}</span><b>{r[2]}</b><span>{r[3]}<small>{i+1} days ago</small></span><span className={styles.scoreCircle}>{r[4]}<small>{Number(r[4])>84?"Excellent":"Good"}</small></span><span className={styles.contactIcons}><Mail size={13}/><Phone size={13}/><ContactRound size={13}/></span><span className={styles.bestFor}><FileText size={13}/><MessageSquare size={13}/><Activity size={13}/></span><span>{r[5]}</span></div>)}<footer>Showing 1 to 25 of 12,842 results <span>‹ <b>1</b> 2 3 4 5 … 514 ›</span></footer></div>}

type PipelineMode="extraction"|"enrichment";
export function DataExtraction(){return <DataPipeline mode="extraction"/>}
export function DataEnrichment(){return <DataPipeline mode="enrichment"/>}

function DataPipeline({mode}:{mode:PipelineMode}){const enrich=mode==="enrichment";return <div className={styles.opsPage}><ScreenHeader title={enrich?"Contact / Data Enrichment":"Data Extraction"} subtitle={enrich?"Enrich and verify contact details to build accurate and actionable lead profiles.":"Extract, normalize and validate raw data from multiple trusted sources."}><Button>Job actions</Button><Button><Pause size={14}/> Pause job</Button><Button><RefreshCw size={14}/> Retry failed</Button><Button primary>{enrich?"Send Approved to Leads":"Send to Enrichment"}<ArrowRight size={15}/></Button></ScreenHeader><div className={styles.jobSummaryGrid}><JobSummary mode={mode}/><Box title={enrich?"Enrichment Progress":"Extraction Progress"}><ProgressRing value={enrich?64:68}/></Box><Box title={enrich?"Contact Discovery":"Record Status"}>{enrich?<DiscoveryCards/>:<StatusCards/>}</Box><Box title="Data Quality Overview"><MiniDonut value={enrich?"86":"82"} label="Good" kind="quality"/></Box>{enrich&&<Box title="Enrichment Usage"><Usage/></Box>}</div><div className={styles.jobAlerts}><span><AlertTriangle size={14}/>{enrich?"10 records need email verification":"32 records have missing critical fields"}<button>Review now</button></span><span><AlertTriangle size={14}/>{enrich?"8 potential duplicates found":"10 potential duplicates found"}<button>Review duplicates</button></span><span><AlertTriangle size={14}/>{enrich?"6 records have invalid phones":"10 records failed to extract"}<button>View details</button></span><small>Last updated: May 13, 2026 10:02 AM</small></div><div className={styles.pipelineTabs}>{(enrich?["All Records (250)","Enriched (160)","Partially Enriched (40)","Verification Needed (20)","Failed (10)","Duplicates (8)","History"]:["Extracted Records (250)","Duplicates (10)","Failed Records (10)","Extraction History","Field Mapping"]).map((x,i)=><button className={i===0?styles.activeTab:""} key={x}>{x}</button>)}</div><div className={styles.pipelineBody}><section className={styles.recordsPanel}><RecordFilters enrich={enrich}/><BulkBar enrich={enrich}/><RecordsTable enrich={enrich}/></section><RecordDrawer enrich={enrich}/></div><Workflow steps={enrich?[["Extracted data","Raw data from sources"],["Enrich contacts","Find missing info"],["Verify information","Validate emails, phones"],["Deduplicate","Merge duplicates"],["Review & approve","Approve quality records"],["Send to leads","Move to CRM"]]:[["Select leads","From Lead Finder"],["Create extraction job","Configure sources"],["Extract raw data","Pull public data"],["Validate & deduplicate","Clean records"],["Review & approve","Approve records"],["Send to enrichment","Next stage"]]}/></div>}

function JobSummary({mode}:{mode:PipelineMode}){const enrich=mode==="enrichment";return <Box title={enrich?"Enrichment Job Summary":"Job Summary"}><div className={styles.jobFacts}><h3>{enrich?"ENR-2026-078":"EXT-2026-045"}<em>Running</em></h3><p><span>Source</span><b>{enrich?"Extraction Job EXT-2026-045":"LinkedIn Executives — May 13"}</b></p><p><span>Created by</span><b>John Smith</b></p><p><span>Created on</span><b>May 13, 2026 · 9:41 AM</b></p><p><span>Total records</span><b>250</b></p><p><span>Assigned to</span><b>Research Team</b></p><Link href="#records">View job details <ArrowRight size={12}/></Link></div></Box>}
function ProgressRing({value}:{value:number}){return <div className={styles.progressRingWrap}><div className={styles.progressRing} style={{background:`conic-gradient(#2bb673 0 ${value}%, #315fe8 ${value}% ${value+18}%, #f7a42a ${value+18}% ${value+25}%, #ef4f5e ${value+25}% 100%)`}}><span><b>{value}%</b><small>Complete</small></span></div><div><p><i/>Completed <b>{value===64?160:170}</b></p><p><i/>Processing <b>{value===64?60:52}</b></p><p><i/>Pending <b>20</b></p><p><i/>Failed <b>10</b></p></div></div>}
function StatusCards(){return <div className={styles.statusCards}>{[["170","Completed",CheckCircle2],["52","Processing",RefreshCw],["18","Queued",Clock3],["10","Failed",XCircle]].map(([a,b,I],i)=>{const Icon=I as IconType;return <div key={a as string} className={styles[`queueTone${i}`]}><Icon size={18}/><b>{a as string}</b><small>{b as string}</small></div>})}</div>}
function DiscoveryCards(){return <div className={styles.statusCards}>{[["162","Emails found",Mail],["128","Phones found",Phone],["198","LinkedIn found",ContactRound],["172","Verified domains",ShieldCheck]].map(([a,b,I],i)=>{const Icon=I as IconType;return <div key={a as string} className={styles[`queueTone${i}`]}><Icon size={18}/><b>{a as string}</b><small>{b as string}</small></div>})}</div>}
function Usage(){return <div className={styles.usage}>{[["1,250","Credits used"],["8,750","Credits remaining"],["10,000","Total credits"]].map((x,i)=><p key={x[1]}><span className={styles[`queueTone${i}`]}><Database size={14}/></span><small>{x[1]}</small><b>{x[0]}</b></p>)}</div>}
function RecordFilters({enrich}:{enrich:boolean}){return <div className={styles.recordFilters}><label><Search size={14}/><input placeholder="Search by name, company, email..."/></label>{["All status","All scores",enrich?"All email status":"All quality","All sources","All owners"].map(x=><button key={x}>{x}<ArrowDownRight size={12}/></button>)}<button><Filter size={13}/> Filters</button></div>}
function BulkBar({enrich}:{enrich:boolean}){return <div className={styles.bulkBar}><span><input type="checkbox" defaultChecked/> 5 selected</span><Button><Check size={13}/> Approve selected</Button><Button><XCircle size={13}/> Reject selected</Button>{enrich&&<Button><Mail size={13}/> Verify emails</Button>}<Button><Merge size={13}/> Merge duplicates</Button><Button><UserPlus size={13}/> Assign owner</Button><Button><Plus size={13}/> Add to list</Button></div>}
function RecordsTable({enrich}:{enrich:boolean}){return <div className={`${styles.recordsTable} ${enrich?styles.enrichTable:""}`}><div className={styles.recordHead}><span/><span>Name / Title</span><span>Company</span>{enrich&&<span>Email</span>}<span>{enrich?"Phone":"Source"}</span><span>{enrich?"Enrichment":"Quality"}</span><span>Fit</span><span>Status</span></div>{finderRows.map((r,i)=><div key={r[0]}><input type="checkbox" defaultChecked={i<3}/><span className={styles.personCell}><Image alt="" src={people[i%4]} width={31} height={31}/><b>{r[0]}</b><small>{r[1]}</small></span><b>{r[2]}</b>{enrich&&<span>{r[0].toLowerCase().replace(" ",".")}@{r[2].toLowerCase().replace(" ","")}.com<small className={i===2?styles.warningText:styles.verifiedText}>{i===2?"Catch-all":"Verified"}</small></span>}<span>{enrich?`+1 (415) 555-01${20+i}`:r[3]}<small>{enrich?(i===6?"Invalid":"Verified"):"May 12, 2026"}</small></span><span className={styles.tableScore}>{92-i*3}</span><span className={styles.tableScore}>{r[4]}</span><em className={i===6?styles.errorPill:i>3?styles.warningPill:styles.successPill}>{i===6?"Failed":i>3?"Review needed":enrich?"Enriched":"Completed"}</em></div>)}<footer>Showing 1 to 25 of 250 results <span>‹ <b>1</b> 2 3 4 5 … 10 ›</span></footer></div>}
function RecordDrawer({enrich}:{enrich:boolean}){return <aside className={styles.recordDrawer}><header>Record Details <button>×</button></header><div className={styles.drawerProfile}><Image alt="Michael Chen" src={people[0]} width={50} height={50}/><h3>Michael Chen <ContactRound size={14}/></h3><p>CEO & Co-Founder at NovaAI</p><small>San Francisco, CA, USA</small></div><nav><button>Overview</button><button>{enrich?"Enrichment":"Extracted"}</button><button>Activity</button></nav><h4>{enrich?"Verified Contact":"Data Quality Score"}</h4>{enrich&&<><p className={styles.detailLine}><span>Email</span><b>michael.chen@novaai.com</b></p><p className={styles.detailLine}><span>Phone</span><b>+1 (415) 555-0123</b></p></>}<h4>Company Information</h4>{[["Company","NovaAI"],["Website","https://novaai.com"],["Industry","Artificial Intelligence"],["Company size","51 – 200 employees"],["HQ location","San Francisco, CA"]].map(x=><p className={styles.detailLine} key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></p>)}<h4>{enrich?"Enrichment Details":"Source & Provenance"}</h4>{[[enrich?"Enrichment score":"Source type",enrich?"92 / 100":"LinkedIn Profile"],["Verified on","May 13, 2026"],["Confidence","High"]].map(x=><p className={styles.detailLine} key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></p>)}<Button>View Full Profile</Button></aside>}
function Workflow({steps}:{steps:string[][]}){return <section className={styles.opsWorkflow}>{steps.map((x,i)=><div key={x[0]}><span>{i+1}</span><p><b>{x[0]}</b><small>{x[1]}</small></p>{i<steps.length-1&&<ArrowRight size={18}/>}</div>)}</section>}
