import Image from "next/image";
import Link from "next/link";
import {
  Activity, AlertTriangle, ArrowDownRight, ArrowUpRight, BarChart3, BellRing,
  BookOpen, BriefcaseBusiness, CalendarDays, CheckCircle2, ChevronRight,
  CircleDollarSign, CircleHelp, ClipboardCheck, Clock3, CloudUpload, DollarSign, FileCheck2, FileText,
  Filter, FolderKanban, Gauge, Handshake, Headphones, ListChecks, Mail,
  MessageSquare, Mic2, PackageCheck, PenLine, Plus, ReceiptText, Rocket, Search, Send,
  Settings, Share2, ShieldCheck, Sparkles, Target, TrendingUp, Upload,
  UserPlus, Users, Video, WalletCards,
} from "lucide-react";
import styles from "./workspace.module.css";

type IconType = React.ComponentType<{ size?: number }>;
type Stat = { label: string; value: string; trend: string; up?: boolean; icon: IconType; tone?: string };

const portraits = [
  "/images/articles/arjun-mehta.png",
  "/images/articles/elena-rossi.png",
  "/images/articles/daniel-kim.png",
  "/images/articles/marcus-chen.png",
];

function PageTitle({ title, subtitle, actions }: { title: string; subtitle: string; actions?: React.ReactNode }) {
  return <div className={styles.pageTitle}><div><div className={styles.breadcrumb}><HomeCrumb /><ChevronRight size={13} /><span>Dashboard</span><ChevronRight size={13} /><b>{title.replace(" Dashboard", "")}</b></div><h1>{title}</h1><p>{subtitle}</p></div><div className={styles.pageActions}>{actions}</div></div>;
}

function HomeCrumb() { return <Link href="/app"><span className={styles.homeGlyph}>◆</span></Link>; }

function DateControls({ compare = false }: { compare?: boolean }) {
  return <><button className={styles.controlButton} type="button">May 12 – May 18, 2026 <CalendarDays size={16} /></button>{compare && <button className={styles.controlButton} type="button">Compare: previous 7 days <ChevronRight size={14} /></button>}<button className={styles.controlButton} type="button"><Filter size={16} /> Filters</button><button className={styles.controlButton} type="button"><Settings size={16} /> Customize</button></>;
}

function StatCard({ stat }: { stat: Stat }) {
  const Icon = stat.icon;
  return <article className={styles.statCard}><span className={`${styles.statIcon} ${styles[stat.tone || "blueTone"]}`}><Icon size={23} /></span><div><small>{stat.label}</small><strong>{stat.value}</strong><em className={stat.up === false ? styles.down : styles.up}>{stat.up === false ? <ArrowDownRight size={13} /> : <ArrowUpRight size={13} />}{stat.trend}</em><p>vs. previous 7 days</p></div></article>;
}

function Panel({ title, action, children, className = "" }: { title: string; action?: string; children: React.ReactNode; className?: string }) {
  return <section className={`${styles.panel} ${className}`}><header><h2>{title}</h2>{action && <button type="button">{action}<ChevronRight size={13} /></button>}</header>{children}</section>;
}

function CssLineChart({ sales = false }: { sales?: boolean }) {
  const heights = sales ? [24, 40, 32, 58, 48, 64, 54, 69, 62, 78, 71, 89] : [18, 29, 27, 42, 46, 40, 51, 56, 63, 70, 78, 91];
  return <div className={styles.lineChart}><div className={styles.axisLabels}><span>{sales ? "$4M" : "$250K"}</span><span>{sales ? "$3M" : "$200K"}</span><span>{sales ? "$2M" : "$150K"}</span><span>{sales ? "$1M" : "$100K"}</span><span>$0</span></div><div className={styles.plot}><div className={styles.gridLines} /><div className={styles.chartDots}>{heights.map((h, i) => <i key={i} style={{ bottom: `${h}%`, left: `${i * 9}%` }} />)}</div><div className={styles.chartBars}>{heights.map((h, i) => <span key={i} style={{ height: `${h}%` }} />)}</div><div className={styles.chartTooltip}><small>May 19, 2026</small><b>{sales ? "$3,240,850" : "$216,480"}</b></div></div><div className={styles.xLabels}><span>Mar 3</span><span>Mar 24</span><span>Apr 14</span><span>May 5</span><span>May 19</span></div></div>;
}

function Donut({ total, label, variant = "projects" }: { total: string; label: string; variant?: "projects" | "clients" | "content" | "leads" }) {
  return <div className={styles.donutBlock}><div className={`${styles.donut} ${styles[`${variant}Donut`]}`}><span><b>{total}</b><small>{label}</small></span></div><div className={styles.donutLegend}>{(variant === "clients" ? [["Healthy","72 (56%)"],["At risk","34 (27%)"],["Needs attention","18 (14%)"],["Inactive","4 (3%)"]] : variant === "content" ? [["Articles","48 (37%)"],["Blogs","26 (20%)"],["Magazines","18 (14%)"],["Podcasts","16 (12%)"],["Videos","12 (9%)"]] : variant === "leads" ? [["LinkedIn","76 (31%)"],["Website","58 (23%)"],["Referrals","42 (17%)"],["Events","28 (11%)"],["Outreach","22 (9%)"]] : [["Planning","12 (14%)"],["Research","18 (21%)"],["In production","33 (38%)"],["Review","15 (17%)"],["On hold","8 (10%)"]]).map(([a,b], i) => <div key={a}><i data-index={i} /><span>{a}</span><b>{b}</b></div>)}</div></div>;
}

function ActivityList({ editorial = false }: { editorial?: boolean }) {
  const data = editorial ? [
    ["Sarah Writer submitted draft", "The Future of AI in Business", "10m"],
    ["Mark Editor requested changes", "Sustainable Cities of Tomorrow", "35m"],
    ["Alex Writer uploaded a new asset", "Brand Film — Corporate Story", "1h"],
    ["Emma Johnson approved draft", "Leadership in the New Era", "2h"],
    ["Priya Writer updated questionnaire", "CEO Interview — Arjun Mehta", "3h"],
  ] : [
    ["New deal created", "Acme Corp — $240,000", "2m"],
    ["Contract signed", "Horizon Partners", "18m"],
    ["New project created", "Q2 Magazine Issue", "42m"],
    ["Invoice paid", "Brand Film — $28,500", "1h"],
    ["Client approved design", "Podcast Episode 23", "2h"],
    ["New message", "Sarah Miller — Acme Corp", "3h"],
  ];
  return <div className={styles.activityList}>{data.map((x, i) => <div key={x[0]}><span className={`${styles.activityIcon} ${styles[`activity${i % 5}`]}`}>{i % 3 === 0 ? <CircleDollarSign size={16} /> : i % 3 === 1 ? <FileText size={16} /> : <FolderKanban size={16} />}</span><p><b>{x[0]}</b><small>{x[1]}</small></p><em>{x[2]} ago</em></div>)}</div>;
}

function ProgressRows({ editorial = false }: { editorial?: boolean }) {
  const rows = editorial ? [["Planning",12],["In writing",22],["Internal review",18],["Client review",24],["Approvals",15],["Ready to publish",9],["Published",7]] : [["Editorial",71],["Magazine",58],["Podcast",67],["Video",63],["Events",50]];
  return <div className={editorial ? styles.workflowSteps : styles.progressRows}>{rows.map(([name, value], i) => <div key={name}><span className={styles[`flowTone${i % 6}`]}>{editorial ? <FileText size={17} /> : <i />}</span><p><b>{name}</b>{editorial && <small>{value} projects</small>}</p>{editorial ? i < rows.length - 1 && <ChevronRight size={15} /> : <><div><i style={{ width: `${value}%` }} /></div><em>{value}%</em></>}</div>)}</div>;
}

function QuickActions({ type = "executive" }: { type?: "executive" | "sales" | "editorial" }) {
  const actions = type === "sales" ? [["Find leads", Search],["Import leads", Upload],["Create campaign", Rocket],["Send email", Mail],["Add deal", WalletCards],["Schedule meeting", CalendarDays],["Create proposal", FileText],["Add task", ListChecks]] : type === "editorial" ? [["Create editorial project", Plus],["Assign writer", UserPlus],["Create questionnaire", ClipboardCheck],["Start draft", PenLine],["Request review", Clock3],["Upload asset", CloudUpload],["Request approval", ShieldCheck],["Add task", ListChecks],["Editorial calendar", CalendarDays],["Style guide", BookOpen],["Content templates", FileText],["AI assistant", Sparkles]] : [["New project", Plus],["Find leads", Search],["Create invoice", ReceiptText],["Schedule meeting", CalendarDays],["Upload files", Upload],["View reports", BarChart3]];
  return <div className={styles.quickGrid}>{actions.map(([label, Icon], i) => { const C = Icon as IconType; return <button key={label as string} type="button"><span className={styles[`quickTone${i % 6}`]}><C size={19} /></span>{label as string}</button>; })}</div>;
}

const executiveStats: Stat[] = [
  { label:"Total revenue", value:"$1,482,650", trend:"12.4%", icon:DollarSign, tone:"greenTone" },
  { label:"Active clients", value:"128", trend:"9.4%", icon:Users, tone:"purpleTone" },
  { label:"Active projects", value:"86", trend:"6.7%", icon:FolderKanban },
  { label:"Pipeline value", value:"$3,240,850", trend:"18.2%", icon:TrendingUp, tone:"orangeTone" },
  { label:"Outstanding invoices", value:"$320,450", trend:"7.2%", up:false, icon:ReceiptText, tone:"redTone" },
  { label:"Overdue payments", value:"$78,320", trend:"4.1%", up:false, icon:Clock3, tone:"orangeTone" },
  { label:"Open approvals", value:"24", trend:"14.3%", up:false, icon:ClipboardCheck, tone:"purpleTone" },
  { label:"At-risk projects", value:"8", trend:"33.3%", up:false, icon:AlertTriangle, tone:"redTone" },
];

export function ExecutiveDashboard() {
  return <div className={styles.dashboardPage}>
    <PageTitle title="Executive Dashboard" subtitle="Complete business overview across every department, project and client." actions={<DateControls />} />
    <div className={styles.statsGrid}>{executiveStats.map((s) => <StatCard key={s.label} stat={s} />)}</div>
    <div className={styles.execPrimary}><Panel title="Revenue & Growth" action="Last 12 weeks"><CssLineChart /></Panel><Panel title="Sales Pipeline" action="View all"><PipelineRows /></Panel><Panel title="Upcoming Meetings & Deadlines" action="View calendar"><MeetingRows /></Panel></div>
    <div className={styles.execSecondary}><Panel title="Client Health" action="View all clients"><Donut label="Total clients" total="128" variant="clients" /></Panel><Panel title="Projects by Stage" action="View all projects"><Donut label="Total" total="86" /></Panel><Panel title="Production Status" action="View all projects"><ProgressRows /></Panel><Panel title="Recent Activity" action="View all"><ActivityList /></Panel></div>
    <div className={styles.execTertiary}><Panel title="Team Workload" action="View team"><TeamWorkload /></Panel><Panel title="Pending Approvals" action="View all"><CompactQueue type="approval" /></Panel><Panel title="Publishing Queue" action="View all"><CompactQueue type="publishing" /></Panel><Panel title="Quick Actions"><QuickActions /></Panel></div>
  </div>;
}

function PipelineRows() { return <div className={styles.pipelineRows}>{[["Prospect","$480,000",15],["Discovery","$620,000",19],["Proposal","$710,000",22],["Negotiation","$540,000",17],["Contract","$430,000",13],["Won","$460,850",14]].map((r,i)=><div key={r[0]}><span>{r[0]}</span><b>{r[1]}</b><em>{r[2]}%</em><i className={styles[`pipe${i}`]} style={{width:`${Number(r[2])*4}%`}} /></div>)}</div>; }

function MeetingRows() { return <div className={styles.meetingRows}>{[["20","Strategy Review — Acme Corp","10:00 AM – 11:00 AM","Meeting"],["21","Editorial Kickoff — Greenfield Ltd.","2:00 PM – 3:00 PM","Meeting"],["22","Client Check-in — Horizon Partners","11:00 AM – 12:00 PM","Meeting"],["23","Draft Review Due — Q2 Magazine","All day","Deadline"],["24","Final Approval — Brand Film","10:00 AM – 11:00 AM","Deadline"]].map(x=><div key={x[0]}><span><small>May</small><b>{x[0]}</b></span><p><b>{x[1]}</b><small>{x[2]}</small></p><em>{x[3]}</em></div>)}</div>; }

function TeamWorkload() { return <div className={styles.workload}>{["Sarah Miller","James Producer","Alex Designer","Maria Editor","David Operations"].map((n,i)=><div key={n}><Image alt="" height={32} src={portraits[i%portraits.length]} width={32}/><p><b>{n}</b><small>{["Account Manager","Podcast Producer","Lead Designer","Senior Editor","Operations Manager"][i]}</small></p><em>{[12,8,15,10,9][i]} tasks</em><span><i style={{width:`${[75,62,80,70,56][i]}%`}}/></span><b>{[75,62,80,70,56][i]}%</b></div>)}</div>; }

function CompactQueue({type}:{type:"approval"|"publishing"}) { const rows=type==="approval"?[["Magazine Cover Design","Acme Corp","Design"],["Article Draft","Greenfield Ltd.","Editorial"],["Video Final Cut","Horizon Partners","Video"],["Podcast Episode 23","TechNova","Audio"],["Event Landing Page","InnovateX","Web"]]:[["Q2 Magazine Issue","Magazine","May 20"],["Brand Film","Video","May 22"],["Podcast Episode 23","Podcast","May 24"],["Thought Leadership Article","Blog","May 28"],["Event Recap","Blog","May 30"]]; return <div className={styles.compactQueue}>{rows.map((x,i)=><div key={x[0]}><span className={styles[`queueTone${i%5}`]}><FileText size={16}/></span><p><b>{x[0]}</b><small>{x[1]}</small></p><em>{x[2]}</em></div>)}</div>; }

export function TeamShellShowcase() {
  const stats = executiveStats.slice(0,3).concat([{label:"Unpaid invoices",value:"$320,450",trend:"7.2%",up:false,icon:ReceiptText,tone:"orangeTone"},{label:"Open tasks",value:"243",trend:"4.1%",up:false,icon:ClipboardCheck,tone:"greenTone"}]);
  return <div className={styles.shellShowcase}><PageTitle title="Executive Overview" subtitle="Real-time overview of key metrics across the business." actions={<><button className={styles.controlButton}><Share2 size={16}/> Share</button><button className={styles.primaryAction}><Plus size={16}/> Add widget</button></>} /><div className={styles.shellGrid}><div><div className={styles.statsGrid}>{stats.map(s=><StatCard stat={s} key={s.label}/>)}</div><div className={styles.shellCharts}><Panel title="Revenue Overview" action="This month"><CssLineChart /></Panel><Panel title="Projects by Stage" action="All projects"><Donut total="86" label="Total" /></Panel></div><div className={styles.shellTables}><Panel title="Recent Projects" action="View all"><ProjectTable /></Panel><Panel title="My Tasks" action="View all (243)"><TaskRows /></Panel></div></div><aside className={styles.shellRail}><Panel title="Activity Feed" action="View all"><ActivityList /></Panel><Panel title="Upcoming Meetings" action="View calendar"><MeetingRows /></Panel><Panel title="Quick Actions"><QuickActions /></Panel></aside></div></div>;
}

function ProjectTable(){return <div className={styles.dataTable}><div className={styles.tableHead}><span>Project name</span><span>Client</span><span>Stage</span><span>Due date</span><span>Progress</span><span>Status</span></div>{[["Q2 Magazine Issue","Acme Corporation","In production","May 24","72%","On track"],["Leadership Podcast Ep. 23","TechNova","Review","May 20","58%","On track"],["Brand Film","BluePeak Partners","Production","May 28","41%","At risk"],["Industry Report 2026","Global Dynamics","Research","Jun 03","24%","On track"],["CEO Interview Series","InnovateX","Planning","Jun 10","12%","On track"]].map((x,i)=><div className={styles.tableRow} key={x[0]}>{x.map((y,j)=><span className={j===0?styles.cellLink:j===5?styles.statusCell:""} key={j}>{j===4?<i className={styles.miniProgress}><b style={{width:y}}/></i>:y}</span>)}</div>)}</div>}
function TaskRows(){return <div className={styles.taskRows}>{[["Review magazine draft","Q2 Magazine Issue","High","May 20"],["Client questionnaire follow-up","Acme Corporation Project","Medium","May 20"],["Approve podcast episode outline","Leadership Podcast Ep. 23","High","May 21"],["Upload brand assets","Brand Film","Low","May 22"],["Finance report review","May Monthly Report","Medium","May 23"]].map(x=><label key={x[0]}><input type="checkbox"/><p><b>{x[0]}</b><small>{x[1]}</small></p><em>{x[2]}</em><span>{x[3]}</span></label>)}</div>}

const salesStats: Stat[] = [
  {label:"Leads added",value:"248",trend:"18.6%",icon:Users,tone:"purpleTone"},{label:"Qualified leads",value:"128",trend:"21.4%",icon:CheckCircle2,tone:"greenTone"},{label:"Active opportunities",value:"86",trend:"8.7%",icon:CalendarDays},{label:"Pipeline value",value:"$2.85M",trend:"15.2%",icon:TrendingUp,tone:"orangeTone"},{label:"Expected revenue",value:"$1.24M",trend:"19.8%",icon:CircleDollarSign,tone:"greenTone"},{label:"Deals won",value:"18",trend:"28.6%",icon:Filter,tone:"purpleTone"},{label:"Meetings booked",value:"32",trend:"14.3%",icon:CalendarDays,tone:"orangeTone"},{label:"Proposals sent",value:"15",trend:"15.4%",icon:FileText},
];

export function SalesDashboard(){return <div className={styles.dashboardPage}><PageTitle title="Sales Dashboard" subtitle="Real-time overview of your sales pipeline and performance." actions={<DateControls compare/>}/><div className={styles.statsGrid}>{salesStats.map(s=><StatCard stat={s} key={s.label}/>)}</div><div className={styles.salesPrimary}><Panel title="Pipeline by Stage" action="All deals"><SalesFunnel/></Panel><Panel title="Pipeline Value Over Time" action="This month"><CssLineChart sales/></Panel><Panel title="Lead Source Performance" action="This month"><Donut total="248" label="Total leads" variant="leads"/></Panel></div><div className={styles.salesSecondary}><Panel title="Recent Leads" action="View all"><RecentLeads/></Panel><Panel title="Upcoming Follow-ups" action="View calendar"><FollowUps/></Panel><Panel title="Deals by Status" action="View all"><DealStatus/></Panel></div><div className={styles.salesTertiary}><Panel title="Sales Performance (This Month)" action="View report"><SalesPerformance/></Panel><Panel title="Top Performing Salespeople" action="View all"><TopPerformers/></Panel><Panel title="Quick Actions"><QuickActions type="sales"/></Panel></div></div>}

function SalesFunnel(){return <div className={styles.funnelWrap}><div className={styles.funnel}>{[["Qualified",100],["Discovery",83],["Proposal",66],["Negotiation",49],["Won",32]].map((x,i)=><div className={styles[`funnel${i}`]} style={{width:`${x[1]}%`}} key={x[0]}><span>{x[0]}</span></div>)}</div><div className={styles.funnelStats}><small>Total pipeline value</small><strong>$2.85M <em>↑ 15.2%</em></strong><p>Weighted pipeline <b>$1.24M</b></p><p>Avg. deal size <b>$33,097</b></p><p>Win rate <b>14.1%</b></p></div></div>}
function RecentLeads(){return <div className={styles.simpleTable}>{["Alex Johnson","Priya Sharma","Michael Brown","Jessica Lee","David Wilson"].map((n,i)=><div key={n}><Link href="/app/sales/leads">{n}</Link><span>{["TechNova Inc.","Greenfield Ltd.","InnovateX","BluePeak Partners","NextGen Solutions"][i]}</span><em>{["LinkedIn","Website","Referral","Event","Cold outreach"][i]}</em><b>{[85,78,72,68,65][i]}</b><Image alt="" height={24} src={portraits[i%4]} width={24}/><small>{["1h","3h","5h","7h","9h"][i]} ago</small></div>)}</div>}
function FollowUps(){return <div className={styles.followups}>{[["20","Follow up: Alex Johnson","TechNova Inc.","10:00 AM","High"],["20","Proposal discussion: Sarah Miller","Acme Corporation","11:30 AM","Medium"],["20","Product demo: Greenfield Ltd.","Greenfield Ltd.","02:00 PM","High"],["21","Contract review: InnovateX","InnovateX","10:30 AM","Medium"],["21","Check-in call: BluePeak Partners","BluePeak Partners","03:30 PM","Low"]].map(x=><div key={x[1]}><span><small>May</small><b>{x[0]}</b></span><p><b>{x[1]}</b><small>{x[2]}</small></p><time>{x[3]}</time><em>{x[4]}</em></div>)}</div>}
function DealStatus(){return <div className={styles.dealStatus}>{[["Open","86 deals","$2.85M"],["Won","18 deals","$612K"],["Lost","9 deals","$210K"],["On hold","7 deals","$145K"],["Closed (not won)","5 deals","$98K"]].map((x,i)=><div key={x[0]}><i data-index={i}/><span>{x[0]}</span><small>{x[1]}</small><b>{x[2]}</b></div>)}</div>}
function SalesPerformance(){return <div className={styles.performanceGrid}>{[["Emails sent","1,248","16.3%",Mail],["Responses","312","20.6%",MessageSquare],["Response rate","25.0%","3.7%",Gauge],["Meetings booked","32","14.3%",CalendarDays],["Conversion rate","12.9%","2.1%",TrendingUp]].map(([a,b,c,I])=>{const Icon=I as IconType;return <div key={a as string}><Icon size={18}/><span>{a as string}</span><strong>{b as string}</strong><em>↑ {c as string}</em></div>})}</div>}
function TopPerformers(){return <div className={styles.topPerformers}>{["Sarah Miller","John Smith","Mark Johnson","Priya Patel","James Wilson"].map((n,i)=><div key={n}><b>{i+1}</b><Image alt="" height={27} src={portraits[i%4]} width={27}/><span>{n}</span><i><em style={{width:`${95-i*11}%`}}/></i><strong>{["$482,000","$412,500","$315,800","$298,400","$254,600"][i]}</strong><small>{16-i*2} deals</small></div>)}</div>}

const editorialStats: Stat[]=[{label:"Active editorial projects",value:"86",trend:"8.7%",icon:FolderKanban},{label:"Drafts in progress",value:"62",trend:"11.3%",icon:PenLine,tone:"purpleTone"},{label:"Internal review",value:"18",trend:"10.0%",up:false,icon:Users,tone:"orangeTone"},{label:"Client review",value:"24",trend:"14.3%",icon:UserRoundIcon},{label:"Ready for approval",value:"15",trend:"15.4%",icon:CheckCircle2,tone:"greenTone"},{label:"Ready to publish",value:"9",trend:"28.6%",icon:Rocket,tone:"purpleTone"},{label:"Overdue items",value:"12",trend:"9.1%",up:false,icon:Clock3,tone:"redTone"}];
function UserRoundIcon({size=23}:{size?:number}){return <Users size={size}/>}

export function EditorialDashboard(){return <div className={styles.dashboardPage}><PageTitle title="Editorial Dashboard" subtitle="Manage editorial workflow, content quality, and the publication pipeline." actions={<DateControls compare/>}/><div className={styles.statsGrid}>{editorialStats.map(s=><StatCard stat={s} key={s.label}/>)}</div><div className={styles.editorialPrimary}><Panel title="Projects by Editorial Stage" action="All content"><Donut total="86" label="Total projects" variant="content"/></Panel><Panel title="Editorial Workflow Overview" action="All content"><ProgressRows editorial/><div className={styles.overallProgress}><i/><span>Overall progress <b>63%</b></span></div></Panel><Panel title="Editorial Reminders" action="View all"><EditorialReminders/></Panel></div><div className={styles.editorialSecondary}><Panel title="Drafts Awaiting Internal Review" action="View all"><EditorialQueue kind="draft"/></Panel><Panel title="Client Review — Awaiting Response" action="View all"><EditorialQueue kind="client"/></Panel><Panel title="Content Types Overview" action="This month"><Donut total="128" label="Total content" variant="content"/></Panel><Panel title="Upcoming Editorial Deadlines" action="View calendar"><EditorialDeadlines/></Panel></div><div className={styles.editorialTertiary}><Panel title="Editorial Team Workload" action="This week"><EditorialWorkload/></Panel><Panel title="Recent Editorial Activity" action="View all"><ActivityList editorial/></Panel><Panel title="Quick Actions"><QuickActions type="editorial"/></Panel></div></div>}

function EditorialReminders(){return <div className={styles.reminders}>{[["3 drafts past due","Update required","10m"],["5 items waiting for client response","Action needed","25m"],["7 assets still missing","Upload required","1h"],["2 approvals waiting for your review","Review pending","2h"],["Q2 Magazine Issue locked for publishing","Ready to publish","3h"]].map((x,i)=><div key={x[0]}><span className={styles[`queueTone${i%5}`]}>{i<2?<AlertTriangle size={16}/>:<FileText size={16}/>}</span><p><b>{x[0]}</b><small>{x[1]}</small></p><em>{x[2]} ago</em></div>)}</div>}
function EditorialQueue({kind}:{kind:"draft"|"client"}){const data=kind==="draft"?[["The Future of AI in Business","Article","Alex Writer","May 20","High"],["Leadership in the New Era","Article","Sarah Writer","May 21","Medium"],["Sustainable Cities of Tomorrow","Article","Mark Writer","May 22","Medium"],["Fintech Revolution 2026","Blog","Priya Writer","May 22","Low"],["Future of Work — Remote & Hybrid","Blog","James Writer","May 23","Low"]]:[["Personal Magazine — May 2026","Magazine project","Acme Corporation","","High"],["Brand Film — Corporate Story","Video project","BluePeak Partners","","High"],["Podcast Ep. 23 — Leadership Talk","Podcast project","TechNova","","Medium"],["Industry Report 2026","Report project","Global Dynamics","","Medium"],["CEO Interview — Arjun Mehta","Interview project","InnovateX","","Low"]];return <div className={styles.editorialQueue}>{data.map((x,i)=><div key={x[0]}><Image alt="" height={36} src={i%2?"/images/articles/board-governance.png":"/images/articles/ai-infrastructure.png"} width={48}/><p><b>{x[0]}</b><small>{x[1]}</small></p>{kind==="draft"&&<><Image alt="" height={22} src={portraits[i%4]} width={22}/><span>{x[2]}</span><time>Due {x[3]}</time></>} {kind==="client"&&<span>{x[2]}</span>}<em>{x[4]}</em></div>)}</div>}
function EditorialDeadlines(){return <div className={styles.deadlines}>{[["20","Article Draft Deadline","AI in Business","11:59 PM","High"],["21","Magazine Content Lock","Q2 Magazine Issue","11:59 PM","High"],["22","Podcast Recording","Ep. 23 — Leadership Talk","02:00 PM","Medium"],["23","Client Approval Deadline","Brand Film — Corporate Story","11:59 PM","Low"],["24","Publish Industry Report","Industry Report 2026","09:00 AM","Low"]].map(x=><div key={x[0]}><span><small>May</small><b>{x[0]}</b></span><p><b>{x[1]}</b><small>{x[2]}</small></p><time>{x[3]}</time><em>{x[4]}</em></div>)}</div>}
function EditorialWorkload(){return <div className={styles.editorWorkload}><div className={styles.workHead}><span>Team member</span><span>Role</span><span>Projects</span><span>Tasks</span><span>Done</span><span>Load</span></div>{["Emma Johnson","Sarah Writer","Mark Editor","Alex Writer","Priya Writer"].map((n,i)=><div key={n}><span>{n}</span><small>{["Editor-in-Chief","Senior Editor","Editor","Senior Writer","Writer"][i]}</small><b>{[18,14,12,10,8][i]}</b><b>{[24,20,18,16,14][i]}</b><b>{[16,14,12,9,8][i]}</b><i><em style={{width:`${[85,72,68,65,58][i]}%`}}/></i><strong>{[85,72,68,65,58][i]}%</strong></div>)}</div>}

export function ClientDashboard(){return <div className={styles.clientDashboard}><div className={styles.clientWelcome}><div><h1>Welcome back, Arjun! <span>👋</span></h1><p>Here’s what’s happening with your projects.</p></div><div className={styles.clientQuick}><b>Quick Actions</b>{[["Message team",Send],["Upload files",CloudUpload],["View tasks",ListChecks],["Schedule meeting",CalendarDays]].map(([a,I])=>{const Icon=I as IconType;return <button key={a as string}><Icon size={20}/><span>{a as string}</span></button>})}</div></div><div className={styles.clientStats}>{[["Active projects","5",FileText,"View all projects"],["Needs your attention","7",BellRing,"View all items"],["Upcoming meetings","2",CalendarDays,"View calendar"],["Pending approvals","3",ShieldCheck,"Review now"]].map(([a,b,I,c],i)=>{const Icon=I as IconType;return <article key={a as string}><span className={styles[`clientTone${i}`]}><Icon size={24}/></span><p><small>{a as string}</small><strong>{b as string}</strong><Link href="/client/projects">{c as string}<ChevronRight size={13}/></Link></p></article>})}</div><div className={styles.clientBody}><div><div className={styles.clientColumns}><Panel title="My Projects" action="View all projects"><ClientProjects/></Panel><Panel title="Needs Your Attention" action="View all"><AttentionList/></Panel></div><Panel title="Project Progress Overview"><ClientProgress/></Panel></div><aside className={styles.clientRail}><Panel title="Upcoming Meetings" action="View calendar"><ClientMeetings/></Panel><Panel title="Recent Messages" action="View all"><ClientMessages/></Panel><Panel title="Helpful Resources" action="View all"><ClientResources/></Panel></aside></div></div>}

function ClientProjects(){return <div className={styles.clientProjects}>{[["Personal Magazine — May 2026","The Perspective Magazine","Design review",75,"May 30","/images/articles/elena-rossi.png"],["Podcast Episode — Leadership Talk","The Perspective Podcast","In production",45,"May 25","/images/podcasts/naveen-malhotra-hero-clean.png"],["Brand Film — Corporate Story","The Perspective Video","Editing",60,"Jun 02","/images/articles/board-governance.png"],["Executive Summit 2026","Event & Summit","Planning",30,"Jun 15","/images/articles/global-growth.png"],["Thought Leadership Article Series","The Perspective Blog","Draft review",50,"May 28","/images/articles/computing-infrastructure.png"]].map(x=><Link href="/client/projects" key={x[0] as string}><Image alt="" height={56} src={x[5] as string} width={56}/><p><b>{x[0] as string}</b><small>{x[1] as string}</small></p><em>{x[2] as string}</em><div><b>{x[3] as number}%</b><i><span style={{width:`${x[3]}%`}}/></i></div><time>Due date<small>{x[4] as string}</small></time><ChevronRight size={16}/></Link>)}</div>}
function AttentionList(){return <div className={styles.attentionList}>{[["Approve magazine cover design","Personal Magazine — May 2026","High",ShieldCheck],["Review article draft","Thought Leadership Series","Medium",FileText],["Provide feedback on brand film","Brand Film — Corporate Story","Medium",Video],["Upload final profile photo","Podcast Episode — Leadership Talk","Low",Upload],["Sign contract INV-2024-1057","The Perspective Magazine","High",FileCheck2]].map(([a,b,c,I],i)=>{const Icon=I as IconType;return <div key={a as string}><span className={styles[`clientTone${i%4}`]}><Icon size={19}/></span><p><b>{a as string}</b><small>{b as string}</small></p><em>{c as string}</em></div>})}</div>}
function ClientMeetings(){return <div className={styles.clientMeetings}>{[["20","Project Kickoff Meeting","Personal Magazine — May 2026","10:00 AM – 11:00 AM"],["22","Content Strategy Review","Brand Film — Corporate Story","2:00 PM – 3:00 PM"]].map(x=><div key={x[0]}><span><small>May</small><b>{x[0]}</b></span><p><b>{x[1]}</b><small>{x[2]}</small><em>{x[3]}</em></p></div>)}</div>}
function ClientMessages(){return <div className={styles.clientMessages}>{[["SM","Sarah Miller","Hi Arjun, please review the latest draft...","2m"],["JP","James Producer","Podcast recording is confirmed...","1h"],["AD","Alex Designer","Cover design concepts are ready...","3h"]].map(x=><div key={x[0]}><span>{x[0]}</span><p><b>{x[1]}</b><small>{x[2]}</small></p><em>{x[3]} ago</em><i/></div>)}</div>}
function ClientResources(){return <div className={styles.resourceGrid}>{[["How it works","Step-by-step guide",FileText],["Client guidelines","Our process & policies",BookOpen],["FAQ","Common questions",CircleHelp]].map(([a,b,I],i)=>{const Icon=I as IconType;return <Link href="/client/support" key={a as string}><span className={styles[`clientTone${i}`]}><Icon size={21}/></span><b>{a as string}</b><small>{b as string}</small></Link>})}</div>}
function ClientProgress(){return <div className={styles.clientProgress}>{[["Planning","2 projects",CloudUpload],["In production","2 projects",Sparkles],["In review","3 projects",FileText],["Approved","1 project",ShieldCheck],["Published","1 project",PackageCheck]].map(([a,b,I],i)=>{const Icon=I as IconType;return <div key={a as string}><span className={styles[`clientTone${i%4}`]}><Icon size={19}/></span><p><b>{a as string}</b><small>{b as string}</small></p>{i<4&&<ChevronRight size={17}/>}</div>})}<i><span/></i><small>Overall completion <b>56%</b></small></div>}
