import Link from "next/link";
import { siteConfig } from "@/config/site";
import { PageContainer } from "./page-container";
import { NewsletterForm } from "./newsletter-form";

export function SiteFooter() {
  return <footer className="border-t-4 border-accent bg-foreground text-white"><PageContainer className="py-14 sm:py-18 lg:py-24"><div className="grid gap-12 border-b border-white/20 pb-14 lg:grid-cols-[1.15fr_.85fr] lg:gap-20"><div><Link className="font-serif text-[clamp(2.5rem,6vw,5.5rem)] leading-none tracking-[-.055em]" href="/">The Perspective</Link><p className="mt-6 max-w-xl text-sm leading-7 text-white/60">{siteConfig.description} A publication for readers who believe a wider frame changes what is possible.</p></div><NewsletterForm /></div>
    <div className="grid grid-cols-2 gap-x-6 gap-y-12 py-14 sm:grid-cols-4 lg:grid-cols-[1.3fr_1.3fr_1fr_.9fr]">{siteConfig.footerSections.map((section) => <nav aria-label={`${section.title} links`} key={section.title}><h2 className="eyebrow mb-5 text-premium">{section.title}</h2><ul className="space-y-3 text-sm text-white/72">{section.links.map((link) => <li key={link.href}><Link className="transition-colors hover:text-white" href={link.href}>{link.label}</Link></li>)}</ul></nav>)}</div>
    <div className="flex flex-col gap-7 border-t border-white/20 pt-7"><div className="flex flex-wrap items-center gap-3">{siteConfig.socials.map((social) => <a aria-label={`${social.label} (opens in a new tab)`} className="flex min-h-10 items-center justify-center border border-white/25 px-3 text-[.65rem] font-bold uppercase tracking-wide hover:border-white hover:bg-white hover:text-foreground" href={social.href} key={social.label} rel="noreferrer" target="_blank">{social.label}</a>)}</div><div className="flex flex-col justify-between gap-4 text-xs leading-5 text-white/55 md:flex-row md:items-end"><div><p>© {new Date().getFullYear()} {siteConfig.name}. All rights reserved.</p><p className="mt-1 max-w-2xl">Independent editorial publication. Views expressed by contributors are their own.</p></div><button className="w-fit border-b border-white/30 pb-1 text-left hover:text-white">{siteConfig.edition}</button></div></div></PageContainer></footer>;
}
