import Image from "next/image";
import Link from "next/link";
import {
  ArrowRight, BarChart3, ChevronRight, LineChart, ShieldCheck, Sparkles, UsersRound,
} from "lucide-react";
import type { Article, CategoryLandingContent } from "@/types";
import { formatEditorialDate } from "@/lib/editorial-date";
import styles from "./business-redesign.module.css";

const tabs = ["All Business","Companies","Economy","Entrepreneurship","Markets","Leadership","Startups","Global Business","Analysis","Interviews"] as const;
const topics = ["Corporate Strategy","Market Trends","Digital Transformation","Investment","Startups","Innovation","Private Equity","ESG"] as const;
const companies = [
  ["Reliance Industries","Expanding retail and digital consumer footprint"],
  ["Tata Consultancy Services","AI-led transformation driving future growth"],
  ["HDFC Bank","Strong balance sheet, leadership in lending"],
  ["Bharti Airtel","Scaling 5G and digital ecosystem"],
  ["Adani Group","Diversifying across ports, energy and airports"],
] as const;

function Breaking(){return <section className={styles.breaking}><div className={styles.shell}><strong>Breaking</strong><div><Link href="/article/markets-optimism">Markets reassess the path for interest rates</Link><Link href="/article/industrial-investment-strategy">Industrial investment moves back to the center of strategy</Link><Link href="/article/global-computing-capacity">Computing capacity becomes a global priority</Link></div><span><i/>Live</span></div></section>}
function SectionHeader({title,href="/business",action="View all"}:{title:string;href?:string;action?:string}){return <header className={styles.sectionHeader}><h2>{title}</h2><Link href={href}>{action}<ArrowRight/></Link></header>}
function StoryImage({article,sizes}:{article:Article;sizes:string}){return article.heroImage?<Image alt={article.heroImage.alt} fill sizes={sizes} src={article.heroImage.src}/>:null}
function Meta({article}:{article:Article}){return <small><time dateTime={article.publishedAt??article.updatedAt}>{formatEditorialDate(article.publishedAt??article.updatedAt)}</time><i/> {article.readingMinutes} min read</small>}

function CategoryHero({content}:{content:CategoryLandingContent}){return <section className={styles.categoryHero}><div className={`${styles.shell} ${styles.heroGrid}`}><div className={styles.heroCopy}><nav><Link href="/">Home</Link><ChevronRight/><Link href="/latest">News</Link><ChevronRight/><span>Business</span></nav><h1>Business</h1><h2>Business in Motion</h2><p>Companies, capital, entrepreneurs and economies shaping the next era of global growth.</p></div><div className={styles.skyline}><Image alt="A modern global business district" fill priority sizes="500px" src="/images/articles/global-growth.png"/><span/><LineChart/></div><aside className={styles.mostRead}><h2>Most Read in Business</h2>{content.mostRead.slice(0,5).map((article,index)=><Link href={`/article/${article.slug}`} key={article.id}><b>{String(index+1).padStart(2,"0")}</b>{article.heroImage?<span><StoryImage article={article} sizes="55px"/></span>:null}<h3>{article.title}</h3></Link>)}</aside></div></section>}
function Subnav(){return <div className={styles.subnav}><nav className={styles.shell}>{tabs.map((tab,index)=><Link aria-current={index===0?"page":undefined} href={index===0?"/business":`/search?q=${encodeURIComponent(tab)}`} key={tab}>{tab}</Link>)}</nav></div>}
function Lead({content}:{content:CategoryLandingContent}){const primary=content.lead.primary;return <section className={styles.leadSection}><div className={`${styles.shell} ${styles.leadGrid}`}><article className={styles.leadStory}><Link href={`/article/${primary.slug}`}><StoryImage article={primary} sizes="(max-width:850px) 100vw, 650px"/><span/></Link><div><p>Featured Story</p><h2><Link href={`/article/${primary.slug}`}>{primary.title}</Link></h2><h3>{primary.dek??primary.excerpt}</h3><Meta article={primary}/></div></article><div className={styles.leadSupport}>{content.lead.supporting.slice(0,3).map(article=><article key={article.id}><div><p>{article.subcategory??article.category.name}</p><h3><Link href={`/article/${article.slug}`}>{article.title}</Link></h3><Meta article={article}/></div>{article.heroImage?<Link href={`/article/${article.slug}`}><StoryImage article={article} sizes="180px"/></Link>:null}</article>)}</div><aside className={styles.topics}><h2>Related Topics</h2><div>{topics.map(topic=><Link href={`/search?q=${encodeURIComponent(topic)}`} key={topic}>{topic}</Link>)}</div><Link href="/search?q=business">See All Topics <ArrowRight/></Link></aside></div></section>}
function Latest({content}:{content:CategoryLandingContent}){return <section className={styles.section}><div className={styles.shell}><SectionHeader action="View All Business News" href="/search?q=business&type=articles" title="Latest from Business"/><div className={styles.latest}>{content.latest.slice(0,5).map(article=><article key={article.id}>{article.heroImage?<Link className={styles.cardImage} href={`/article/${article.slug}`}><StoryImage article={article} sizes="260px"/></Link>:null}<div><p>{article.subcategory??article.category.name}</p><h3><Link href={`/article/${article.slug}`}>{article.title}</Link></h3><Meta article={article}/></div></article>)}</div></div></section>}
function MiniList({articles}:{articles:readonly Article[]}){return <div className={styles.miniList}>{articles.slice(0,2).map(article=><Link href={`/article/${article.slug}`} key={article.id}>{article.heroImage?<span><StoryImage article={article} sizes="80px"/></span>:null}<div><h3>{article.title}</h3><Meta article={article}/></div></Link>)}</div>}
function Intelligence({content}:{content:CategoryLandingContent}){const sections=content.editorialSections;const economy=sections[1];const entrepreneur=sections[2];const global=sections[3];return <section className={styles.section}><div className={`${styles.shell} ${styles.intelligence}`}><section className={styles.watch}><SectionHeader action="View all" title="Companies to Watch"/><ul>{companies.map(([name,desc],index)=><li key={name}><span>{["R","T","H","A","G"][index]}</span><div><b>{name}</b><p>{desc}</p></div></li>)}</ul><Link href="/search?q=companies">View All Companies <ArrowRight/></Link></section><EditorialColumn section={economy}/><EditorialColumn section={entrepreneur}/><EditorialColumn section={global}/><ExpertInsight content={content}/></div></section>}
function EditorialColumn({section}:{section:CategoryLandingContent["editorialSections"][number]|undefined}){if(!section)return null;return <section className={styles.editorialColumn}><SectionHeader action="View all" href={section.href} title={section.title}/>{section.feature.heroImage?<Link className={styles.columnImage} href={`/article/${section.feature.slug}`}><StoryImage article={section.feature} sizes="260px"/></Link>:null}<h2><Link href={`/article/${section.feature.slug}`}>{section.feature.title}</Link></h2><p>{section.feature.excerpt}</p><Meta article={section.feature}/><MiniList articles={section.supporting}/></section>}
function ExpertInsight({content}:{content:CategoryLandingContent}){const person=content.interview;return <section className={styles.expert}><h2>Expert Insight</h2><Link className={styles.expertImage} href={content.interviewHref}>{person.portrait?<Image alt={person.portrait.alt} fill sizes="260px" src={person.portrait.src}/>:null}</Link><h3><Link href={content.interviewHref}>The Next Decade of Corporate India</Link></h3><blockquote>“The companies that will lead tomorrow are those that invest in people, innovation and purpose—together.”</blockquote><p><b>{person.name}</b><span>{person.title}, {person.company}</span></p><Link href={content.interviewHref}>Read Full Interview <ArrowRight/></Link></section>}
function Promotions({content}:{content:CategoryLandingContent}){const analysis=content.inDepth;return <section className={styles.section}><div className={`${styles.shell} ${styles.promotions}`}><article className={styles.analysis}><div><p>In Depth Analysis</p><h2>The Future of Work in an AI-Powered Economy</h2><h3>How organizations can adapt, reskill and build a future-ready workforce.</h3><Link href={`/article/${analysis.slug}`}>Read Full Analysis <ArrowRight/></Link></div>{analysis.heroImage?<span><StoryImage article={analysis} sizes="300px"/></span>:null}</article><article className={styles.magazine}><div><p>The Perspective Magazine</p><h2>Business Edition</h2><h3>Deep insights, exclusive interviews and long-form analyses.</h3><Link href="/magazine">Read Latest Issue <ArrowRight/></Link></div><span><Image alt="The Perspective business magazine" fill sizes="150px" src="/images/articles/global-growth.png"/><b>THE<br/>PERSPECTIVE</b></span></article><article className={styles.briefing}><div><p>Stay Ahead</p><h2>Business Briefing</h2><h3>Get the top business stories and insights every morning.</h3><form action="/search"><input aria-label="Email address" name="q" placeholder="Enter your email address" type="email"/><button>Subscribe</button></form></div><span>☕</span></article></div></section>}
function Premium(){return <section className={styles.section}><div className={`${styles.shell} ${styles.premium}`}><article><ShieldCheck/><div><p>The Perspective Premium</p><h2>Unlock Exclusive Business Intelligence</h2><ul><li><Sparkles/><b>Premium Articles</b><span>In-depth reporting</span></li><li><UsersRound/><b>Expert Interviews</b><span>Exclusive conversations</span></li><li><BarChart3/><b>Data &amp; Reports</b><span>Actionable insights</span></li></ul></div></article><article><div><p>Partner With Us</p><h2>Reach senior leaders and decision makers.</h2><Link href="/events#partner">Explore Partnerships</Link></div><span><Image alt="Business leaders in conversation" fill sizes="360px" src="/images/articles/board-governance.png"/></span></article></div></section>}
export function BusinessRedesign({content}:{content:CategoryLandingContent}){return <div className={styles.page}><Breaking/><CategoryHero content={content}/><Subnav/><Lead content={content}/><Latest content={content}/><Intelligence content={content}/><Promotions content={content}/><Premium/><section className={styles.archive}><div className={styles.shell}><p>Complete Business desk</p><h2>Continue with the original category experience.</h2><p>The current Business page, its reporting modules, interview, analysis and full latest-news archive remain available below.</p></div></section></div>}
