import Image from "next/image";
import Link from "next/link";
import {
  ArrowRight, BriefcaseBusiness, Building2, CalendarDays, Check, ChevronRight, Clock3,
  Download, FileText, Globe2, HeartHandshake, Lightbulb, Mail, MapPin,
  Mic2, Network, Play, Sparkles, Ticket, UsersRound,
} from "lucide-react";
import { NewsletterForm } from "@/components/layout/newsletter-form";
import { getPublicAuthors } from "@/data/mock/author-profiles";
import type { EventDetail } from "@/data/mock/events";
import styles from "./event-detail-page.module.css";

const authors=getPublicAuthors();
const portrait=(index:number)=>authors[index%authors.length]?.avatar?.src??"/images/articles/elena-rossi.png";
const speakerNames=["Nandan Nilekani","Falguni Nayar","Sridhar Vembu","Roshni Nadar Malhotra","Harsh Goenka"];
const agenda=[["09:00 AM","Registration & Networking Breakfast",""],["10:00 AM","Opening Keynote: The World in 2026 and Beyond","Nandan Nilekani"],["11:00 AM","Fireside Chat: Building Iconic Consumer Brands","Falguni Nayar"],["12:00 PM","Panel: AI and the Future of Industries","Sridhar Vembu, Roshni Nadar Malhotra"],["01:00 PM","Networking Lunch",""],["02:30 PM","Leadership in an Uncertain World","Harsh Goenka"]] as const;
const themes=[[UsersRound,"Leadership","The next era of responsible leadership"],[Sparkles,"Technology","AI, innovation and emerging technologies"],[Network,"Future of Work","People, culture and productivity"],[HeartHandshake,"Sustainability","Building a resilient and sustainable world"],[Globe2,"Markets","Global economy, capital and investments"]] as const;
const partners=[["Infosys","Knowledge Partner"],["accenture","Innovation Partner"],["aws","Technology Partner"],["Google Cloud","Cloud Partner"],["CRED","Business Partner"],["ZOHO","Enterprise Partner"]] as const;

function SectionHeader({title,href,action="View all"}:{title:string;href?:string;action?:string}){return <header className={styles.sectionHeader}><h2>{title}</h2>{href&&<Link href={href}>{action}<ArrowRight/></Link>}</header>}

function Hero({event}:{event:EventDetail}){return <><nav className={styles.breadcrumb} aria-label="Breadcrumb"><Link href="/">Home</Link><ChevronRight/><Link href="/events">Events & Summits</Link><ChevronRight/><b>{event.title}</b></nav><section className={styles.hero}><Image alt={`${event.title} auditorium`} fill priority sizes="(max-width:900px) 100vw, 1440px" src={event.heroImage}/><span/><div className={styles.heroCopy}><p>The Perspective Events</p><h1>{event.title}</h1><h2>{event.strapline}</h2><div className={styles.heroDetails}><ul><li><CalendarDays/>{event.dates}</li><li><MapPin/>{event.venue}<br/>{event.city}</li></ul><p>{event.description}</p></div><div className={styles.heroActions}><a href="#register">Register now</a><a href="#agenda">View full agenda</a><a href="#partners">Become a partner</a></div></div><aside className={styles.glance}><h2>Event at a glance</h2><ul><li><Mic2/><b>{event.speakers}</b><span>Speakers</span></li><li><FileText/><b>{event.sessions}</b><span>Sessions</span></li><li><UsersRound/><b>{event.attendees}</b><span>Attendees</span></li><li><CalendarDays/><b>2</b><span>Days</span></li></ul><nav><Link href="/search?q=leadership"><UsersRound/>Leadership</Link><Link href="/business"><BriefcaseBusiness/>Business</Link><Link href="/technology"><Sparkles/>Technology</Link><Link href="/search?q=markets"><Globe2/>Markets</Link></nav><p>#TPSummit2026</p><div>in　X　◎　▶</div></aside></section></>}

function ValueStrip(){return <section className={styles.valueStrip}>{[[Globe2,"Global perspectives","Leaders from across industries and geographies"],[Lightbulb,"Actionable insights","Ideas and strategies you can apply immediately"],[UsersRound,"Meaningful connections","Network with top leaders, investors and innovators"],[Sparkles,"Future-focused","Conversations shaping business, technology and society"]].map(([Icon,title,copy])=><article key={String(title)}><Icon/><div><b>{String(title)}</b><p>{String(copy)}</p></div></article>)}</section>}

function Speakers(){return <section className={styles.speakers}><SectionHeader action="View all speakers" href="/authors" title="Featured speakers"/><div>{speakerNames.map((name,index)=><Link href={`/search?q=${encodeURIComponent(name)}`} key={name}><span><Image alt={name} fill sizes="180px" src={portrait(index)}/></span><h3>{name}</h3><p>{["Co-founder and Chairman, Infosys","Founder & CEO, Nykaa","Founder & CEO, Zoho Corporation","Chairperson, HCL Technologies","Chairman, RPG Enterprises"][index]}</p></Link>)}</div></section>}

function Overview({event}:{event:EventDetail}){return <section className={styles.overview}><SectionHeader title="Event overview"/><p>The Perspective {event.title} brings together visionary leaders, entrepreneurs, investors, policymakers and innovators for two days of bold conversations and future-focused insights.</p><p>From AI and digital transformation to leadership, markets and sustainability—explore the ideas defining tomorrow.</p><Link href="/search?q=event+brochure">Download event brochure<Download/></Link></section>}

function Themes(){return <section className={styles.themes}><SectionHeader title="Key themes"/><div>{themes.map(([Icon,title,copy])=><article key={String(title)}><Icon/><div><b>{String(title)}</b><p>{String(copy)}</p></div></article>)}</div></section>}

function Agenda(){return <section className={styles.agenda} id="agenda"><SectionHeader action="View full agenda" href="/search?q=leadership+summit+agenda" title="Event agenda"/><nav><button type="button">Day 1 · May 29, 2026</button><button type="button">Day 2 · May 30, 2026</button></nav><ol>{agenda.map(([time,title,speaker])=><li key={`${time}-${title}`}><time>{time}</time><div><b>{title}</b>{speaker&&<p>{speaker}</p>}</div></li>)}</ol><Link href="/search?q=leadership+summit+agenda">View full agenda<ArrowRight/></Link></section>}

function DetailRail({event}:{event:EventDetail}){return <aside className={styles.detailRail}><section><SectionHeader title="Event details"/><ul><li><CalendarDays/><div><b>Date</b><span>{event.dates}</span></div></li><li><MapPin/><div><b>Venue</b><span>{event.venue}, {event.city}</span></div></li><li><Clock3/><div><b>Time</b><span>09:00 AM – 06:00 PM (IST)</span></div></li><li><BriefcaseBusiness/><div><b>Dress code</b><span>Business / Business Casual</span></div></li><li><Ticket/><div><b>Event type</b><span>In-Person</span></div></li></ul></section><section className={styles.early}><h2>Early bird registration</h2><p>Save up to 20% on early bird passes.<br/><b>Offer ends on March 15, 2026.</b></p><a href="#register">Register now<ArrowRight/></a></section><section><SectionHeader title="Why attend?"/><ul className={styles.checks}>{["Gain actionable insights from global leaders","Stay ahead of industry trends and disruptions","Build meaningful connections and partnerships","Be part of impactful conversations","Access exclusive summit content and reports"].map(item=><li key={item}><Check/>{item}</li>)}</ul></section></aside>}

function Sessions(){const cards=[["Fireside chat","The India Growth Story","Nandan Nilekani in conversation with Ananya Mehta","/images/articles/elena-rossi.png"],["Panel discussion","AI and the Future of Work","Exploring opportunities, challenges and workforce shifts","/images/articles/board-governance.png"],["Roundtable","Founders of Tomorrow","Exclusive roundtable with emerging founders","/images/articles/global-leadership.png"]];return <section className={styles.sessions}><SectionHeader action="View all sessions" href="/search?q=summit+sessions" title="Sessions highlight"/><div>{cards.map(([type,title,copy,image])=><article key={title}><Link href="/videos"><span><Image alt={title} fill sizes="350px" src={image}/><Play/></span></Link><p>{type}</p><h3>{title}</h3><small>{copy}</small></article>)}</div></section>}

function Highlights(){return <section className={styles.highlights}><SectionHeader action="View highlights" href="/videos" title="Past editions highlights"/><div className={styles.stats}>{[["2","Editions"],["70+","Speakers"],["1,800+","Attendees"],["25+","Sessions"],["45+","Partner organizations"]].map(([value,label])=><span key={label}><b>{value}</b><small>{label}</small></span>)}</div><Link href="/videos"><Image alt="World Summit highlights" fill sizes="280px" src="/images/events/leadership-summit-hero.png"/><i><Play/></i><b>World Summit 2025<br/>Highlights</b><small>02:15 min</small></Link></section>}

function Partners(){return <section className={styles.partners} id="partners"><SectionHeader action="View all partners" href="/search?q=event+partners" title="Our partners"/><div>{partners.map(([name,type])=><Link href={`/search?q=${encodeURIComponent(name)}`} key={name}><b>{name}</b><small>{type}</small></Link>)}</div></section>}

function Venue(){return <section className={styles.venue}><SectionHeader title="Venue"/><div><span><Image alt="Bharat Mandapam, New Delhi" fill sizes="380px" src="/images/articles/global-growth.png"/></span><article><h2>Bharat Mandapam</h2><p>Pragati Maidan, New Delhi, India</p><p>India’s premier convention and exhibition centre, located in the heart of New Delhi, offering world-class facilities.</p><ul><li><Check/>Spacious auditoriums</li><li><Check/>State-of-the-art infrastructure</li><li><Check/>Easy connectivity</li></ul><Link href="/search?q=Bharat+Mandapam+directions">Get directions<ArrowRight/></Link></article></div></section>}

function Attend(){return <section className={styles.attend}><SectionHeader title="Who should attend?"/><ul>{[[UsersRound,"C-Level Executives"],[Sparkles,"Entrepreneurs & Founders"],[Globe2,"Investors & VCs"],[Building2,"Policymakers"],[BriefcaseBusiness,"Industry Leaders"],[Network,"Professionals & Consultants"]].map(([Icon,label])=><li key={String(label)}><Icon/>{String(label)}</li>)}</ul></section>}

function Gallery(){const images=["/images/events/leadership-summit-hero.png","/images/articles/board-governance.png","/images/articles/global-leadership.png","/images/articles/elena-rossi.png","/images/articles/arjun-mehta.png","/images/articles/global-growth.png"];return <section className={styles.gallery}><SectionHeader action="View gallery" href="/search?q=summit+gallery" title="Photo gallery"/><div>{images.map((image,index)=><Link href="/search?q=summit+gallery" key={`${image}-${index}`}><Image alt={`Leadership Summit gallery ${index+1}`} fill sizes="180px" src={image}/></Link>)}</div></section>}

function Discovery(){return <section className={styles.discovery}><article><SectionHeader action="View all articles" href="/latest" title="Related articles"/><div>{["The Leadership Agenda for 2026","AI and the Future of Business","Building Resilient Organizations"].map((title,index)=><Link href="/latest" key={title}><span><Image alt="" fill sizes="55px" src={portrait(index)}/></span><div><b>{title}</b><small>{index+5} min read</small></div></Link>)}</div></article><article><SectionHeader action="View all events" href="/events" title="Related events"/><div>{[["The Perspective Finance Summit 2026","Jul 18–19, 2026 · Mumbai"],["Sustainability Summit 2026","Sep 10–11, 2026 · Bengaluru"],["Global Tech Summit 2026","Nov 14–15, 2026 · Singapore"]].map(([title,date])=><Link href="/events" key={title}><CalendarDays/><div><b>{title}</b><small>{date}</small></div></Link>)}</div></article><article><SectionHeader title="Frequently asked questions"/><div className={styles.faq}>{["What is included in the attendee pass?","Is the event virtual or in-person?","Can I get a refund if I cannot attend?","Are group discounts available?"].map(question=><details key={question}><summary>{question}</summary><p>Contact our events team for full registration information.</p></details>)}</div><Link href="/search?q=events+faq">View all FAQs<ArrowRight/></Link></article><article className={styles.updates}><SectionHeader title="Stay updated"/><Mail/><p>Get the latest updates, speaker announcements and exclusive summit insights.</p><NewsletterForm buttonLabel="Subscribe" label="Summit updates" theme="light"/><small>No spam. Unsubscribe anytime.</small></article></section>}

function Registration(){return <section className={styles.registration} id="register"><Image alt="Leadership Summit audience" fill sizes="1400px" src="/images/events/leadership-summit-hero.png"/><span/><div><h2>Be part of the conversations shaping the future.</h2><p>Reserve your seat at The Perspective Leadership Summit 2026.</p></div><Link href="/search?q=leadership+summit+registration">Register now</Link></section>}

export function EventDetailPage({event}:{event:EventDetail}){return <main className={styles.page}><div className={styles.shell}><Hero event={event}/><ValueStrip/><div className={styles.featureGrid}><Speakers/><Overview event={event}/></div><div className={styles.agendaGrid}><Themes/><Agenda/><DetailRail event={event}/></div><Sessions/><div className={styles.partnerGrid}><Highlights/><Partners/></div><div className={styles.venueGrid}><Venue/><Attend/><Gallery/></div><Discovery/><Registration/></div></main>}
