import { z } from "zod";
import { parseAuthenticationJson, requireSameOrigin } from "@/modules/authentication/http/request-security";
import { authorizeTrustedHttpOperation, authorizationProblem } from "@/modules/authorization/http";
import { updateSendingAccount } from "@/modules/comms/core";
import { invalidR6Request,r6CommandError,r6Json,resolveR6TeamRequest,unavailableR6Request } from "@/modules/r6/http";
import { getAuthorizedSendingAccount } from "@/modules/r6/queries";
import { loadR6SendingAccountResource } from "@/modules/r6/resources";
const schema=z.object({expectedRowVersion:z.number().int().positive(),displayName:z.string().trim().max(160).nullable().optional(),dailyLimit:z.number().int().nonnegative().nullable().optional(),hourlyLimit:z.number().int().nonnegative().nullable().optional()}).strict().refine(v=>v.displayName!==undefined||v.dailyLimit!==undefined||v.hourlyLimit!==undefined);
export async function GET(request:Request,route:{params:Promise<{sendingAccountId:string}>}){const {sendingAccountId}=await route.params;if(!z.string().uuid().safeParse(sendingAccountId).success)return invalidR6Request();const r=await resolveR6TeamRequest(request);if(r.kind==="response")return r.response;try{const row=await getAuthorizedSendingAccount(r.context,sendingAccountId);if(!row)return authorizationProblem(404,"AUTHZ_NOT_FOUND");return r6Json({sendingAccount:row});}catch{return unavailableR6Request();}}
export async function PATCH(request:Request,route:{params:Promise<{sendingAccountId:string}>}){if(!requireSameOrigin(request))return authorizationProblem(403,"AUTHZ_DENIED");const input=await parseAuthenticationJson(request,schema);if(!input)return invalidR6Request();const r=await resolveR6TeamRequest(request);if(r.kind==="response")return r.response;const {sendingAccountId}=await route.params;if(!z.string().uuid().safeParse(sendingAccountId).success)return invalidR6Request();const resource=await loadR6SendingAccountResource(r.context,sendingAccountId);if(!resource)return authorizationProblem(404,"AUTHZ_NOT_FOUND");const requestedFields=["displayName","dailyLimit","hourlyLimit"].filter(f=>input[f as keyof typeof input]!==undefined);const a=await authorizeTrustedHttpOperation({context:r.context,permissionKey:"emailaccount.manage",resource,command:{action:"update",requestedFields},concealResource:true});if(a.kind==="response")return a.response;const out=await updateSendingAccount(r.context,{sendingAccountId,...input});if(out.kind==="error")return r6CommandError(out.code);return r6Json({sendingAccount:out.value});}