import Link from "next/link";
import { ArrowRight, BookOpen, Crown } from "lucide-react";
import type { MagazinePremiumPageContent } from "@/types";
import { CategoryNewsletter } from "@/components/category/category-newsletter";
import { PageContainer } from "@/components/layout/page-container";
import { MagazineCover } from "@/components/magazine/magazine-cover";
import { formatMagazineIssueDate } from "@/lib/magazine-issue-date";
import { PremiumIssueCatalogue } from "./premium-issue-catalogue";
import { PremiumPageHeader } from "./premium-page-header";
import { PremiumStoryCard } from "./premium-story-card";

export function MagazinePremiumPage({ content }: { content: MagazinePremiumPageContent }) {
  const { heroIssue } = content;
  return <>
    <PremiumPageHeader readerHref={content.digitalReaderHref} />

    <>
      <div className="bg-[#12120f] text-white"><PageContainer className="section-space-lg" width="standard"><section aria-labelledby="premium-hero-heading" className="grid gap-14 lg:grid-cols-[minmax(16rem,.72fr)_minmax(0,1.28fr)] lg:items-center lg:gap-20"><div className="mx-auto w-[76%] max-w-md lg:w-full"><MagazineCover issue={heroIssue} priority variant="large" /></div><div><p className="eyebrow inline-flex items-center gap-2 text-[#e7c785]"><Crown aria-hidden="true" className="size-4" /> Featured Premium Edition</p><h2 className="mt-5 font-serif text-[clamp(3.2rem,8vw,7.5rem)] leading-[.82] tracking-[-.06em]" id="premium-hero-heading">{heroIssue.coverHeadline}</h2><p className="type-deck mt-7 max-w-3xl text-white/65">{heroIssue.description}</p><p className="type-meta mt-6 text-white/50">{formatMagazineIssueDate(heroIssue.publicationDate)} · Issue {String(heroIssue.issueNumber).padStart(2, "0")} · {heroIssue.pageCount} pages · Premium</p><div className="mt-8 flex flex-wrap gap-3"><Link className="inline-flex min-h-12 items-center gap-2 bg-white px-5 text-sm font-bold text-foreground hover:bg-[#f3e6d0]" href="#featured-premium-stories">Explore stories <ArrowRight aria-hidden="true" className="size-4" /></Link><Link className="inline-flex min-h-12 items-center border border-white/70 px-5 text-sm font-bold hover:bg-white hover:text-foreground" href="/magazine/archive?type=premium">Browse Premium archive</Link></div><ul className="mt-10 border-t border-white/20">{content.heroStories.map(({ article, sectionLabel }) => <li className="border-b border-white/20" key={article.id}><Link className="group grid min-h-16 grid-cols-[6.5rem_minmax(0,1fr)_auto] items-center gap-4 py-4 hover:text-[#e7c785]" href={`/article/${article.slug}`}><span className="type-meta text-white/45">{sectionLabel}</span><span className="font-serif text-lg leading-tight sm:text-xl">{article.title}</span><ArrowRight aria-hidden="true" className="size-4 transition-transform group-hover:translate-x-1" /></Link></li>)}</ul></div></section></PageContainer></div>

      <PageContainer className="section-space" width="standard"><section aria-labelledby="premium-benefits-heading"><div className="grid gap-7 border-t-2 border-foreground pt-5 lg:grid-cols-[.62fr_1.38fr]"><div><p className="eyebrow text-accent">What defines Premium</p><h2 className="type-display-lg mt-5" id="premium-benefits-heading">More room for the story.</h2></div><p className="type-deck max-w-3xl text-muted">Premium is an editorial distinction for issues built with greater depth. It is not an active access decision, paywall or subscription entitlement.</p></div><ol className="mt-12 grid border-t border-border sm:grid-cols-2 lg:grid-cols-5">{content.benefits.map((benefit, index) => <li className="border-b border-border py-7 sm:px-5 sm:first:pl-0 lg:border-r lg:last:border-r-0" key={benefit.id}><span className="font-serif text-3xl text-accent">{String(index + 1).padStart(2, "0")}</span><h3 className="mt-5 font-serif text-2xl leading-tight">{benefit.title}</h3><p className="mt-3 text-sm leading-6 text-muted">{benefit.description}</p></li>)}</ol></section></PageContainer>

      <div className="bg-surface-subtle"><PageContainer className="section-space" width="standard"><PremiumIssueCatalogue issues={content.premiumIssues} /></PageContainer></div>

      <PageContainer className="section-space" width="standard"><section aria-labelledby="featured-premium-heading" id="featured-premium-stories"><header className="grid gap-6 border-t-2 border-foreground pt-5 lg:grid-cols-[.62fr_1.38fr]"><div><p className="eyebrow text-accent">Featured stories</p><h2 className="type-display-lg mt-5" id="featured-premium-heading">Ideas from Premium</h2></div><p className="type-deck max-w-3xl text-muted">A selection from both Premium editions, linked to the same public article routes used across The Perspective.</p></header><div className="mt-12 grid gap-x-9 gap-y-14 lg:grid-cols-2">{content.featuredStories.map((story, index) => <PremiumStoryCard key={story.article.id} lead={index === 0} story={story} />)}</div></section></PageContainer>

      <div className="bg-[#e3ddd1]"><PageContainer className="section-space" width="standard"><section aria-labelledby="premium-voices-heading" className="grid gap-10 lg:grid-cols-[.55fr_1.45fr] lg:gap-20"><div><p className="eyebrow text-accent">Premium voices</p><h2 className="type-display-lg mt-5" id="premium-voices-heading">People with a longer view.</h2><p className="type-body-lg mt-6 text-[#4d4a43]">Interviews and arguments from leaders and writers thinking beyond the immediate cycle.</p></div><ol>{content.voiceStories.map(({ article, issue, sectionLabel }, index) => <li className="grid gap-4 border-t border-[#aaa292] py-6 sm:grid-cols-[3rem_minmax(0,1fr)_auto] sm:gap-6" key={article.id}><span className="font-serif text-2xl text-accent">{String(index + 1).padStart(2, "0")}</span><div><p className="type-meta text-[#665f53]">{sectionLabel} · {formatMagazineIssueDate(issue.publicationDate)}</p><Link className="mt-3 block font-serif text-3xl leading-[.98] hover:text-accent sm:text-4xl" href={`/article/${article.slug}`}>{article.title}</Link><p className="mt-3 text-sm leading-6 text-[#5b554a]">{article.dek ?? article.excerpt}</p>{article.authors[0] ? <p className="type-meta mt-4 text-[#665f53]">By {article.authors[0].name}</p> : null}</div><Link aria-label={`Read ${article.title}`} className="hidden self-center sm:block" href={`/article/${article.slug}`}><ArrowRight aria-hidden="true" className="size-5" /></Link></li>)}</ol></section></PageContainer></div>

      <PageContainer className="section-space" width="standard"><section aria-labelledby="premium-themes-heading"><header className="grid gap-6 border-t-2 border-foreground pt-5 lg:grid-cols-[.62fr_1.38fr]"><div><p className="eyebrow text-accent">Browse by theme</p><h2 className="type-display-lg mt-5" id="premium-themes-heading">Follow the ideas.</h2></div><p className="type-deck max-w-3xl text-muted">Move from Premium editions into the Magazine categories and archive searches that carry these subjects forward.</p></header><nav aria-label="Premium Magazine themes"><ul className="mt-12 grid gap-x-8 md:grid-cols-2 lg:grid-cols-3">{content.themeLinks.map((theme) => <li className="border-t border-border" key={theme.id}><Link className="group block py-6" href={theme.href}><span className="flex items-center justify-between gap-4 font-serif text-3xl group-hover:text-accent">{theme.label}<ArrowRight aria-hidden="true" className="size-5 transition-transform group-hover:translate-x-1" /></span><span className="mt-3 block text-sm leading-6 text-muted">{theme.description}</span></Link></li>)}</ul></nav></section></PageContainer>

      {content.archiveIssues.length > 0 ? <div className="bg-surface-subtle"><PageContainer className="section-space" width="standard"><section aria-labelledby="premium-archive-heading" className="grid gap-12 lg:grid-cols-[.65fr_1.35fr] lg:items-center lg:gap-20"><div><p className="eyebrow text-accent">From the archive</p><h2 className="type-display-lg mt-5" id="premium-archive-heading">Premium has a history.</h2><p className="type-body-lg mt-6 text-muted">Return to earlier special packages and the ideas that continue to shape the Magazine.</p><p className="type-meta mt-6 text-muted">{content.storyCount} unique stories across {content.premiumIssues.length} Premium editions</p><Link className="mt-7 inline-flex min-h-12 items-center gap-2 bg-foreground px-5 text-sm font-bold text-white hover:bg-accent" href="/magazine/archive?type=premium">Explore Premium in the archive <ArrowRight aria-hidden="true" className="size-4" /></Link></div><ol>{content.archiveIssues.map((issue) => <li className="grid grid-cols-[7rem_minmax(0,1fr)] gap-6 border-t border-border py-6 sm:grid-cols-[10rem_minmax(0,1fr)]" key={issue.id}><MagazineCover issue={issue} variant="compact" /><div><p className="type-meta text-[#76531b]">{formatMagazineIssueDate(issue.publicationDate)} · Premium</p><h3 className="mt-3 font-serif text-4xl leading-[.95]">{issue.coverHeadline}</h3><p className="mt-4 text-sm leading-6 text-muted">{issue.description}</p></div></li>)}</ol></section></PageContainer></div> : null}

      <PageContainer className="section-space" width="standard"><section aria-labelledby="premium-comparison-heading"><header className="max-w-3xl"><p className="eyebrow text-accent">Editorial distinction</p><h2 className="type-display-lg mt-5" id="premium-comparison-heading">Standard and Premium editions.</h2><p className="type-deck mt-6 text-muted">Both belong to The Perspective Magazine. Premium signals a deeper editorial package; it does not currently change article access.</p></header><div className="mt-12 grid border-y border-border lg:grid-cols-2"><div className="py-8 lg:pr-10"><p className="type-meta text-muted">Standard editions</p><ul className="mt-5">{content.comparison.standard.map((item) => <li className="border-t border-border py-4 font-serif text-xl" key={item}>{item}</li>)}</ul></div><div className="border-t border-border bg-[#171612] p-8 text-white lg:border-l lg:border-t-0 lg:p-10"><p className="type-meta text-[#e7c785]">Premium editions</p><ul className="mt-5">{content.comparison.premium.map((item) => <li className="border-t border-white/20 py-4 font-serif text-xl" key={item}>{item}</li>)}</ul></div></div></section></PageContainer>

      <div className="bg-[#171612] text-white"><PageContainer className="section-space" width="standard"><section aria-labelledby="premium-membership-heading" className="grid gap-10 lg:grid-cols-[1.15fr_.85fr] lg:items-end"><div><p className="eyebrow text-[#e7c785]">Membership positioning</p><h2 className="type-display-lg mt-5" id="premium-membership-heading">An editorial collection today. A membership foundation tomorrow.</h2><p className="type-deck mt-6 max-w-3xl text-white/60">This page establishes the Premium catalogue without introducing plans, pricing, sign-in or access decisions. Subscription options belong to the next dedicated product stage.</p></div><div className="flex flex-wrap gap-3 lg:justify-end"><Link className="inline-flex min-h-12 items-center gap-2 bg-white px-5 text-sm font-bold text-foreground hover:bg-[#f3e6d0]" href="/magazine#subscribe">Subscription overview <ArrowRight aria-hidden="true" className="size-4" /></Link><Link className="inline-flex min-h-12 items-center gap-2 border border-white/65 px-5 text-sm font-bold hover:bg-white hover:text-foreground" href={content.digitalReaderHref}><BookOpen aria-hidden="true" className="size-4" /> Open Digital Reader</Link></div></section></PageContainer></div>

      <PageContainer className="section-space" width="standard"><div className="grid gap-8 lg:grid-cols-2"><section aria-labelledby="premium-magazine-heading" className="flex min-h-[22rem] flex-col justify-between border-t-2 border-foreground bg-surface p-7 sm:p-10"><div><p className="eyebrow text-accent">The Perspective Magazine</p><h2 className="type-h2 mt-5" id="premium-magazine-heading">Start with the latest issue.</h2><p className="type-body-lg mt-6 max-w-xl text-muted">Explore the current monthly edition, its cover story and the full Magazine experience.</p></div><Link className="mt-8 inline-flex min-h-12 w-fit items-center gap-2 bg-foreground px-5 text-sm font-bold text-white hover:bg-accent" href="/magazine">Latest issue <ArrowRight aria-hidden="true" className="size-4" /></Link></section><section aria-labelledby="premium-discovery-heading" className="flex min-h-[22rem] flex-col justify-between bg-accent p-7 text-white sm:p-10"><div><p className="eyebrow text-white/70">Archive discovery</p><h2 className="type-h2 mt-5" id="premium-discovery-heading">Every issue. Every theme.</h2><p className="type-body-lg mt-6 max-w-xl text-white/75">Browse the publication record by year, theme, Premium status and Reader availability.</p></div><Link className="mt-8 inline-flex min-h-12 w-fit items-center gap-2 bg-white px-5 text-sm font-bold text-foreground hover:bg-[#f3e6d0]" href="/magazine/archive">Browse full archive <ArrowRight aria-hidden="true" className="size-4" /></Link></section></div></PageContainer>

      <div className="bg-surface"><PageContainer className="section-space" width="standard"><CategoryNewsletter description="New issues, deeper interviews and special editions from The Perspective Magazine." eyebrow="For readers who keep the long view" title="The Magazine Briefing" /></PageContainer></div>
    </>
  </>;
}
