import type { PermissionDefinition } from "./types";

export const PERMISSION_DEFINITIONS = [
  {
    key: "analytics.distribution.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R11",
  },
  {
    key: "approval.client.decide",
    surface: "CLIENT",
    risk: "HIGH",
    assignability: "CLIENT_ROLE",
    permittedScopes: ["CLIENT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["audit", "exact-version", "SoD", "client-safe-projection"],
    activationStage: "R8",
  },
  {
    key: "approval.decide",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["audit", "exact-version", "SoD"],
    activationStage: "R8",
  },
  {
    key: "approval.override",
    surface: "TEAM",
    risk: "CRITICAL",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["audit", "reason", "recent-auth", "MFA", "exact-version", "SoD"],
    activationStage: "R8",
  },
  {
    key: "approval.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R8",
  },
  {
    key: "audit.view",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit"],
    activationStage: "R5",
  },
  {
    key: "calendar.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R8",
  },
  {
    key: "campaign.manage",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit"],
    activationStage: "R6",
  },
  {
    key: "campaign.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R6",
  },
  {
    key: "client.approval.view",
    surface: "CLIENT",
    risk: "LOW",
    assignability: "CLIENT_ROLE",
    permittedScopes: ["CLIENT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["client-safe-projection"],
    activationStage: "R12",
  },
  {
    key: "client.asset.upload",
    surface: "CLIENT",
    risk: "MEDIUM",
    assignability: "CLIENT_ROLE",
    permittedScopes: ["CLIENT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["client-safe-projection"],
    activationStage: "R12",
  },
  {
    key: "client.asset.view",
    surface: "CLIENT",
    risk: "LOW",
    assignability: "CLIENT_ROLE",
    permittedScopes: ["CLIENT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["client-safe-projection"],
    activationStage: "R12",
  },
  {
    key: "client.auth.recover",
    surface: "SELF_CLIENT",
    risk: "MEDIUM",
    assignability: "SELF_ONLY",
    permittedScopes: ["NONE", "OWN"],
    requiresFieldPolicy: false,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R3/R12",
  },
  {
    key: "client.auth.signin",
    surface: "SELF_CLIENT",
    risk: "HIGH",
    assignability: "SELF_ONLY",
    permittedScopes: ["NONE", "OWN"],
    requiresFieldPolicy: false,
    requiresWorkflowPolicy: true,
    obligations: ["audit"],
    activationStage: "R3/R12",
  },
  {
    key: "client.billing.pay",
    surface: "CLIENT",
    risk: "HIGH",
    assignability: "CLIENT_ROLE",
    permittedScopes: ["CLIENT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["audit", "financial-evidence", "SoD", "client-safe-projection"],
    activationStage: "R12",
  },
  {
    key: "client.billing.view",
    surface: "CLIENT",
    risk: "LOW",
    assignability: "CLIENT_ROLE",
    permittedScopes: ["CLIENT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["client-safe-projection"],
    activationStage: "R12",
  },
  {
    key: "client.contact.manage",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit"],
    activationStage: "R6",
  },
  {
    key: "client.contract.sign",
    surface: "CLIENT",
    risk: "HIGH",
    assignability: "CLIENT_ROLE",
    permittedScopes: ["CLIENT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["audit", "exact-version", "client-safe-projection"],
    activationStage: "R12",
  },
  {
    key: "client.contract.view",
    surface: "CLIENT",
    risk: "LOW",
    assignability: "CLIENT_ROLE",
    permittedScopes: ["CLIENT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["client-safe-projection"],
    activationStage: "R12",
  },
  {
    key: "client.dashboard.view",
    surface: "CLIENT",
    risk: "LOW",
    assignability: "CLIENT_ROLE",
    permittedScopes: ["CLIENT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["client-safe-projection"],
    activationStage: "R12",
  },
  {
    key: "client.design.review",
    surface: "CLIENT",
    risk: "HIGH",
    assignability: "CLIENT_ROLE",
    permittedScopes: ["CLIENT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["audit", "client-safe-projection"],
    activationStage: "R12",
  },
  {
    key: "client.design.view",
    surface: "CLIENT",
    risk: "LOW",
    assignability: "CLIENT_ROLE",
    permittedScopes: ["CLIENT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["client-safe-projection"],
    activationStage: "R12",
  },
  {
    key: "client.distribution.view",
    surface: "CLIENT",
    risk: "LOW",
    assignability: "CLIENT_ROLE",
    permittedScopes: ["CLIENT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["client-safe-projection"],
    activationStage: "R12",
  },
  {
    key: "client.draft.review",
    surface: "CLIENT",
    risk: "MEDIUM",
    assignability: "CLIENT_ROLE",
    permittedScopes: ["CLIENT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["client-safe-projection"],
    activationStage: "R12",
  },
  {
    key: "client.draft.view",
    surface: "CLIENT",
    risk: "LOW",
    assignability: "CLIENT_ROLE",
    permittedScopes: ["CLIENT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["client-safe-projection"],
    activationStage: "R12",
  },
  {
    key: "client.invite.accept",
    surface: "SELF_CLIENT",
    risk: "MEDIUM",
    assignability: "SELF_ONLY",
    permittedScopes: ["NONE", "OWN"],
    requiresFieldPolicy: false,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R3/R12",
  },
  {
    key: "client.media.review",
    surface: "CLIENT",
    risk: "MEDIUM",
    assignability: "CLIENT_ROLE",
    permittedScopes: ["CLIENT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["client-safe-projection"],
    activationStage: "R12",
  },
  {
    key: "client.media.view",
    surface: "CLIENT",
    risk: "LOW",
    assignability: "CLIENT_ROLE",
    permittedScopes: ["CLIENT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["client-safe-projection"],
    activationStage: "R12",
  },
  {
    key: "client.message.send",
    surface: "CLIENT",
    risk: "HIGH",
    assignability: "CLIENT_ROLE",
    permittedScopes: ["CLIENT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["audit", "client-safe-projection"],
    activationStage: "R12",
  },
  {
    key: "client.message.view",
    surface: "CLIENT",
    risk: "LOW",
    assignability: "CLIENT_ROLE",
    permittedScopes: ["CLIENT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["client-safe-projection"],
    activationStage: "R12",
  },
  {
    key: "client.notification.view",
    surface: "CLIENT",
    risk: "LOW",
    assignability: "CLIENT_ROLE",
    permittedScopes: ["CLIENT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["client-safe-projection"],
    activationStage: "R12",
  },
  {
    key: "client.org.manage",
    surface: "CLIENT",
    risk: "HIGH",
    assignability: "CLIENT_ROLE",
    permittedScopes: ["CLIENT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit", "client-safe-projection"],
    activationStage: "R12",
  },
  {
    key: "client.portal.manage",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit"],
    activationStage: "R6",
  },
  {
    key: "client.portal.provision",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit"],
    activationStage: "R6",
  },
  {
    key: "client.profile.edit",
    surface: "SELF_CLIENT",
    risk: "MEDIUM",
    assignability: "SELF_ONLY",
    permittedScopes: ["NONE", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R3/R12",
  },
  {
    key: "client.project.activity.view",
    surface: "CLIENT",
    risk: "LOW",
    assignability: "CLIENT_ROLE",
    permittedScopes: ["CLIENT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["client-safe-projection"],
    activationStage: "R12",
  },
  {
    key: "client.project.view",
    surface: "CLIENT",
    risk: "LOW",
    assignability: "CLIENT_ROLE",
    permittedScopes: ["CLIENT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["client-safe-projection"],
    activationStage: "R12",
  },
  {
    key: "client.publication.view",
    surface: "CLIENT",
    risk: "LOW",
    assignability: "CLIENT_ROLE",
    permittedScopes: ["CLIENT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["client-safe-projection"],
    activationStage: "R12",
  },
  {
    key: "client.questionnaire.edit",
    surface: "CLIENT",
    risk: "MEDIUM",
    assignability: "CLIENT_ROLE",
    permittedScopes: ["CLIENT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["client-safe-projection"],
    activationStage: "R12",
  },
  {
    key: "client.questionnaire.view",
    surface: "CLIENT",
    risk: "LOW",
    assignability: "CLIENT_ROLE",
    permittedScopes: ["CLIENT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["client-safe-projection"],
    activationStage: "R12",
  },
  {
    key: "client.renewal.view",
    surface: "CLIENT",
    risk: "LOW",
    assignability: "CLIENT_ROLE",
    permittedScopes: ["CLIENT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["client-safe-projection"],
    activationStage: "R12",
  },
  {
    key: "client.report.view",
    surface: "CLIENT",
    risk: "LOW",
    assignability: "CLIENT_ROLE",
    permittedScopes: ["CLIENT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["client-safe-projection"],
    activationStage: "R12",
  },
  {
    key: "client.support.manage",
    surface: "CLIENT",
    risk: "HIGH",
    assignability: "CLIENT_ROLE",
    permittedScopes: ["CLIENT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit", "client-safe-projection"],
    activationStage: "R12",
  },
  {
    key: "client.task.complete",
    surface: "CLIENT",
    risk: "MEDIUM",
    assignability: "CLIENT_ROLE",
    permittedScopes: ["CLIENT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["client-safe-projection"],
    activationStage: "R12",
  },
  {
    key: "client.task.view",
    surface: "CLIENT",
    risk: "LOW",
    assignability: "CLIENT_ROLE",
    permittedScopes: ["CLIENT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["client-safe-projection"],
    activationStage: "R12",
  },
  {
    key: "client.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R6",
  },
  {
    key: "commercial.exception.approve",
    surface: "TEAM",
    risk: "CRITICAL",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["audit", "reason", "recent-auth", "MFA", "exact-version", "SoD"],
    activationStage: "R7",
  },
  {
    key: "company.edit",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R6",
  },
  {
    key: "company.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R6",
  },
  {
    key: "contact.edit",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R6",
  },
  {
    key: "contact.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R6",
  },
  {
    key: "contract.edit",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R7",
  },
  {
    key: "contract.send",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["audit", "exact-version"],
    activationStage: "R7",
  },
  {
    key: "contract.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R7",
  },
  {
    key: "dashboard.executive.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R5+",
  },
  {
    key: "deal.edit",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R6",
  },
  {
    key: "deal.manage",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit"],
    activationStage: "R6",
  },
  {
    key: "deal.move",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: [],
    activationStage: "R6",
  },
  {
    key: "deal.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R6",
  },
  {
    key: "department.manage",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit"],
    activationStage: "R5",
  },
  {
    key: "design.approve",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["audit", "exact-version", "SoD"],
    activationStage: "R9",
  },
  {
    key: "design.cover.edit",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["audit"],
    activationStage: "R9",
  },
  {
    key: "design.cover.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: [],
    activationStage: "R9",
  },
  {
    key: "design.layout.manage",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["audit"],
    activationStage: "R9",
  },
  {
    key: "distribution.campaign.manage",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit"],
    activationStage: "R10",
  },
  {
    key: "distribution.campaign.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R10",
  },
  {
    key: "distribution.dashboard.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R10",
  },
  {
    key: "distribution.launch",
    surface: "TEAM",
    risk: "CRITICAL",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["audit", "reason", "recent-auth", "MFA", "exact-version"],
    activationStage: "R10",
  },
  {
    key: "draft.edit",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R8",
  },
  {
    key: "draft.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R8",
  },
  {
    key: "editorial.approve",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["audit", "exact-version", "SoD"],
    activationStage: "R8",
  },
  {
    key: "editorial.dashboard.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R8",
  },
  {
    key: "editorial.review",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: [],
    activationStage: "R8",
  },
  {
    key: "editorial.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R8",
  },
  {
    key: "emailaccount.manage",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit"],
    activationStage: "R6",
  },
  {
    key: "event.agenda.manage",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit"],
    activationStage: "R8/R9",
  },
  {
    key: "event.dashboard.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R8/R9",
  },
  {
    key: "event.manage",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit"],
    activationStage: "R8/R9",
  },
  {
    key: "event.participant.manage",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit"],
    activationStage: "R8/R9",
  },
  {
    key: "event.registration.manage",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit"],
    activationStage: "R8/R9",
  },
  {
    key: "event.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R8/R9",
  },
  {
    key: "file.version",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R8",
  },
  {
    key: "file.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R8",
  },
  {
    key: "inbox.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R6",
  },
  {
    key: "integration.manage",
    surface: "TEAM",
    risk: "CRITICAL",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit", "reason", "recent-auth", "MFA"],
    activationStage: "R13",
  },
  {
    key: "invoice.edit",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R7",
  },
  {
    key: "invoice.issue",
    surface: "TEAM",
    risk: "CRITICAL",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["audit", "reason", "recent-auth", "MFA", "financial-evidence", "SoD"],
    activationStage: "R7",
  },
  {
    key: "invoice.send",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["audit"],
    activationStage: "R7",
  },
  {
    key: "invoice.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R7",
  },
  {
    key: "lead.discover",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R6",
  },
  {
    key: "lead.edit",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R6",
  },
  {
    key: "lead.enrich",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R6",
  },
  {
    key: "lead.extract.run",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R6",
  },
  {
    key: "lead.import.review",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: [],
    activationStage: "R6",
  },
  {
    key: "lead.list.manage",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit"],
    activationStage: "R6",
  },
  {
    key: "lead.qualify",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R6",
  },
  {
    key: "lead.review",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: [],
    activationStage: "R6",
  },
  {
    key: "lead.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R6",
  },
  {
    key: "magazine.dashboard.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R9",
  },
  {
    key: "magazine.proof.review",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: [],
    activationStage: "R9",
  },
  {
    key: "magazine.reader.publish",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["audit", "exact-version"],
    activationStage: "R9",
  },
  {
    key: "magazine.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R9",
  },
  {
    key: "meeting.edit",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R6",
  },
  {
    key: "meeting.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R6",
  },
  {
    key: "message.read",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R6",
  },
  {
    key: "message.send",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["audit"],
    activationStage: "R6",
  },
  {
    key: "notification.read.own",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R5+",
  },
  {
    key: "outreach.dashboard.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R6",
  },
  {
    key: "outreach.launch",
    surface: "TEAM",
    risk: "CRITICAL",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["audit", "reason", "recent-auth", "MFA", "exact-version"],
    activationStage: "R6",
  },
  {
    key: "outreach.prepare",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: [],
    activationStage: "R6",
  },
  {
    key: "package.manage",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit"],
    activationStage: "R7",
  },
  {
    key: "payment.reconcile",
    surface: "TEAM",
    risk: "CRITICAL",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["audit", "reason", "recent-auth", "MFA", "financial-evidence", "SoD"],
    activationStage: "R7",
  },
  {
    key: "payment.refund",
    surface: "TEAM",
    risk: "CRITICAL",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["audit", "reason", "recent-auth", "MFA", "financial-evidence", "SoD"],
    activationStage: "R7",
  },
  {
    key: "payment.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["financial-evidence", "SoD"],
    activationStage: "R7",
  },
  {
    key: "permission.manage",
    surface: "TEAM",
    risk: "CRITICAL",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit", "reason", "recent-auth", "MFA", "no-self", "delegation-ceiling", "optimistic-concurrency"],
    activationStage: "R5",
  },
  {
    key: "podcast.dashboard.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R8/R9",
  },
  {
    key: "podcast.episode.edit",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R8/R9",
  },
  {
    key: "podcast.episode.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R8/R9",
  },
  {
    key: "podcast.guest.manage",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit"],
    activationStage: "R8/R9",
  },
  {
    key: "podcast.review",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: [],
    activationStage: "R8/R9",
  },
  {
    key: "podcast.schedule.manage",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit"],
    activationStage: "R8/R9",
  },
  {
    key: "profile.update.own",
    surface: "SELF_TEAM",
    risk: "MEDIUM",
    assignability: "SELF_ONLY",
    permittedScopes: ["NONE", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R3",
  },
  {
    key: "project.activity.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R8",
  },
  {
    key: "project.assign",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["audit"],
    activationStage: "R8",
  },
  {
    key: "project.create",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R8",
  },
  {
    key: "project.manage",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit"],
    activationStage: "R8",
  },
  {
    key: "project.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R8",
  },
  {
    key: "proposal.approve",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["audit", "exact-version", "SoD"],
    activationStage: "R6",
  },
  {
    key: "proposal.edit",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R6",
  },
  {
    key: "proposal.send",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["audit", "exact-version"],
    activationStage: "R6",
  },
  {
    key: "proposal.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R6",
  },
  {
    key: "publication.publish",
    surface: "TEAM",
    risk: "CRITICAL",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["audit", "reason", "recent-auth", "MFA", "exact-version"],
    activationStage: "R9",
  },
  {
    key: "publish.dashboard.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["exact-version"],
    activationStage: "R9",
  },
  {
    key: "publish.execute",
    surface: "TEAM",
    risk: "CRITICAL",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["audit", "reason", "recent-auth", "MFA", "exact-version"],
    activationStage: "R9",
  },
  {
    key: "publish.queue.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["exact-version"],
    activationStage: "R9",
  },
  {
    key: "publish.schedule",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["audit", "exact-version"],
    activationStage: "R9",
  },
  {
    key: "questionnaire.edit",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R8",
  },
  {
    key: "questionnaire.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R8",
  },
  {
    key: "renewal.edit",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R11",
  },
  {
    key: "renewal.manage",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit"],
    activationStage: "R11",
  },
  {
    key: "renewal.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R11",
  },
  {
    key: "reply.assign",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["audit"],
    activationStage: "R6",
  },
  {
    key: "reply.handle",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R6",
  },
  {
    key: "reply.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R6",
  },
  {
    key: "report.approve",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["audit", "exact-version", "SoD"],
    activationStage: "R11",
  },
  {
    key: "report.create",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R11",
  },
  {
    key: "report.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R11",
  },
  {
    key: "role.manage",
    surface: "TEAM",
    risk: "CRITICAL",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit", "reason", "recent-auth", "MFA", "no-self", "delegation-ceiling", "optimistic-concurrency"],
    activationStage: "R5",
  },
  {
    key: "sequence.manage",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit"],
    activationStage: "R6",
  },
  {
    key: "settings.manage",
    surface: "TEAM",
    risk: "CRITICAL",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit", "reason", "recent-auth", "MFA"],
    activationStage: "R13",
  },
  {
    key: "source.manage",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit"],
    activationStage: "R6",
  },
  {
    key: "staff.auth.mfa",
    surface: "SELF_TEAM",
    risk: "MEDIUM",
    assignability: "SELF_ONLY",
    permittedScopes: ["NONE", "OWN"],
    requiresFieldPolicy: false,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R3",
  },
  {
    key: "staff.auth.recover",
    surface: "SELF_TEAM",
    risk: "MEDIUM",
    assignability: "SELF_ONLY",
    permittedScopes: ["NONE", "OWN"],
    requiresFieldPolicy: false,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R3",
  },
  {
    key: "staff.auth.signin",
    surface: "SELF_TEAM",
    risk: "HIGH",
    assignability: "SELF_ONLY",
    permittedScopes: ["NONE", "OWN"],
    requiresFieldPolicy: false,
    requiresWorkflowPolicy: true,
    obligations: ["audit"],
    activationStage: "R3",
  },
  {
    key: "staff.invite.accept",
    surface: "SELF_TEAM",
    risk: "MEDIUM",
    assignability: "SELF_ONLY",
    permittedScopes: ["NONE", "OWN"],
    requiresFieldPolicy: false,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R3",
  },
  {
    key: "task.edit",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R8",
  },
  {
    key: "task.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R8",
  },
  {
    key: "team.manage",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit"],
    activationStage: "R5",
  },
  {
    key: "team.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R5",
  },
  {
    key: "template.manage",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit"],
    activationStage: "R6+",
  },
  {
    key: "video.dashboard.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R8/R9",
  },
  {
    key: "video.edit",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R8/R9",
  },
  {
    key: "video.publish.prepare",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: ["audit", "exact-version"],
    activationStage: "R8/R9",
  },
  {
    key: "video.review",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: [],
    activationStage: "R8/R9",
  },
  {
    key: "video.schedule.manage",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit"],
    activationStage: "R8/R9",
  },
  {
    key: "video.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R8/R9",
  },
  {
    key: "workflow.move",
    surface: "TEAM",
    risk: "MEDIUM",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: true,
    obligations: [],
    activationStage: "R8",
  },
  {
    key: "workflow.template.manage",
    surface: "TEAM",
    risk: "HIGH",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: ["audit"],
    activationStage: "R8",
  },
  {
    key: "workspace.mywork.view",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R5+",
  },
  {
    key: "workspace.search",
    surface: "TEAM",
    risk: "LOW",
    assignability: "TEAM_ROLE",
    permittedScopes: ["ORG", "DEPT", "ASN", "OWN", "READ"],
    requiresFieldPolicy: true,
    requiresWorkflowPolicy: false,
    obligations: [],
    activationStage: "R5+",
  }
] as const satisfies readonly PermissionDefinition[];

export type CanonicalPermissionKey =
  (typeof PERMISSION_DEFINITIONS)[number]["key"];

const permissionRegistry = new Map<CanonicalPermissionKey, PermissionDefinition<CanonicalPermissionKey>>(
  PERMISSION_DEFINITIONS.map((definition) => [
    definition.key,
    definition as PermissionDefinition<CanonicalPermissionKey>,
  ]),
);

if (permissionRegistry.size !== PERMISSION_DEFINITIONS.length) {
  throw new Error("Duplicate permission key in R5 canonical registry");
}

export const PERMISSION_REGISTRY: ReadonlyMap<
  CanonicalPermissionKey,
  PermissionDefinition<CanonicalPermissionKey>
> = permissionRegistry;

export function isCanonicalPermissionKey(
  value: string,
): value is CanonicalPermissionKey {
  return permissionRegistry.has(value as CanonicalPermissionKey);
}

export function getPermissionDefinition(
  key: CanonicalPermissionKey,
): PermissionDefinition<CanonicalPermissionKey> {
  const definition = permissionRegistry.get(key);
  if (!definition) {
    throw new Error(`Unknown canonical permission: ${key}`);
  }
  return definition;
}
