import { readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
const root=join(process.cwd(),"src/app/api/v1/r6");
function files(dir=root):Array<{path:string;source:string}>{return readdirSync(dir).flatMap(name=>{const path=join(dir,name);if(statSync(path).isDirectory())return files(path);return name==="route.ts"?[{path,source:readFileSync(path,"utf8")}]:[];});}
const comms=files().filter(x=>/\/(outreach\/(campaigns|sending-accounts|sequences)|inbox\/conversations|meetings)\//.test(x.path.replaceAll("\\","/")));
describe("R6 Communications whole HTTP surface falsification",()=>{
 it("classifies the expected human route inventory",()=>{const paths=comms.map(x=>x.path.replaceAll("\\","/"));for(const suffix of ["outreach/sending-accounts/route.ts","outreach/sending-accounts/[sendingAccountId]/route.ts","outreach/sequences/route.ts","outreach/sequences/[sequenceId]/route.ts","outreach/sequences/[sequenceId]/versions/route.ts","outreach/campaigns/route.ts","outreach/campaigns/[campaignId]/route.ts","outreach/campaigns/[campaignId]/transition/route.ts","outreach/campaigns/[campaignId]/launch/route.ts","inbox/conversations/route.ts","inbox/conversations/[conversationId]/route.ts","inbox/conversations/[conversationId]/assignment/route.ts","inbox/conversations/[conversationId]/notes/route.ts","meetings/route.ts","meetings/[meetingId]/route.ts","meetings/[meetingId]/reschedule/route.ts"])expect(paths.some(p=>p.endsWith(suffix))).toBe(true);});
 it("keeps every communications mutation behind same-origin enforcement",()=>{for(const {path,source} of comms){if(/export async function (POST|PATCH|PUT|DELETE)/.test(source))expect(source,path).toContain("requireSameOrigin");}});
 it("uses canonical R6 request resolution throughout the communications surface",()=>{for(const {path,source} of comms)expect(source,path).toContain("resolveR6TeamRequest");});
 it("does not accept browser-owned authority or provider truth fields",()=>{const joined=comms.map(x=>x.source).join("\n");for(const token of ["ownerOrganizationId","membershipId:","permissionKey: input","role: input","scope: input","externalEventId","providerThreadId","payloadHash","sentAt:","receivedAt:"])expect(joined).not.toContain(token);});
 it("keeps worker/provider commands unreachable from route imports",()=>{const joined=comms.map(x=>x.source).join("\n");for(const token of ["recordDeliveryEvent","evaluateDispatchSafety","buildCampaignApprovalSnapshotInTransaction","computeCampaignApprovalSnapshot","addCampaignRecipient","createConversation","recordMessage"])expect(joined).not.toContain(token);});
 it("requires trusted loaders before mutable existing-resource commands",()=>{for(const suffix of ["sending-accounts/[sendingAccountId]/route.ts","sequences/[sequenceId]/versions/route.ts","campaigns/[campaignId]/route.ts","conversations/[conversationId]/assignment/route.ts","meetings/[meetingId]/reschedule/route.ts"]){const x=comms.find(v=>v.path.replaceAll("\\","/").endsWith(suffix));expect(x?.source,suffix).toMatch(/loadR6[A-Za-z]+Resource/);expect(x?.source,suffix).toContain("authorizeTrustedHttpOperation");}});
 it("retains immutable sequence version and draft campaign gates",()=>{const seq=comms.find(x=>x.path.includes("[sequenceId]")&&x.path.includes("versions"))?.source??"";expect(seq).toContain("exactVersionMatches");const campaign=comms.find(x=>x.path.replaceAll("\\","/").endsWith("campaigns/[campaignId]/route.ts"))?.source??"";expect(campaign).toContain('resource.lifecycleState==="DRAFT"');expect(campaign).toContain("exactVersionMatches");});
 it("exposes meeting history only through authorized projection and no mutation route",()=>{const paths=comms.map(x=>x.path.replaceAll("\\","/"));expect(paths.some(p=>/meeting.*history.*route\.ts/i.test(p))).toBe(false);});
});