"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import {
  AlertCircle, Bell, BookOpen, Bookmark, CalendarDays, Check, CheckCircle2,
  ChevronDown, ChevronRight, CircleDollarSign, Clock3, CreditCard, Download,
  ExternalLink, Eye, FileText, Filter, Headphones, HelpCircle, Home, ImageIcon,
  Laptop, LockKeyhole, Mail, MessageSquare, MoreVertical, Newspaper,
  PauseCircle, PenLine, Play, Plus, ReceiptText, Search, Settings, Share2,
  ShieldCheck, Sparkles, Star, Ticket, Trash2, UserRound, Users, Video,
} from "lucide-react";
import styles from "./member-experience.module.css";

export type MemberPage =
  | "dashboard" | "saved" | "following" | "newsletters" | "subscription"
  | "billing" | "settings" | "notifications" | "magazines" | "events" | "support";

const memberNav = [
  ["dashboard", "Dashboard", "/my-perspective", Home],
  ["saved", "Saved Articles", "/my-perspective/saved", Bookmark],
  ["magazines", "My Magazines", "/my-perspective/magazines", BookOpen],
  ["following", "Following", "/my-perspective/following", UserRound],
  ["newsletters", "Newsletters", "/my-perspective/newsletters", Mail],
  ["media", "Podcasts & Videos", "/my-perspective/saved?type=media", Play],
  ["events", "Events", "/my-perspective/events", CalendarDays],
  ["briefings", "My Briefings", "/my-perspective/newsletters", Newspaper],
] as const;

const accountNav = [
  ["settings", "Profile & Settings", "/my-perspective/settings", UserRound],
  ["subscription", "Subscription", "/my-perspective/subscription", ShieldCheck],
  ["billing", "Billing & Payments", "/my-perspective/billing", CreditCard],
  ["notifications", "Notifications", "/my-perspective/notifications", Bell],
  ["support", "Help & Support", "/my-perspective/support", HelpCircle],
] as const;

const stories = [
  { title: "The Architects of Tomorrow", topic: "Business", image: "/images/articles/global-growth.png", meta: "8 min read", progress: 65 },
  { title: "AI Infrastructure Race: What Comes Next", topic: "Technology", image: "/images/articles/computing-infrastructure.png", meta: "12 min read", progress: 40 },
  { title: "Redefining Leadership in a New Era", topic: "Leadership", image: "/images/articles/board-governance.png", meta: "10 min read", progress: 75 },
  { title: "The Next Wave of Clean Energy Innovation", topic: "Economy", image: "/images/articles/future-leader.png", meta: "9 min read", progress: 35 },
  { title: "Global Markets Outlook Q2 2026", topic: "Global", image: "/images/articles/global-leadership.png", meta: "7 min read", progress: 20 },
];

const people = [
  { name: "Arjun Mehta", role: "Founder, Mehta Group", image: "/images/articles/arjun-mehta.png" },
  { name: "Daniel Kim", role: "Founder, Nexora Systems", image: "/images/articles/daniel-kim.png" },
  { name: "Meera Sinha", role: "Economist & Analyst", image: "/images/auth/member-access-hero.png" },
  { name: "Rohan Verma", role: "Author & Strategic Advisor", image: "/images/articles/marcus-chen.png" },
];

const magazineIssues = [
  { month: "May 2026", issue: "Issue 28", title: "AI & The Next Leap", image: "/images/articles/ai-infrastructure.png", progress: 65 },
  { month: "April 2026", issue: "Issue 27", title: "The Architects of Tomorrow", image: "/images/articles/global-growth.png", progress: 32 },
  { month: "March 2026", issue: "Issue 26", title: "India's Moment", image: "/images/home/editorial-skyline.png", progress: 18 },
  { month: "February 2026", issue: "Issue 25", title: "Capital & Innovation", image: "/images/articles/future-leader.png", progress: 100 },
  { month: "January 2026", issue: "Issue 24", title: "The Disruptors", image: "/images/articles/daniel-kim.png", progress: 0 },
];

function Section({ title, action, children, className = "" }: { title: string; action?: React.ReactNode; children: React.ReactNode; className?: string }) {
  return <section className={`${styles.card} ${className}`}><div className={styles.sectionHead}><h2>{title}</h2>{action}</div>{children}</section>;
}

function PageHeader({ eyebrow = "My Perspective", title, intro, actions }: { eyebrow?: string; title: string; intro: string; actions?: React.ReactNode }) {
  return <header className={styles.pageHeader}><div><p>{eyebrow}</p><h1>{title}</h1><span>{intro}</span></div>{actions && <div className={styles.headerActions}>{actions}</div>}</header>;
}

function PrimaryButton({ children, onClick, href, tone = "primary" }: { children: React.ReactNode; onClick?: () => void; href?: string; tone?: "primary" | "outline" | "dark" }) {
  const cn = `${styles.button} ${styles[tone]}`;
  return href ? <Link className={cn} href={href}>{children}</Link> : <button className={cn} onClick={onClick} type="button">{children}</button>;
}

function Toggle({ checked, onChange, label }: { checked: boolean; onChange: () => void; label: string }) {
  return <button aria-label={label} aria-pressed={checked} className={`${styles.toggle} ${checked ? styles.toggleOn : ""}`} onClick={onChange} type="button"><span /></button>;
}

function MemberSidebar({ page }: { page: MemberPage }) {
  const render = (item: readonly [string, string, string, React.ComponentType<{ size?: number }>]) => {
    const [key, label, href, Icon] = item;
    return <Link className={page === key ? styles.sideActive : ""} href={href} key={key}><Icon size={17} />{label}</Link>;
  };
  return <aside className={styles.sidebar}><p>My Perspective</p><nav>{memberNav.map(render)}</nav><div className={styles.sideDivider} /><b>Account</b><nav>{accountNav.map(render)}</nav><div className={styles.invite}><Users /><strong>Invite a friend</strong><span>Share thoughtful journalism and give a friend one month of Premium.</span><Link href="/signup">Invite now <ChevronRight /></Link></div></aside>;
}

function MemberShell({ page, children }: { page: MemberPage; children: React.ReactNode }) {
  return <div className={styles.memberRoot} id="member-experience"><div className={styles.memberLayout}><MemberSidebar page={page} /><div className={styles.memberMain}>{children}</div></div></div>;
}

function StatStrip({ items }: { items: { icon?: React.ReactNode; value: string; label: string }[] }) {
  return <div className={styles.statStrip}>{items.map((item) => <div key={`${item.value}-${item.label}`}>{item.icon}<strong>{item.value}</strong><span>{item.label}</span></div>)}</div>;
}

function StoryMini({ story }: { story: (typeof stories)[number] }) {
  return <Link className={styles.storyMini} href="/article/architects-of-tomorrow"><Image alt="" height={70} src={story.image} width={92} /><span><small>{story.topic}</small><strong>{story.title}</strong><em>{story.meta}</em></span></Link>;
}

function StoryCard({ story, saved = false }: { story: (typeof stories)[number]; saved?: boolean }) {
  return <article className={styles.storyCard}><div className={styles.media}><Image alt="" fill sizes="(max-width: 700px) 100vw, 240px" src={story.image} /><span>{story.topic}</span>{saved && <Bookmark className={styles.saveBadge} />}</div><div><h3>{story.title}</h3><p>Insightful reporting and analysis for readers shaping what comes next.</p><div className={styles.meta}><span>{story.meta}</span><span>{story.progress}%</span></div><div className={styles.progress}><i style={{ width: `${story.progress}%` }} /></div></div></article>;
}

function MagazineCard({ issue, compact = false }: { issue: (typeof magazineIssues)[number]; compact?: boolean }) {
  return <article className={`${styles.magazineCard} ${compact ? styles.magazineCompact : ""}`}><div className={styles.magCover}><Image alt="" fill sizes="180px" src={issue.image} /><div><small>The</small><b>Perspective.</b><span>{issue.title}</span></div></div><p>{issue.month}</p><h3>{issue.title}</h3><small>{issue.issue}</small>{!compact && <><div className={styles.progress}><i style={{ width: `${issue.progress}%` }} /></div><PrimaryButton href="/magazine/read/august-2026" tone={issue.progress ? "primary" : "outline"}>{issue.progress === 100 ? "Read again" : issue.progress ? "Continue reading" : "Read issue"}</PrimaryButton></>}</article>;
}

function DashboardPage() {
  return <MemberShell page="dashboard"><div className={styles.dashboardGrid}><div className={styles.dashboardBody}>
    <section className={styles.welcome}><div><p>Welcome back</p><h1>Good Evening, Vaishnav.</h1><span>Your stories, magazines, people and ideas—all in one place.</span></div><PrimaryButton tone="outline"><Settings size={16} /> Customize my feed</PrimaryButton></section>
    <div className={styles.threeGrid}>
      <Section title="Continue reading" action={<Link href="/my-perspective/saved">View all</Link>}><div className={styles.continueFeature}><Image alt="A city at sunset" fill src={stories[0].image} /><div><small>Business</small><h3>The Architects of Tomorrow</h3><p>Visionaries building a better future</p><Link href="/article/architects-of-tomorrow">Continue reading <ChevronRight /></Link></div></div></Section>
      <Section title="Saved stories" action={<Link href="/my-perspective/saved">View all</Link>}>{stories.slice(1,4).map((s) => <StoryMini key={s.title} story={s} />)}</Section>
      <Section title="Recommended for you" action={<Link href="/latest">View all</Link>}>{stories.slice(2,5).map((s) => <StoryMini key={s.title} story={s} />)}</Section>
    </div>
    <div className={styles.dashboardWide}><Section title="My magazine issues" action={<Link href="/my-perspective/magazines">View all</Link>}><div className={styles.magRow}>{magazineIssues.map((i) => <MagazineCard compact issue={i} key={i.month} />)}</div></Section></div>
    <div className={styles.twoGrid}><Section title="Followed topics" action={<Link href="/my-perspective/following">Manage</Link>}><div className={styles.pills}>{["Business", "Technology", "Leadership", "Economy", "Startups", "AI & Data", "Markets", "Sustainability"].map((x) => <span key={x}>{x}</span>)}</div><Link className={styles.textLink} href="/my-perspective/following"><Plus /> Add topic</Link></Section><Section title="Followed authors & leaders" action={<Link href="/my-perspective/following">View all</Link>}>{people.slice(0,3).map((p) => <PersonRow key={p.name} person={p} />)}</Section></div>
    <div className={styles.promoGrid}><Promo icon={<Mail />} title="Today's briefing" text="Your Morning Briefing is ready, with stories handpicked for you." href="/newsletter" action="Read briefing" /><Promo icon={<Settings />} title="Personalize your experience" text="Tune content, briefings and notifications around your interests." href="/my-perspective/newsletters" action="Go to preferences" /><Promo icon={<Star />} title="Member benefits" text="Premium stories, every issue, events and an ad-light reading experience." href="/my-perspective/subscription" action="View benefits" /></div>
  </div><aside className={styles.dashboardRail}><section className={styles.memberCard}><small>Membership</small><h2>Premium Member</h2><p>Annual Premium · Member since May 2025</p><PrimaryButton href="/my-perspective/subscription" tone="outline">Manage subscription</PrimaryButton></section><Section title="Your reading activity"><StatStrip items={[{ value: "14", label: "Articles read" }, { value: "2h 45m", label: "Reading time" }, { value: "5", label: "Topics followed" }]} /></Section><Section title="Upcoming events"><EventMini date="22" month="May" title="Global Leadership Summit 2026" /><EventMini date="05" month="Jun" title="Future of Work Conference" /></Section><Section title="Latest podcast episodes">{stories.slice(1,3).map((s) => <StoryMini key={s.title} story={s} />)}</Section></aside></div></MemberShell>;
}

function Promo({ icon, title, text, href, action }: { icon: React.ReactNode; title: string; text: string; href: string; action: string }) { return <article className={styles.promo}>{icon}<div><strong>{title}</strong><p>{text}</p><Link href={href}>{action} <ChevronRight /></Link></div></article>; }
function EventMini({ date, month, title }: { date: string; month: string; title: string }) { return <Link className={styles.eventMini} href="/events/leadership-summit-2026"><span><small>{month}</small>{date}</span><div><strong>{title}</strong><p>New Delhi · Registration open</p></div><ChevronRight /></Link>; }
function PersonRow({ person, controls = false }: { person: (typeof people)[number]; controls?: boolean }) { return <div className={styles.personRow}><Image alt="" height={46} src={person.image} width={46} /><span><strong>{person.name}</strong><small>{person.role}</small></span>{controls && <><button aria-label={`Notifications for ${person.name}`} type="button"><Bell /></button><button aria-label={`More options for ${person.name}`} type="button"><MoreVertical /></button></>}</div>; }

function SavedPage() {
  const [query, setQuery] = useState(""); const [type, setType] = useState("All"); const [selected, setSelected] = useState<string[]>([]);
  const filtered = stories.filter((s) => (type === "All" || s.topic === type) && s.title.toLowerCase().includes(query.toLowerCase()));
  return <MemberShell page="saved"><div className={styles.contentWithRail}><div>
    <PageHeader title="Saved Articles & Reading List" intro="Everything you wanted to come back to—organized in one place." actions={<><PrimaryButton tone="outline"><CheckCircle2 /> Select all</PrimaryButton><PrimaryButton tone="outline">Bulk actions <ChevronDown /></PrimaryButton></>} />
    <StatStrip items={[{ icon: <Bookmark />, value: "42", label: "Saved items" }, { icon: <Eye />, value: "18", label: "Unread" }, { icon: <BookOpen />, value: "7", label: "Magazine stories" }, { icon: <Headphones />, value: "8", label: "Podcasts" }, { icon: <Video />, value: "5", label: "Videos" }]} />
    <div className={styles.filterBar}><label><Search /><input aria-label="Search saved items" onChange={(e) => setQuery(e.target.value)} placeholder="Search saved items…" value={query} /></label><select aria-label="Saved item type" onChange={(e) => setType(e.target.value)} value={type}><option>All</option><option>Business</option><option>Technology</option><option>Leadership</option></select><select aria-label="Date saved"><option>All time</option><option>This week</option><option>This month</option></select><button onClick={() => { setQuery(""); setType("All"); }} type="button">Clear all</button></div>
    <div className={styles.chipTabs}>{["All", "Articles", "Magazine Stories", "Podcasts", "Videos", "Authors / People"].map((x) => <button className={x === "All" ? styles.chipActive : ""} key={x} type="button">{x}</button>)}</div>
    <div className={styles.sectionLabel}><h2>Continue reading</h2><Link href="/latest">View all</Link></div><div className={styles.storyGrid}>{filtered.map((s) => <StoryCard key={s.title} saved story={s} />)}</div>
    <Section title="All saved items"><div className={styles.tableWrap}><table><thead><tr><th /><th>Type</th><th>Title</th><th>Topic</th><th>Saved on</th><th>Progress</th><th>Actions</th></tr></thead><tbody>{stories.map((s, i) => <tr key={s.title}><td><input aria-label={`Select ${s.title}`} checked={selected.includes(s.title)} onChange={() => setSelected((old) => old.includes(s.title) ? old.filter((x) => x !== s.title) : [...old, s.title])} type="checkbox" /></td><td>{i % 3 === 0 ? "Magazine" : i % 2 ? "Article" : "Podcast"}</td><td><strong>{s.title}</strong><small>Independent analysis and perspectives.</small></td><td>{s.topic}</td><td>{i < 2 ? "Today" : `May ${11 - i}, 2026`}</td><td>{s.progress}%</td><td><button aria-label="Share"><Share2 /></button><button aria-label="Remove"><Trash2 /></button></td></tr>)}</tbody></table></div></Section>
  </div><aside className={styles.rightRail}><Section title="Reading list overview"><StatStrip items={[{ value: "18", label: "Unread" }, { value: "12h 45m", label: "Reading time" }, { value: "5", label: "Completed" }]} /><PrimaryButton href="/my-perspective" tone="outline">View reading activity</PrimaryButton></Section><Section title="Collections">{[["Business & Markets",12],["Technology & Innovation",11],["Leadership & People",8],["Global Affairs",7]].map(([x,n]) => <div className={styles.lineItem} key={x}><span><BookOpen />{x}</span><b>{n}</b></div>)}<Link className={styles.textLink} href="#"><Plus /> Create collection</Link></Section><Section title="Saved magazine issues"><div className={styles.magRow}>{magazineIssues.slice(0,3).map((i) => <MagazineCard compact issue={i} key={i.month} />)}</div></Section><Section title="Based on your saves">{stories.slice(0,3).map((s) => <StoryMini key={s.title} story={s} />)}</Section></aside></div></MemberShell>;
}

function FollowingPage() {
  const [tab, setTab] = useState("Topics"); const [followed, setFollowed] = useState(["Economy", "Innovation"]);
  const topics = ["Business", "Technology", "Leadership", "Sustainability", "Global Affairs"];
  return <MemberShell page="following"><div className={styles.contentWithRail}><div><PageHeader title="Topics, Authors & People You Follow" intro="Shape your feed around the ideas and voices that matter most to you." actions={<><PrimaryButton tone="outline"><Sparkles /> Discover more</PrimaryButton><PrimaryButton tone="outline"><Bell /> Manage notifications</PrimaryButton></>} /><div className={styles.tabs}>{["Topics","Authors","People / Leaders","Companies"].map((x) => <button className={tab === x ? styles.tabActive : ""} key={x} onClick={() => setTab(x)}>{x}</button>)}</div><div className={styles.filterBar}><label><Search /><input aria-label="Search following" placeholder={`Search followed ${tab.toLowerCase()}…`} /></label><select><option>All categories</option></select><select><option>Recently followed</option></select></div>
    <div className={styles.followTopicGrid}>{topics.map((topic, i) => <article key={topic}><div className={styles.topicImage}><Image alt="" fill src={stories[i].image} /></div><h3>{topic}</h3><p>{54 + i * 14} articles this week</p><div><span><Check /> Following</span><button aria-label={`${topic} notifications`}><Bell /></button></div></article>)}</div>
    <div className={styles.threeGrid}><Section title="Followed authors" action={<Link href="/authors">View all</Link>}>{people.map((p) => <PersonRow controls key={p.name} person={p} />)}</Section><Section title="Followed people / leaders" action={<Link href="/search?type=people">View all</Link>}>{people.slice().reverse().map((p) => <PersonRow controls key={p.name} person={p} />)}</Section><Section title="Latest updates from who you follow">{stories.slice(0,3).map((s) => <StoryMini key={s.title} story={s} />)}<PrimaryButton href="/latest" tone="outline">Go to my feed</PrimaryButton></Section></div>
    <div className={styles.sectionLabel}><h2>You might also like to follow</h2></div><div className={styles.recommendRow}>{["Economy", "Startups", "AI & Data", "Geopolitics", "Innovation", "Health & Bio"].map((x) => <article key={x}><Sparkles /><strong>{x}</strong><small>{58 + x.length * 4}K followers</small><button onClick={() => setFollowed((v) => v.includes(x) ? v.filter((a) => a !== x) : [...v, x])}><Plus /> {followed.includes(x) ? "Following" : "Follow"}</button></article>)}</div>
  </div><aside className={styles.rightRail}><Section title="Your following summary">{[["Topics",12],["Authors",8],["People / Leaders",6],["Companies",4]].map(([x,n]) => <div className={styles.lineItem} key={x}><span><UserRound />{x}</span><b>{n}</b></div>)}<div className={styles.totalLine}><strong>Total following</strong><b>30</b></div></Section><Promo icon={<Bell />} title="Notification settings" text="Customize how you receive updates from what you follow." href="/my-perspective/notifications" action="Manage settings" /><Promo icon={<Mail />} title="Personalized briefing" text="Get the best of what you follow in your daily briefing." href="/my-perspective/newsletters" action="Manage briefing" /><Promo icon={<Sparkles />} title="Discover more" text="Find more topics, authors and leaders that match your interests." href="/search" action="Explore now" /></aside></div></MemberShell>;
}

const briefings = [
  { title: "Daily Briefing", text: "Top stories, must-know insights and editor's picks.", frequency: "Daily at 7:00 AM", image: "/images/home/editorial-skyline.png" },
  { title: "Business Briefing", text: "Markets, companies, economy and business leaders.", frequency: "Daily at 8:00 AM", image: "/images/articles/global-growth.png" },
  { title: "Leadership Briefing", text: "Leadership strategies, interviews and expert opinions.", frequency: "Twice weekly", image: "/images/articles/board-governance.png" },
  { title: "Technology Briefing", text: "Emerging tech, innovation, startups and AI.", frequency: "Weekly on Monday", image: "/images/articles/ai-infrastructure.png" },
  { title: "Markets Briefing", text: "Market trends, analysis and investment insights.", frequency: "Daily at 6:30 PM", image: "/images/articles/global-leadership.png" },
  { title: "Magazine Briefing", text: "New issues, features and exclusive stories.", frequency: "Weekly on Friday", image: "/images/newsletter/briefings-hero.png" },
  { title: "Events Briefing", text: "Invitations, highlights and upcoming events.", frequency: "Weekly on Wednesday", image: "/images/events/leadership-summit-hero.png" },
  { title: "Podcast Updates", text: "New episodes, special series and recommendations.", frequency: "Weekly on Saturday", image: "/images/podcasts/naveen-malhotra-hero-clean.webp" },
];

function NewsletterPage() {
  const [active, setActive] = useState(briefings.map((x) => x.title)); const [paused, setPaused] = useState(false); const [saved, setSaved] = useState(false); const [format, setFormat] = useState("Standard");
  return <MemberShell page="newsletters"><div className={styles.contentWithRail}><div><PageHeader title="Newsletter & Briefing Preferences" intro="Choose what reaches your inbox, how often it arrives, and which topics matter most." actions={<><PrimaryButton onClick={() => setPaused((x) => !x)} tone="outline"><PauseCircle /> {paused ? "Resume all emails" : "Pause all emails"}</PrimaryButton><PrimaryButton onClick={() => { setSaved(true); setTimeout(() => setSaved(false), 2400); }}><Check /> {saved ? "Preferences saved" : "Save preferences"}</PrimaryButton></>} /><StatStrip items={[{ icon: <Newspaper />, value: `${active.length}`, label: "Active briefings" }, { icon: <Bell />, value: "3", label: "Topic alerts" }, { icon: <Clock3 />, value: "7:00 AM", label: "Daily delivery" }, { icon: <Mail />, value: "vaishnav@example.com", label: "Primary email" }]} />
    <div className={styles.sectionLabel}><h2>Your subscribed briefings</h2></div><div className={styles.briefingGrid}>{briefings.map((b) => { const on = active.includes(b.title) && !paused; return <article className={styles.briefingCard} key={b.title}><div className={styles.briefingImage}><Image alt="" fill src={b.image} /><Newspaper /></div><h3>{b.title}</h3><p>{b.text}</p><div><select aria-label={`${b.title} frequency`} defaultValue={b.frequency}><option>{b.frequency}</option><option>Weekly</option><option>Monthly</option></select><Toggle checked={on} label={`Toggle ${b.title}`} onChange={() => setActive((old) => old.includes(b.title) ? old.filter((x) => x !== b.title) : [...old, b.title])} /></div><button type="button">Edit <Settings /></button></article>; })}<article className={`${styles.briefingCard} ${styles.discoverBriefing}`}><Plus /><h3>Discover more briefings</h3><p>Explore more newsletters based on your interests.</p><PrimaryButton href="/newsletter" tone="outline">Explore now</PrimaryButton></article></div>
    <div className={styles.sectionLabel}><h2>Topic alerts</h2></div><div className={styles.alertChips}>{["Artificial Intelligence · Daily", "Global Economy · Weekly", "Sustainability · Weekly"].map((x) => <span key={x}>{x}<Bell /></span>)}<button><Plus /> Add new alert</button></div>
    <div className={styles.sectionLabel}><h2>Recommended for you</h2></div><div className={styles.recommendStories}>{["Policy & Politics Briefing", "World Affairs Briefing", "Health & Science Briefing", "Climate Briefing"].map((x, i) => <article key={x}><Image alt="" height={70} src={stories[i].image} width={100} /><div><strong>{x}</strong><p>Curated reporting and context for busy readers.</p><button>+ Subscribe</button></div></article>)}</div>
  </div><aside className={styles.rightRail}><Section title="Delivery preferences"><label className={styles.formLabel}>Email frequency<select><option>Daily</option><option>Weekly</option></select></label><label className={styles.formLabel}>Preferred delivery time<select><option>7:00 AM</option><option>8:00 AM</option></select></label><span className={styles.formLabel}>Email format</span><div className={styles.segmented}>{["Standard","Compact","Text only"].map((x) => <button className={format === x ? styles.segmentActive : ""} key={x} onClick={() => setFormat(x)}>{x}</button>)}</div><label className={styles.checkLine}><input defaultChecked type="checkbox" /> Include featured partner content</label></Section><Section title="Preview" action={<Link href="/newsletter">View full sample</Link>}><div className={styles.emailPreview}><b>The Perspective.</b><small>Daily Briefing · August 13, 2026</small><h3>The Architects of Tomorrow</h3><p>Visionaries building a better future.</p><StoryMini story={stories[3]} /></div></Section><Section title="Manage email address"><p className={styles.bodyText}>Primary email<br /><strong>vaishnav@example.com</strong> <em className={styles.success}>Verified</em></p><PrimaryButton tone="outline">Change email</PrimaryButton></Section><Promo icon={<ShieldCheck />} title="Privacy & control" text="Unsubscribe anytime or manage preferences with ease." href="/search?q=privacy" action="View email privacy policy" /></aside></div></MemberShell>;
}

function SubscriptionPage() {
  const [plan, setPlan] = useState("Premium");
  const plans = [
    { name: "Reader", price: "$0", intro: "Core news and selected stories.", features: ["Daily news coverage", "Weekly newsletter", "Limited archive access"] },
    { name: "Premium", price: "$19", intro: "Complete access to premium content.", features: ["All Reader benefits", "Premium magazine editions", "Full archive access", "Ad-light experience", "Member events"] },
    { name: "Patron", price: "$49", intro: "For readers who want to go deeper.", features: ["All Premium benefits", "Early access", "Exclusive reports", "Private roundtables"] },
  ];
  return <MemberShell page="subscription"><div className={styles.contentWithRail}><div><PageHeader title="Subscription Management" intro="Manage your membership, benefits, renewal and access in one place." /><section className={styles.planOverview}><div className={styles.premiumBadge}><small>The Perspective.</small><b>Premium member</b><strong>$19 <em>/ month</em></strong><span>Active</span></div><StatStrip items={[{ icon: <UserRound />, value: "Active", label: "Membership status" }, { icon: <CalendarDays />, value: "May 12, 2024", label: "Member since" }, { icon: <CalendarDays />, value: "Sep 12, 2026", label: "Next billing date" }, { icon: <Clock3 />, value: "Monthly", label: "Billing cycle" }]} /><div className={styles.planActions}><PrimaryButton>Manage plan</PrimaryButton><PrimaryButton tone="outline">Change billing cycle</PrimaryButton><button className={styles.dangerText}>Cancel subscription</button></div></section>
    <Section title="Your premium benefits"><div className={styles.benefitRow}>{[[BookOpen,"Premium editions"],[Laptop,"Digital reader"],[LockKeyhole,"Premium archive"],[Eye,"Ad-light experience"],[Star,"Exclusive content"],[CalendarDays,"Member events"]].map(([Icon,label]) => { const I = Icon as React.ComponentType<{size?: number}>; return <div key={label as string}><I size={23} /><strong>{label as string}</strong><span>Included with your membership</span></div>; })}</div></Section>
    <div className={styles.planChoice}>{plans.map((p) => <article className={plan === p.name ? styles.planSelected : ""} key={p.name}>{p.name === "Premium" && <span className={styles.ribbon}>Most popular</span>}<small>{p.name} member</small><h2>{p.price}<em>/ month</em></h2><p>{p.intro}</p><ul>{p.features.map((x) => <li key={x}><Check />{x}</li>)}</ul><PrimaryButton onClick={() => setPlan(p.name)} tone={p.name === "Patron" ? "dark" : p.name === plan ? "primary" : "outline"}>{p.name === plan ? "Current plan" : "Choose plan"}</PrimaryButton></article>)}</div>
    <div className={styles.statusRow}>{[["Active","Your membership is active.","success"],["Trial","Trial ends in 6 days.","info"],["Payment due","Update payment method.","warning"],["Past due","Access may be interrupted.","danger"],["Cancelled","Ends after billing cycle.","muted"],["Expired","Renew to continue.","muted"]].map(([a,b,c]) => <article data-tone={c} key={a}><CheckCircle2 /><strong>{a}</strong><span>{b}</span></article>)}</div>
  </div><aside className={styles.rightRail}><Section title="Current billing summary">{[["Plan",`${plan} Member`],["Billing cycle","Monthly"],["Amount",plan === "Patron" ? "$49.00" : plan === "Reader" ? "$0.00" : "$19.00"],["Next billing date","Sep 12, 2026"],["Payment method","Visa •••• 4242"]].map(([x,y]) => <div className={styles.lineItem} key={x}><span>{x}</span><b>{y}</b></div>)}<Link className={styles.textLink} href="/my-perspective/billing">Update payment method <ChevronRight /></Link></Section><Promo icon={<Headphones />} title="Need help?" text="Our membership team can help with any question." href="/my-perspective/support" action="Contact support" /><Section title="Frequently asked questions">{["How do I change my plan?","Can I pause my subscription?","How do I cancel?","What payment methods do you accept?","When will I be charged again?"].map((x) => <button className={styles.faqRow} key={x}>{x}<ChevronRight /></button>)}</Section></aside></div></MemberShell>;
}

const transactions = [
  ["Aug 12, 2026","INV-2026-0812","Aug 12 – Sep 11, 2026","$19.00","Paid"],
  ["Jul 12, 2026","INV-2026-0712","Jul 12 – Aug 11, 2026","$19.00","Paid"],
  ["Jun 12, 2026","INV-2026-0612","Jun 12 – Jul 11, 2026","$19.00","Paid"],
  ["May 12, 2026","INV-2026-0512","May 12 – Jun 11, 2026","$19.00","Paid"],
  ["Apr 12, 2026","INV-2026-0412","Apr 12 – May 11, 2026","$19.00","Paid"],
  ["Mar 12, 2026","INV-2026-0312","Mar 12 – Apr 11, 2026","$19.00","Failed"],
  ["Feb 12, 2026","INV-2026-0212","Feb 12 – Mar 11, 2026","$19.00","Paid"],
];

function BillingPage() {
  const [tab, setTab] = useState("Invoices & Payments");
  return <MemberShell page="billing"><div className={styles.contentWithRail}><div><PageHeader title="Billing & Payment History" intro="Review payments, invoices, billing details and payment methods." /><div className={styles.summaryCards}><Summary icon={<Star />} title="Current plan" value="Premium Member" text="$19.00 / month" /><Summary icon={<CalendarDays />} title="Next charge" value="$19.00" text="on Sep 12, 2026" /><Summary icon={<CreditCard />} title="Payment method" value="VISA •••• 4242" text="Expires 06/2028" /><Summary icon={<CheckCircle2 />} title="Billing status" value="Up to date" text="No payments due" success /></div><div className={styles.tabs}>{["Invoices & Payments","Payment Methods","Billing Details","Tax & Receipts"].map((x) => <button className={tab === x ? styles.tabActive : ""} key={x} onClick={() => setTab(x)}>{x}</button>)}</div>
    <Section title="Transaction history" action={<button className={styles.textButton}><Download /> Download all invoices</button>}><div className={styles.tableWrap}><table><thead><tr><th>Date</th><th>Invoice #</th><th>Description</th><th>Billing period</th><th>Amount</th><th>Status</th><th>Payment</th><th>Actions</th></tr></thead><tbody>{transactions.map((r) => <tr key={r[1]}><td>{r[0]}</td><td>{r[1]}</td><td>Premium membership</td><td>{r[2]}</td><td>{r[3]}</td><td><span className={r[4] === "Paid" ? styles.statusPaid : styles.statusFailed}>{r[4] === "Paid" ? <CheckCircle2 /> : <AlertCircle />}{r[4]}</span></td><td>Visa •••• 4242</td><td><button aria-label={`Download ${r[1]}`}><Download /></button><button aria-label={`Receipt ${r[1]}`}><ReceiptText /></button></td></tr>)}</tbody></table></div></Section>
    <div className={styles.fourGrid}><InfoCard icon={<CreditCard />} title="Payment method" lines={["Visa ending in 4242","Expires 06/2028"]} action="Update payment method" /><InfoCard icon={<Home />} title="Billing address" lines={["Vaishnav Sawant","Mumbai, Maharashtra, India"]} action="Update billing address" /><InfoCard icon={<CircleDollarSign />} title="Tax information" lines={["GSTIN: 27ABCDE1234F1Z5","Business type: Individual"]} action="Update tax information" /><InfoCard icon={<Mail />} title="Invoice preferences" lines={["Email invoices to","vaishnav@example.com"]} action="Manage preferences" /></div>
  </div><aside className={styles.rightRail}><Section title="Payment overview">{[["Current balance","$0.00"],["Last payment","Aug 12, 2026 · $19.00"],["Total paid this year","$152.00"],["Currency","USD"],["Billing email","vaishnav@example.com"]].map(([x,y]) => <div className={styles.lineItem} key={x}><span>{x}</span><b>{y}</b></div>)}<PrimaryButton tone="outline">View billing summary</PrimaryButton></Section><article className={`${styles.callout} ${styles.calloutDanger}`}><AlertCircle /><div><h3>Payment failed</h3><p>We could not process your payment on Mar 12, 2026. Update your method to avoid interruption.</p><PrimaryButton>Update payment method</PrimaryButton></div></article><Promo icon={<Headphones />} title="Need help?" text="Our support team can help with billing and payment queries." href="/my-perspective/support" action="Contact billing support" /></aside></div></MemberShell>;
}

function Summary({ icon, title, value, text, success }: { icon: React.ReactNode; title: string; value: string; text: string; success?: boolean }) { return <article className={styles.summaryCard}>{icon}<small>{title}</small><strong className={success ? styles.success : ""}>{value}</strong><span>{text}</span></article>; }
function InfoCard({ icon, title, lines, action }: { icon: React.ReactNode; title: string; lines: string[]; action: string }) { return <article className={styles.infoCard}>{icon}<div><h3>{title}</h3>{lines.map((x) => <p key={x}>{x}</p>)}<button>{action} <ChevronRight /></button></div></article>; }

function SettingsPage() {
  const [tab, setTab] = useState("Profile"); const [visibility, setVisibility] = useState("Members only"); const [saved, setSaved] = useState(false);
  return <MemberShell page="settings"><div className={styles.contentWithRail}><div><PageHeader title="Profile & Account Settings" intro="Manage your identity, security, personal details and account preferences." actions={<><PrimaryButton onClick={() => { setSaved(true); setTimeout(() => setSaved(false), 2000); }}><PenLine /> {saved ? "Profile updated" : "Update profile"}</PrimaryButton><PrimaryButton tone="outline"><LockKeyhole /> Change password</PrimaryButton></>} /><div className={styles.tabs}>{["Profile","Account","Security","Privacy","Connected accounts"].map((x) => <button className={tab === x ? styles.tabActive : ""} key={x} onClick={() => setTab(x)}>{x}</button>)}</div>
    <section className={styles.profileHero}><div className={styles.avatar}><Image alt="Vaishnav Sawant" fill src="/images/articles/marcus-chen.png" /><button aria-label="Change photo"><ImageIcon /></button></div><div><h2>Vaishnav Sawant <span>Premium member</span></h2><p>✉ vaishnav@example.com <em className={styles.success}>Verified</em></p><p>+91 98765 43210 <em className={styles.success}>Verified</em></p><small>Member since May 12, 2024 · Member ID: TPS-124578</small></div><p>Passionate about business, technology, leadership and global affairs. I rely on The Perspective for deep insights and thoughtful analysis.</p><dl><div><dt>Country / Region</dt><dd>India</dd></div><div><dt>Language</dt><dd>English</dd></div><div><dt>Timezone</dt><dd>Asia/Kolkata</dd></div></dl></section>
    <div className={styles.settingsGrid}><Section title="Personal information"><div className={styles.formGrid}>{[["Full name","Vaishnav Sawant"],["Occupation / Designation","Entrepreneur & Consultant"],["Display name","Vaishnav"],["Company / Organization","Perspective Media Pvt. Ltd."],["Email address","vaishnav@example.com"],["Country / Region","India"],["Phone number","+91 98765 43210"],["Language","English"],["Date of birth","May 12, 1992"],["Timezone","(UTC+05:30) Asia/Kolkata"]].map(([x,y]) => <label className={styles.formLabel} key={x}>{x}<input defaultValue={y} /></label>)}</div></Section><Section title="Profile visibility"><p className={styles.bodyText}>Choose who can see your profile details.</p>{["Public","Members only","Private"].map((x) => <label className={styles.radioLine} key={x}><input checked={visibility === x} name="visibility" onChange={() => setVisibility(x)} type="radio" /><span><strong>{x}</strong><small>{x === "Public" ? "Visible to all readers" : x === "Members only" ? "Visible to signed-in members" : "Only you can see your profile"}</small></span></label>)}</Section></div>
    <div className={styles.threeGrid}><Section title="Connected accounts">{[["Google","vaishnav@example.com",true],["Apple","vaishnav@example.com",true],["X","@vaishnav_sawant",false],["LinkedIn","Vaishnav Sawant",false]].map(([a,b,c]) => <div className={styles.lineItem} key={a as string}><span><ExternalLink />{a}<small>{b as string}</small></span><b className={c ? styles.success : ""}>{c ? "Connected" : "Connect"}</b></div>)}</Section><Section title="Data & privacy controls">{[[Download,"Download your data"],[ShieldCheck,"Privacy settings"],[Trash2,"Delete account"]].map(([I,x]) => { const Icon = I as React.ComponentType<{size?: number}>; return <button className={styles.settingRow} key={x as string}><Icon /><span><strong>{x as string}</strong><small>Manage your account information.</small></span><ChevronRight /></button>; })}</Section><Section title="Account activity">{[[Clock3,"Login history"],[ShieldCheck,"Security activity"]].map(([I,x]) => { const Icon = I as React.ComponentType<{size?: number}>; return <button className={styles.settingRow} key={x as string}><Icon /><span><strong>{x as string}</strong><small>Review recent account activity.</small></span><ChevronRight /></button>; })}<div className={styles.privacyNote}><ShieldCheck /> We take your privacy and security seriously.</div></Section></div>
  </div><aside className={styles.rightRail}><Section title="Quick settings shortcuts">{[[Mail,"Communication preferences"],[Newspaper,"Newsletter preferences"],[ShieldCheck,"Subscription management"],[ReceiptText,"Billing & payment history"]].map(([I,x]) => { const Icon = I as React.ComponentType<{size?: number}>; return <button className={styles.settingRow} key={x as string}><Icon /><span><strong>{x as string}</strong><small>Open related settings.</small></span><ChevronRight /></button>; })}</Section><Section title="Security overview">{[["Password","Strong"],["Two-factor authentication","On"],["Login alerts","On"]].map(([x,y]) => <div className={styles.lineItem} key={x}><span><LockKeyhole />{x}</span><b className={styles.success}>{y}</b></div>)}</Section><Section title="Active sessions (3)" action={<Link href="#">View all</Link>}>{["Windows 11 · Chrome","iPhone 14 · Safari","MacBook Pro · Chrome"].map((x) => <div className={styles.session} key={x}><Laptop /><span><strong>{x}</strong><small>Mumbai, India · Active now</small></span><em>Active</em></div>)}<PrimaryButton tone="outline">Sign out of other devices</PrimaryButton></Section></aside></div></MemberShell>;
}

const noticeSeed = [
  ["New article from your followed topic", "India's Manufacturing Momentum has been published under Business & Economy.", "Editorial", "/images/articles/global-growth.png"],
  ["Ananya Rao published a new article", "Leadership in Uncertain Times: A Conversation with Global CEOs.", "Authors & People", "/images/auth/member-access-hero.png"],
  ["The Perspective — May issue is out now", "Read the latest edition: The Architects of Tomorrow.", "Magazines", "/images/articles/future-leader.png"],
  ["New podcast episode", "The Future of AI Regulation is now available.", "Podcasts", "/images/podcasts/naveen-malhotra-hero-clean.webp"],
  ["Event reminder", "Global Leadership Summit 2026 starts in 2 days.", "Events", "/images/events/leadership-summit-hero.png"],
  ["Daily Briefing delivered", "Your Morning Briefing is ready.", "Newsletters", "/images/newsletter/briefings-hero.png"],
  ["Exclusive invite for Premium members", "You're invited to a closed-door roundtable.", "Exclusive", "/images/articles/board-governance.png"],
  ["Security alert", "New sign-in detected on Chrome, Mumbai, India.", "Account", "/images/articles/cybersecurity-operations.png"],
];

function NotificationsPage() {
  const [filter, setFilter] = useState("All"); const [unread, setUnread] = useState(noticeSeed.map((_, i) => i < 4)); const [delivery, setDelivery] = useState([true,true,true,true]);
  const visible = noticeSeed.filter((n) => filter === "All" || n[2] === filter);
  return <MemberShell page="notifications"><div className={styles.contentWithRail}><div><PageHeader title="Notifications" intro="Stay on top of the stories, people, magazines and updates that matter to you." actions={<><PrimaryButton onClick={() => setUnread(unread.map(() => false))} tone="outline"><Check /> Mark all as read</PrimaryButton><PrimaryButton><Settings /> Notification settings</PrimaryButton></>} /><div className={styles.noticeSummary}><StatStrip items={[{ icon: <Bell />, value: `${unread.filter(Boolean).length}`, label: "Unread" }, { icon: <CalendarDays />, value: "34", label: "This week" }, { icon: <Star />, value: "5", label: "Priority" }, { icon: <Mail />, value: "128", label: "Total" }]} /><label><Search /><input placeholder="Search notifications…" /></label></div><div className={styles.tabs}>{["All","Editorial","Authors & People","Magazines","Events","Account"].map((x) => <button className={filter === x ? styles.tabActive : ""} key={x} onClick={() => setFilter(x)}>{x}</button>)}</div>
    <div className={styles.noticeList}>{visible.map((n) => { const index = noticeSeed.indexOf(n); return <article className={unread[index] ? styles.unreadNotice : ""} key={n[0]} onClick={() => setUnread((old) => old.map((x,i) => i === index ? false : x))}><i /><Image alt="" height={58} src={n[3]} width={80} /><div><h3>{n[0]}</h3><p>{n[1]}</p></div><span>{n[2]}</span><time>{index < 3 ? `${10-index}:2${index} AM` : `May ${14-index}, 2026`}</time><button aria-label="Save"><Bookmark /></button><button aria-label="More"><MoreVertical /></button></article>; })}</div><PrimaryButton tone="outline">Load more <ChevronDown /></PrimaryButton>
  </div><aside className={styles.rightRail}><Section title="Delivery preferences">{["In-app notifications","Email notifications","Push notifications","Daily digest email"].map((x,i) => <div className={styles.toggleLine} key={x}><span><Bell />{x}</span><Toggle checked={delivery[i]} label={x} onChange={() => setDelivery((old) => old.map((v,j) => i === j ? !v : v))} /></div>)}<div className={styles.quiet}><Clock3 /><div><strong>Quiet hours</strong><p>10:00 PM – 7:00 AM</p></div></div></Section><Section title="Priority notifications">{["Breaking news & editorial","Followed topics","Authors & people","Magazine releases","Events & reminders"].map((x,i) => <div className={styles.lineItem} key={x}><span><Star />{x}</span><b>{i % 2 ? "Medium" : "High"}</b></div>)}</Section><Promo icon={<Headphones />} title="Need help?" text="Learn more about notifications and preferences." href="/help" action="View Help Center" /></aside></div></MemberShell>;
}

function MagazinesPage() {
  const [tab, setTab] = useState("All issues");
  return <MemberShell page="magazines"><div className={styles.contentWithRail}><div><PageHeader title="My Magazine Library" intro="Access all your magazine issues, Premium editions and reading progress." actions={<><label className={styles.headerSearch}><Search /><input placeholder="Search issues in your library…" /></label><PrimaryButton tone="outline"><Filter /> Filters</PrimaryButton></>} /><StatStrip items={[{ icon: <BookOpen />, value: "14", label: "Issues available" }, { icon: <Star />, value: "4", label: "Premium editions" }, { icon: <Clock3 />, value: "3", label: "In progress" }, { icon: <CheckCircle2 />, value: "6", label: "Completed" }, { icon: <Bookmark />, value: "8", label: "Saved" }]} /><div className={styles.tabs}>{["All issues","In progress","Premium editions","Completed","Saved","Downloads"].map((x) => <button className={tab === x ? styles.tabActive : ""} key={x} onClick={() => setTab(x)}>{x}</button>)}</div><div className={styles.sectionLabel}><h2>Continue reading</h2></div><div className={styles.magazineGrid}>{magazineIssues.slice(0,4).map((i) => <MagazineCard issue={i} key={i.month} />)}</div><div className={styles.sectionLabel}><h2>Premium editions</h2><Link href="/magazine/premium">View all</Link></div><div className={styles.magazineGrid}>{magazineIssues.slice().reverse().map((i) => <MagazineCard compact issue={{...i,title:`Premium: ${i.title}`}} key={i.month} />)}</div><div className={styles.sectionLabel}><h2>Saved for later</h2></div><div className={styles.savedIssueRow}>{magazineIssues.slice(1).map((i) => <StoryMini key={i.month} story={{title:i.title,topic:i.month,image:i.image,meta:i.issue,progress:i.progress}} />)}</div>
  </div><aside className={styles.rightRail}><section className={styles.memberCard}><small>Your magazine access</small><h2>Premium Member</h2><p>Full access to all issues, premium editions and a 10+ year archive.</p><PrimaryButton href="/my-perspective/subscription" tone="outline">Manage subscription</PrimaryButton></section><Section title="Reading progress"><div className={styles.progressDonut}><strong>3</strong><span>In progress</span></div>{[["In progress",3],["Completed",6],["Saved",8],["Not started",21]].map(([x,n]) => <div className={styles.lineItem} key={x}><span>{x}</span><b>{n}</b></div>)}</Section><Section title="Recommended for you">{magazineIssues.slice(0,2).map((i) => <StoryMini key={i.month} story={{title:i.title,topic:i.month,image:i.image,meta:i.issue,progress:i.progress}} />)}<Link className={styles.textLink} href="/magazine/archive">Explore more issues <ChevronRight /></Link></Section></aside></div></MemberShell>;
}

const eventRows = [
  ["Future of Technology Summit 2026","Jun 18, 2026","Mumbai · Virtual","/images/articles/ai-infrastructure.png"],
  ["Global Economic Outlook 2026","Jul 10, 2026","Bengaluru · In person","/images/articles/global-leadership.png"],
];

function EventsPage() {
  const [tab,setTab] = useState("Upcoming (3)");
  return <MemberShell page="events"><div className={styles.contentWithRail}><div><PageHeader title="My Events" intro="Manage registrations, tickets, schedules and event experiences." actions={<><PrimaryButton href="/events" tone="outline"><CalendarDays /> Browse events</PrimaryButton><PrimaryButton><CalendarDays /> Add to calendar</PrimaryButton></>} /><div className={styles.tabs}>{["Upcoming (3)","Past events (8)","Saved (2)","Member events (1)"].map((x) => <button className={tab === x ? styles.tabActive : ""} key={x} onClick={() => setTab(x)}>{x}</button>)}</div><div className={styles.sectionLabel}><h2>Upcoming events</h2></div><article className={styles.featureEvent}><div className={styles.eventPoster}><Image alt="Leadership summit at night" fill src="/images/events/leadership-summit-hero.png" /><b>The Perspective<br />Leadership Summit</b></div><div><span className={styles.statusPaid}>Registration confirmed</span><h2>The Perspective Leadership Summit 2026</h2><p><CalendarDays /> May 29–30, 2026 · 9:00 AM–6:00 PM IST</p><p>India&apos;s premier leadership gathering bringing together global visionaries and changemakers.</p><div className={styles.inlineActions}><PrimaryButton href="/events/leadership-summit-2026"><Ticket /> View ticket</PrimaryButton><PrimaryButton tone="outline">View agenda</PrimaryButton><PrimaryButton tone="outline">Add to calendar</PrimaryButton></div></div><div className={styles.ticketCode}><Ticket /><strong>TPSLS2026-001245</strong><span>Premium member</span></div></article><div className={styles.eventRows}>{eventRows.map((e) => <article key={e[0]}><Image alt="" height={75} src={e[3]} width={160} /><div><span className={styles.statusPaid}>Confirmed</span><h3>{e[0]}</h3><p>{e[1]} · {e[2]}</p></div><PrimaryButton tone="outline">View ticket</PrimaryButton><PrimaryButton tone="outline">Add to calendar</PrimaryButton></article>)}</div><div className={styles.sectionLabel}><h2>Past events</h2><Link href="/events">View all</Link></div><div className={styles.pastEvents}>{stories.slice(0,4).map((s,i) => <article key={s.title}><Image alt="" fill src={s.image} /><div><small>Attended</small><h3>{["Perspective Conclave","Sustainability Summit","Finance Leadership Forum","AI & Innovation Summit"][i]} 2025</h3><PrimaryButton tone="outline">View replay</PrimaryButton></div></article>)}</div><div className={styles.sectionLabel}><h2>Saved / interested events</h2></div><div className={styles.savedIssueRow}>{eventRows.map((e) => <StoryMini key={e[0]} story={{title:e[0],topic:e[1],image:e[3],meta:e[2],progress:0}} />)}</div>
  </div><aside className={styles.rightRail}><Section title="Your next event"><div className={styles.countdown}><span>Starts in</span><strong>16</strong><small>days</small></div><h3>The Perspective Leadership Summit 2026</h3>{[["Registration status","Confirmed"],["Ticket type","Premium Member"],["Registration ID","TPSLS2026-001245"],["Attendee","Vaishnav Sawant"]].map(([x,y]) => <div className={styles.lineItem} key={x}><span>{x}</span><b>{y}</b></div>)}<PrimaryButton><Ticket /> View ticket</PrimaryButton></Section><Section title="Event tools">{["My agenda","Saved sessions","Speakers I follow","Networking"].map((x) => <button className={styles.settingRow} key={x}><CalendarDays /><span><strong>{x}</strong><small>Manage your event experience.</small></span><ChevronRight /></button>)}</Section><Section title="Recommended for you"><StoryMini story={{...stories[2],title:"World Leadership Summit 2026"}} /><PrimaryButton href="/events" tone="outline">Register now</PrimaryButton></Section></aside></div></MemberShell>;
}

type TicketItem = { title:string; id:string; status:string; category:string; date:string; };
const tickets: TicketItem[] = [
  { title:"Issue accessing premium article", id:"TPS-75621", status:"Open", category:"Magazine / Digital Reader", date:"May 12, 2026" },
  { title:"Payment failed but amount deducted", id:"TPS-75603", status:"Open", category:"Subscription & Billing", date:"May 11, 2026" },
  { title:"Newsletter not received", id:"TPS-75587", status:"Awaiting reply", category:"Newsletter", date:"May 10, 2026" },
  { title:"How to download invoice?", id:"TPS-75512", status:"Resolved", category:"Subscription & Billing", date:"May 5, 2026" },
  { title:"Change email address", id:"TPS-75432", status:"Resolved", category:"Account & Security", date:"Apr 28, 2026" },
];

function SupportPage() {
  const [selected,setSelected] = useState(tickets[0]); const [reply,setReply] = useState(""); const [sent,setSent] = useState(false);
  return <MemberShell page="support"><div className={styles.contentWithRail}><div><PageHeader title="Help & Support Requests" intro="Get help, track your conversations and connect with the right Perspective team." actions={<PrimaryButton><Plus /> Create support request</PrimaryButton>} /><StatStrip items={[{icon:<MessageSquare />,value:"2",label:"Open"},{icon:<Mail />,value:"1",label:"Awaiting reply"},{icon:<CheckCircle2 />,value:"8",label:"Resolved"},{icon:<ReceiptText />,value:"12",label:"Closed"}]} /><div className={styles.tabs}>{["All requests","Open (2)","Awaiting reply (1)","Resolved (8)","Closed (12)"].map((x,i) => <button className={i === 0 ? styles.tabActive : ""} key={x}>{x}</button>)}</div><div className={styles.supportDesk}><div className={styles.ticketList}>{tickets.map((t) => <button className={selected.id === t.id ? styles.ticketActive : ""} key={t.id} onClick={() => setSelected(t)}><span data-status={t.status}>{t.status}</span><strong>{t.title}</strong><small>{t.category} · #{t.id} · {t.date}</small><ChevronRight /></button>)}</div><section className={styles.thread}><header><small>#{selected.id}</small><h2>{selected.title}</h2><div><span>Category <b>{selected.category}</b></span><span>Priority <b>High</b></span><span>Created <b>{selected.date}</b></span><span>Assigned to <b>Ronit Sharma</b></span></div></header><article><div className={styles.initials}>VS</div><div><strong>Vaishnav Sawant</strong><time>May 12, 2026, 10:24 AM</time><p>I am unable to access this feature even though my account is active. Please check and help.</p><button><FileText /> error_screenshot.png <Download /></button></div></article><article><Image alt="Ronit Sharma" height={38} src="/images/articles/marcus-chen.png" width={38} /><div><strong>Ronit Sharma <em>Support specialist</em></strong><time>May 12, 2026, 11:15 AM</time><p>Hi Vaishnav, thank you for reaching out. We checked your account and resolved the issue. Please try again now.</p></div></article>{sent && <article><div className={styles.initials}>VS</div><div><strong>Vaishnav Sawant</strong><time>Just now</time><p>{reply || "Thank you for your help."}</p></div></article>}<form onSubmit={(e) => { e.preventDefault(); setSent(true); }}><input onChange={(e) => setReply(e.target.value)} placeholder="Type your message here…" value={reply} /><button type="submit">Send reply</button></form></section></div><Section title="Help Center suggestions" action={<Link href="/help">View all help articles</Link>}><div className={styles.helpLinks}>{["How to access Premium articles","Troubleshooting login issues","Managing your subscription","Payment failed but amount deducted?"].map((x) => <Link href="/help" key={x}><strong>{x}</strong><span>Step-by-step guidance and answers.</span></Link>)}</div></Section>
  </div><aside className={styles.rightRail}><Section title="Need quick help?">{["Search Help Center","Subscription & Billing","Account & Security","Magazine / Digital Reader","Events support"].map((x) => <button className={styles.settingRow} key={x}><HelpCircle /><span><strong>{x}</strong><small>Find answers and guidance.</small></span><ChevronRight /></button>)}</Section><Section title="Typical response time">{[["General support","Within 24 hours"],["Billing & payments","1 business day"],["Complex enquiries","Up to 2 business days"]].map(([x,y]) => <div className={styles.responseTime} key={x}><Clock3 /><span><strong>{x}</strong><small>{y}</small></span></div>)}</Section><Section title="Still need help?"><p className={styles.bodyText}>Email support<br /><strong>support@theperspective.com</strong></p><p className={styles.bodyText}>Call us<br /><strong>+91 22 6950 2050</strong></p><PrimaryButton tone="outline">Start live chat</PrimaryButton></Section></aside></div></MemberShell>;
}

const pages: Record<MemberPage, React.ComponentType> = { dashboard: DashboardPage, saved: SavedPage, following: FollowingPage, newsletters: NewsletterPage, subscription: SubscriptionPage, billing: BillingPage, settings: SettingsPage, notifications: NotificationsPage, magazines: MagazinesPage, events: EventsPage, support: SupportPage };

export function MemberExperience({ page }: { page: MemberPage }) {
  const Page = pages[page];
  return <Page />;
}
