import type { LucideIcon } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BookOpen, Bookmark, Crown, Headphones, LockKeyhole, Mail, ShieldCheck, UserRound, UsersRound } from "lucide-react";
import { ForgotPasswordForm, LoginForm, SignupForm, VerificationPanel } from "./auth-forms";
import styles from "./auth-pages.module.css";

type Mode="login"|"signup"|"forgot"|"verify";
const copy={
 login:{eyebrow:"Sign in to The Perspective",title:<>Welcome back to<br/>meaningful perspectives.</>,description:"Sign in to access premium stories, digital magazines, expert insights, newsletters, events and a personalized experience curated just for you."},
 signup:{eyebrow:"Join The Perspective",title:<>Create Your Account.<br/>Build Your Reading<br/>Experience.</>,description:"Save stories, follow topics and authors, access digital magazines, manage briefings, and personalize how you experience The Perspective."},
 forgot:{eyebrow:"Account recovery",title:<>Your Perspective<br/>Is Still Here.</>,description:"Saved stories, followed topics, magazine access, briefings and preferences remain connected to your account."},
 verify:{eyebrow:"Verify your email",title:<>One More Step.<br/>Then Your Perspective<br/>Is Yours.</>,description:"We’ve sent a verification link to john.doe@email.com. Verify your email to activate your account and start personalizing your experience."},
} as const;
const features:Record<Mode,{icon:LucideIcon;title:string;text:string}[]>={
 login:[{icon:Bookmark,title:"Save & read anywhere",text:"Save articles, magazines and podcasts to read or listen anytime."},{icon:UserRound,title:"Personalized for you",text:"Follow topics, authors and leaders and get stories that matter."},{icon:Crown,title:"Premium access",text:"Unlimited access to in-depth journalism and member benefits."}],
 signup:[{icon:Bookmark,title:"Save & organize",text:"Save articles, magazines and podcasts to read anytime."},{icon:UserRound,title:"Personalized for you",text:"Follow topics, authors and leaders."},{icon:BookOpen,title:"Digital magazine access",text:"Read current issues and past editions."},{icon:Mail,title:"Newsletter & briefings",text:"Manage preferences and receive the updates that matter."}],
 forgot:[{icon:Bookmark,title:"Pick up where you left off",text:"Your reading list, highlights and saved stories are waiting."},{icon:UserRound,title:"Personalized for you",text:"Topics, authors and preferences stay as you set them."},{icon:BookOpen,title:"Access what matters",text:"Digital magazines, newsletters and exclusive content remain yours."},{icon:ShieldCheck,title:"Secure & private",text:"We keep your data safe and your account protected."}],
 verify:[{icon:Bookmark,title:"Save & organize",text:"Saved stories and magazines stay connected."},{icon:UserRound,title:"Follow what matters",text:"Choose authors, topics and leaders."},{icon:BookOpen,title:"Access digital editions",text:"Read magazines across devices."},{icon:ShieldCheck,title:"Manage your briefings",text:"Control newsletters and alerts from one account."}],
};
const trust=[{icon:LockKeyhole,title:"Secure & private",text:"Enterprise-grade security protects your data."},{icon:UsersRound,title:"Trusted by thousands",text:"Join a global community of readers and leaders."},{icon:Headphones,title:"Need help?",text:"Our support team is here to help."},{icon:ArrowRight,title:"Visit Help Center",text:"Find answers to account questions."}];

export function AuthPage({mode,recoveryToken,returnPath}:{mode:Mode;recoveryToken?:string;returnPath?:string}){const current=copy[mode];return <main className={styles.page}><div className={styles.authShell}><section className={styles.editorial}><Image alt="The Perspective magazine, laptop and mobile member reading experience" fill priority sizes="(max-width: 900px) 100vw, 60vw" src="/images/auth/member-access-hero.png"/><div className={styles.imageWash}/><div className={styles.editorialCopy}><p>{current.eyebrow}</p><h1>{current.title}</h1><i/><span>{current.description}</span><ul>{features[mode].map(({icon:Icon,title,text})=><li key={title}><Icon/><div><b>{title}</b><small>{text}</small></div></li>)}</ul><blockquote>Independent journalism. Expert analysis. Meaningful influence.<br/>That’s The Perspective.</blockquote></div></section><section className={styles.formSide}>{mode==="login"?<LoginForm returnPath={returnPath}/>:mode==="signup"?<SignupForm/>:mode==="forgot"?<ForgotPasswordForm token={recoveryToken}/>:<VerificationPanel/>}</section></div><section className={styles.trustStrip}>{trust.map(({icon:Icon,title,text},index)=><Link href={index>1?"/help":"/about"} key={title}><Icon/><span><b>{title}</b><small>{text}</small></span></Link>)}</section><section className={styles.authBridge}><div><p>Member experience</p><h2>Your Perspective account connects every story, issue, briefing and event.</h2></div><Link href="/help">Account support <ArrowRight/></Link></section></main>}
