"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useMemo, useState, type FormEvent } from "react";
import { Building2, CheckCircle2, Eye, EyeOff, LockKeyhole, Mail, Send, ShieldCheck, UserRound, XCircle } from "lucide-react";
import type { AuthenticationContextOption } from "@/modules/authentication/types";
import styles from "./auth-pages.module.css";

function PasswordField({ confirm = false, minLength = 8, onChange, value }: { confirm?: boolean; minLength?: number; onChange: (value: string) => void; value: string }) {
  const [visible,setVisible]=useState(false);
  return <label><span>{confirm ? "Confirm password" : "Password"}</span><div className={styles.inputWrap}><input autoComplete={confirm?"new-password":"current-password"} minLength={minLength} onChange={e=>onChange(e.target.value)} placeholder={confirm ? "Confirm your password" : "Enter your password"} required type={visible?"text":"password"} value={value}/><LockKeyhole/><button aria-label={visible?"Hide password":"Show password"} onClick={()=>setVisible(v=>!v)} type="button">{visible?<EyeOff/>:<Eye/>}</button></div></label>;
}

function SocialButtons(){return <><div className={styles.socials}><button disabled title="Not configured" type="button"><b>G</b>Continue with Google</button><button disabled title="Not configured" type="button"><b>●</b>Continue with Apple</button></div><div className={styles.or}><span/>or<span/></div></>}
function FormMessage({message,success}:{message:string;success:boolean}){return message?<p aria-live="polite" className={success?styles.success:styles.error}>{success?<CheckCircle2/>:<XCircle/>}{message}</p>:null}

export function LoginForm({returnPath}:{returnPath?:string}){
 const router=useRouter();
 const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [remember,setRemember]=useState(false);const [message,setMessage]=useState("");const [success,setSuccess]=useState(false);const [pending,setPending]=useState(false);const [challengeToken,setChallengeToken]=useState("");const [code,setCode]=useState("");const [contexts,setContexts]=useState<AuthenticationContextOption[]>([]);const [selectedMembershipId,setSelectedMembershipId]=useState("");
 async function submit(e:FormEvent){e.preventDefault();setPending(true);setMessage("");try{if(contexts.length){const response=await fetch("/api/v1/auth/context",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({membershipId:selectedMembershipId})});if(!response.ok){setSuccess(false);setMessage("Unable to select that organization.");return}setSuccess(true);setMessage("Organization selected. Redirecting…");router.push(returnPath ?? "/app");router.refresh();return}const response=await fetch(challengeToken?"/api/v1/auth/mfa/verify":"/api/v1/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(challengeToken?{challengeToken,code}:{email,password,surface:"TEAM",remember})});const result=await response.json().catch(()=>({}));if(response.status===202&&result.challengeToken){setChallengeToken(result.challengeToken);setSuccess(true);setMessage("Enter the six-digit code from your authenticator app.");return}if(response.status===202&&result.status==="context_selection_required"&&Array.isArray(result.contexts)){const nextContexts=result.contexts as AuthenticationContextOption[];setChallengeToken("");setContexts(nextContexts);setSelectedMembershipId(nextContexts[0]?.membershipId??"");setSuccess(true);setMessage("Choose the organization you want to use for this session.");return}if(!response.ok){setSuccess(false);setMessage(challengeToken?"Unable to verify that code.":"Unable to sign in with those credentials.");return}setSuccess(true);setMessage("Signed in securely. Redirecting…");router.push(returnPath ?? "/app");router.refresh()}catch{setSuccess(false);setMessage("Authentication is temporarily unavailable.")}finally{setPending(false)}}
 return <form className={styles.authForm} onSubmit={submit}><h2>{contexts.length?"Choose Organization":challengeToken?"Two-Factor Verification":"Team Workspace Sign In"}</h2><p>{contexts.length?"Your identity is verified. Select one eligible organization for this session.":challengeToken?"Enter the current code from your authenticator app.":"Welcome back. Please sign in to your authorized workspace."}</p>{!challengeToken&&!contexts.length&&<><SocialButtons/><label><span>Email address</span><div className={styles.inputWrap}><input autoComplete="username" inputMode="email" onChange={e=>setEmail(e.target.value)} placeholder="Enter your work email address" required type="email" value={email}/><Mail/></div></label><PasswordField minLength={1} onChange={setPassword} value={password}/><div className={styles.formOptions}><label><input checked={remember} onChange={e=>setRemember(e.target.checked)} type="checkbox"/> Remember me</label><Link href="/forgot-password">Forgot password?</Link></div></>}{challengeToken&&<label><span>Authenticator code</span><div className={styles.inputWrap}><input autoComplete="one-time-code" inputMode="numeric" maxLength={6} minLength={6} onChange={e=>setCode(e.target.value.replace(/\D/gu,""))} placeholder="000000" required value={code}/><ShieldCheck/></div></label>}{contexts.length>0&&<label><span>Organization</span><div className={styles.inputWrap}><select className={styles.contextSelect} onChange={e=>setSelectedMembershipId(e.target.value)} required value={selectedMembershipId}>{contexts.map(context=><option key={context.membershipId} value={context.membershipId}>{context.organizationName}</option>)}</select><Building2/></div></label>}<button className={styles.primary} disabled={pending||Boolean(contexts.length&&!selectedMembershipId)} type="submit">{pending?"Please wait…":contexts.length?"Continue":challengeToken?"Verify and continue":"Sign in"}</button><FormMessage message={message} success={success}/><p className={styles.switch}>Workspace access is invitation-only.</p><Privacy/></form>
}

export function SignupForm(){
 const [data,setData]=useState({first:"",last:"",email:"",password:"",confirm:""});const [terms,setTerms]=useState(false);const [message,setMessage]=useState("");const [success,setSuccess]=useState(false);const strength=useMemo(()=>data.password.length>=12?"Strong":data.password.length>=8?"Medium":"Weak",[data.password]);
 function set(key:keyof typeof data,value:string){setData(current=>({...current,[key]:value}))}function submit(e:FormEvent){e.preventDefault();if(!terms){setSuccess(false);setMessage("Please accept the Terms of Use and Privacy Policy.");return}if(data.password!==data.confirm||data.password.length<8){setSuccess(false);setMessage("Passwords must match and contain at least 8 characters.");return}setSuccess(false);setMessage("Public account creation is not available. Workspace access is invitation-only, and no account or email was created.")}
 return <form className={styles.authForm} onSubmit={submit}><h2>Create Your Account</h2><p>Public self-signup is not available. Workspace access is invitation-only.</p><SocialButtons/><div className={styles.twoFields}><label><span>First name</span><div className={styles.inputWrap}><input onChange={e=>set("first",e.target.value)} placeholder="Enter your first name" required value={data.first}/><UserRound/></div></label><label><span>Last name</span><div className={styles.inputWrap}><input onChange={e=>set("last",e.target.value)} placeholder="Enter your last name" required value={data.last}/><UserRound/></div></label></div><label><span>Email address</span><div className={styles.inputWrap}><input onChange={e=>set("email",e.target.value)} placeholder="Enter your email address" required type="email" value={data.email}/><Mail/></div></label><div className={styles.twoFields}><PasswordField onChange={v=>set("password",v)} value={data.password}/><PasswordField confirm onChange={v=>set("confirm",v)} value={data.confirm}/></div><div className={styles.strength}>Password strength: <b data-strength={strength}>{strength}</b><i><span style={{width:strength==="Strong"?"100%":strength==="Medium"?"62%":"25%"}}/></i></div><label className={styles.check}><input disabled title="Newsletter delivery is not configured" type="checkbox"/>I would like to receive newsletters and important updates.</label><label className={styles.check}><input checked={terms} onChange={e=>setTerms(e.target.checked)} type="checkbox"/>I agree to the <Link href="/terms">Terms of Use</Link> and <Link href="/privacy">Privacy Policy</Link>.</label><button className={styles.primary} type="submit">Create account</button><FormMessage message={message} success={success}/><p className={styles.switch}>Already have an account? <Link href="/login">Sign in</Link></p><Privacy/></form>
}

export function ForgotPasswordForm({token=""}:{token?:string}){
 const [email,setEmail]=useState("");const [state,setState]=useState<"idle"|"sent"|"error">("idle");const [pending,setPending]=useState(false);const [password,setPassword]=useState("");const [confirm,setConfirm]=useState("");
 async function submit(e:FormEvent){e.preventDefault();setPending(true);try{const response=await fetch(token?"/api/v1/auth/recovery/complete":"/api/v1/auth/recovery/request",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(token?{token,password,confirmPassword:confirm,surface:"TEAM"}:{email,surface:"TEAM"})});setState(response.ok?"sent":"error")}catch{setState("error")}finally{setPending(false)}}
 return <><form className={`${styles.authForm} ${styles.recovery}`} onSubmit={submit}><div className={styles.formIcon}><LockKeyhole/></div><h2>{token?"Create a New Password":"Forgot Your Password?"}</h2><p>{token?"Choose a new password. Completing recovery will revoke your existing sessions.":"Enter the work email associated with your account. If it is eligible, we’ll send a secure recovery link."}</p>{token?<><PasswordField minLength={12} onChange={setPassword} value={password}/><PasswordField confirm minLength={12} onChange={setConfirm} value={confirm}/></>:<label><span>Email address</span><div className={styles.inputWrap}><input onChange={e=>setEmail(e.target.value)} placeholder="Enter your work email address" required type="email" value={email}/><Mail/></div></label>}<button className={styles.primary} disabled={pending} type="submit">{pending?"Please wait…":token?"Reset password":"Send recovery link"}</button><div className={styles.or}><span/>or<span/></div><Link className={styles.outline} href="/login">← Back to sign in</Link><p className={styles.helpLine}>Need help? Visit our <Link href="/help">Help Center</Link>.</p></form><aside className={styles.stateRail}><StateCard kind="success" title={token?"Password reset complete":"Check your email"} text={state==="sent"?(token?"Your password was reset. Return to sign in.":"If the account is eligible, recovery instructions will arrive shortly."):"Recovery status will appear here."}/><StateCard kind="error" title="Unable to complete request" text={state==="error"?"The request is invalid, expired, or temporarily unavailable.":"Expired and invalid links fail securely."}/><StateCard kind="secure" title="Your security is our priority" text="Recovery links are single-use and expire after 60 minutes."/></aside></>
}

function StateCard({kind,title,text}:{kind:"success"|"error"|"secure";title:string;text:string}){const Icon=kind==="success"?Send:kind==="error"?XCircle:ShieldCheck;return <section className={styles.stateCard} data-kind={kind}><Icon/><div><b>{title}</b><p>{text}</p><button disabled title="Use the recovery form. This card does not send email." type="button">{kind==="success"?"Resend link":kind==="error"?"Try again":"Learn more"}</button></div></section>}
function Privacy(){return <div className={styles.privacy}><ShieldCheck/><div><b>Your privacy and security are our priority.</b><span>We never share your personal information.</span></div></div>}

export function VerificationPanel(){
 const [state,setState]=useState<"sent"|"verified"|"expired"|"invalid">("sent");
 return <div className={styles.verifyLayout}><section className={styles.verifyMain}><header><b>Verification preview</b><nav aria-label="Preview states. No email is sent.">{(["sent","verified","expired","invalid"] as const).map(item=><button aria-pressed={state===item} onClick={()=>setState(item)} type="button" key={item}>{item==="sent"?"Email sent":item[0].toUpperCase()+item.slice(1)}</button>)}</nav></header><div className={styles.verifyBody}>{state==="sent"?<><div className={styles.formIcon}><Send/></div><h2>Check Your Inbox</h2><p>This is a preview of the verification screen. No verification email is sent, and no account is activated.</p><div className={styles.verifySteps}><span><Mail/><b>Open your email</b><small>Check your inbox and spam folder.</small></span><span><Send/><b>Click the link</b><small>Tap the verification link.</small></span><span><ShieldCheck/><b>You’re all set</b><small>Your account activates instantly.</small></span></div><button className={styles.primary} disabled title="Email delivery is not configured" type="button">Open email app</button><div className={styles.verifyActions}><button disabled title="Email delivery is not configured" type="button">Resend verification email</button><Link href="/signup">Change email address</Link></div><small>Resend is unavailable because email delivery is not configured.</small></>:<VerificationState state={state}/>}<Link className={styles.back} href="/login">← Back to sign in</Link></div></section><aside className={styles.stateRail}><VerificationMini kind="verified"/><VerificationMini kind="expired"/><VerificationMini kind="invalid"/></aside></div>
}
function VerificationState({state}:{state:"verified"|"expired"|"invalid"}){return <div className={styles.singleState}>{state==="verified"?<CheckCircle2/>:<XCircle/>}<h2>{state==="verified"?"Preview: verified appearance":state==="expired"?"This Link Has Expired":"This Link Is Invalid"}</h2><p>{state==="verified"?"This preview does not activate an account or verify an email address.":"Email delivery is not configured, so a new verification link cannot be sent."}</p>{state==="verified"?<Link className={styles.primary} href="/login">Return to sign in</Link>:<button className={styles.primary} disabled title="Email delivery is not configured" type="button">Send new verification link</button>}</div>}
function VerificationMini({kind}:{kind:"verified"|"expired"|"invalid"}){const ok=kind==="verified";return <section className={styles.verifyMini} data-kind={kind}>{ok?<CheckCircle2/>:<XCircle/>}<div><small>{kind}</small><h3>{ok?"Preview only":kind==="expired"?"This Link Has Expired":"This Link Is Invalid"}</h3><p>{ok?"No account was activated.":"A new email cannot be sent from this page."}</p><button disabled title="Email delivery is not configured" type="button">{ok?"Continue":"Send new link"}</button></div></section>}
