"use client";

import Link from "next/link";
import { useMemo, useState, type FormEvent } from "react";
import { CheckCircle2, Eye, EyeOff, LockKeyhole, Mail, Send, ShieldCheck, UserRound, XCircle } from "lucide-react";
import styles from "./auth-pages.module.css";

function PasswordField({ confirm = false, onChange, value }: { confirm?: boolean; onChange: (value: string) => void; value: string }) {
  const [visible,setVisible]=useState(false);
  return <label><span>{confirm ? "Confirm password" : "Password"}</span><div className={styles.inputWrap}><input minLength={8} onChange={e=>onChange(e.target.value)} placeholder={confirm ? "Confirm your password" : "Enter your password"} required type={visible?"text":"password"} value={value}/><LockKeyhole/><button aria-label={visible?"Hide password":"Show password"} onClick={()=>setVisible(v=>!v)} type="button">{visible?<EyeOff/>:<Eye/>}</button></div></label>;
}

function SocialButtons(){return <><div className={styles.socials}><button type="button"><b>G</b>Continue with Google</button><button type="button"><b>●</b>Continue with Apple</button></div><div className={styles.or}><span/>or<span/></div></>}
function FormMessage({message,success}:{message:string;success:boolean}){return message?<p aria-live="polite" className={success?styles.success:styles.error}>{success?<CheckCircle2/>:<XCircle/>}{message}</p>:null}

export function LoginForm(){
 const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [message,setMessage]=useState("");const [success,setSuccess]=useState(false);
 function submit(e:FormEvent){e.preventDefault();if(!email.includes("@")||password.length<8){setSuccess(false);setMessage("Enter a valid email and a password of at least 8 characters.");return}localStorage.setItem("perspective-demo-member",email);setSuccess(true);setMessage("Signed in successfully. Your member experience is ready.")}
 return <form className={styles.authForm} onSubmit={submit}><h2>Sign In</h2><p>Welcome back. Please sign in to your account.</p><SocialButtons/><label><span>Email address</span><div className={styles.inputWrap}><input inputMode="email" onChange={e=>setEmail(e.target.value)} placeholder="Enter your email address" required type="email" value={email}/><Mail/></div></label><PasswordField onChange={setPassword} value={password}/><div className={styles.formOptions}><label><input type="checkbox"/> Remember me</label><Link href="/forgot-password">Forgot password?</Link></div><button className={styles.primary} type="submit">Sign in</button><FormMessage message={message} success={success}/><p className={styles.switch}>New to The Perspective?</p><Link className={styles.outline} href="/signup">Create your account</Link><Privacy/></form>
}

export function SignupForm(){
 const [data,setData]=useState({first:"",last:"",email:"",password:"",confirm:""});const [terms,setTerms]=useState(false);const [message,setMessage]=useState("");const [success,setSuccess]=useState(false);const strength=useMemo(()=>data.password.length>=12?"Strong":data.password.length>=8?"Medium":"Weak",[data.password]);
 function set(key:keyof typeof data,value:string){setData(current=>({...current,[key]:value}))}function submit(e:FormEvent){e.preventDefault();if(!terms){setSuccess(false);setMessage("Please accept the Terms of Use and Privacy Policy.");return}if(data.password!==data.confirm||data.password.length<8){setSuccess(false);setMessage("Passwords must match and contain at least 8 characters.");return}localStorage.setItem("perspective-pending-member",data.email);setSuccess(true);setMessage("Account created. Check your inbox to verify your email.")}
 return <form className={styles.authForm} onSubmit={submit}><h2>Create Your Account</h2><p>It’s quick, easy and free.</p><SocialButtons/><div className={styles.twoFields}><label><span>First name</span><div className={styles.inputWrap}><input onChange={e=>set("first",e.target.value)} placeholder="Enter your first name" required value={data.first}/><UserRound/></div></label><label><span>Last name</span><div className={styles.inputWrap}><input onChange={e=>set("last",e.target.value)} placeholder="Enter your last name" required value={data.last}/><UserRound/></div></label></div><label><span>Email address</span><div className={styles.inputWrap}><input onChange={e=>set("email",e.target.value)} placeholder="Enter your email address" required type="email" value={data.email}/><Mail/></div></label><div className={styles.twoFields}><PasswordField onChange={v=>set("password",v)} value={data.password}/><PasswordField confirm onChange={v=>set("confirm",v)} value={data.confirm}/></div><div className={styles.strength}>Password strength: <b data-strength={strength}>{strength}</b><i><span style={{width:strength==="Strong"?"100%":strength==="Medium"?"62%":"25%"}}/></i></div><label className={styles.check}><input defaultChecked type="checkbox"/>I would like to receive newsletters and important updates.</label><label className={styles.check}><input checked={terms} onChange={e=>setTerms(e.target.checked)} type="checkbox"/>I agree to the <Link href="/search?q=terms">Terms of Use</Link> and <Link href="/search?q=privacy">Privacy Policy</Link>.</label><button className={styles.primary} type="submit">Create account</button><FormMessage message={message} success={success}/><p className={styles.switch}>Already have an account? <Link href="/login">Sign in</Link></p><Privacy/></form>
}

export function ForgotPasswordForm(){
 const [email,setEmail]=useState("");const [state,setState]=useState<"idle"|"sent"|"error">("idle");
 function submit(e:FormEvent){e.preventDefault();setState(email.includes("@")&&!email.startsWith("missing")?"sent":"error")}
 return <><form className={`${styles.authForm} ${styles.recovery}`} onSubmit={submit}><div className={styles.formIcon}><LockKeyhole/></div><h2>Forgot Your Password?</h2><p>Enter the email associated with your Perspective account and we’ll send you a secure link to reset your password.</p><label><span>Email address</span><div className={styles.inputWrap}><input onChange={e=>setEmail(e.target.value)} placeholder="Enter your email address" required type="email" value={email}/><Mail/></div></label><button className={styles.primary} type="submit">Send reset link</button><div className={styles.or}><span/>or<span/></div><Link className={styles.outline} href="/login">← Back to sign in</Link><p className={styles.helpLine}>Need help? Visit our <Link href="/help">Help Center</Link>.</p></form><aside className={styles.stateRail}><StateCard kind="success" title="Check your email!" text={state==="sent"?`We sent a password reset link to ${email}.`:"A successful request appears here with resend controls."}/><StateCard kind="error" title="Email not found" text={state==="error"?"We couldn’t find an account associated with that email address.":"Invalid account requests receive a clear and private error."}/><StateCard kind="secure" title="Your security is our priority" text="Password reset links are secure and expire after 60 minutes."/></aside></>
}

function StateCard({kind,title,text}:{kind:"success"|"error"|"secure";title:string;text:string}){const Icon=kind==="success"?Send:kind==="error"?XCircle:ShieldCheck;return <section className={styles.stateCard} data-kind={kind}><Icon/><div><b>{title}</b><p>{text}</p><button type="button">{kind==="success"?"Resend link":kind==="error"?"Try again":"Learn more"}</button></div></section>}
function Privacy(){return <div className={styles.privacy}><ShieldCheck/><div><b>Your privacy and security are our priority.</b><span>We never share your personal information.</span></div></div>}

export function VerificationPanel(){
 const [state,setState]=useState<"sent"|"verified"|"expired"|"invalid">("sent");const [seconds,setSeconds]=useState(45);
 function resend(){setState("sent");setSeconds(45)}
 return <div className={styles.verifyLayout}><section className={styles.verifyMain}><header><b>Verification status</b><nav>{(["sent","verified","expired","invalid"] as const).map(item=><button aria-pressed={state===item} onClick={()=>setState(item)} type="button" key={item}>{item==="sent"?"Email sent":item[0].toUpperCase()+item.slice(1)}</button>)}</nav></header><div className={styles.verifyBody}>{state==="sent"?<><div className={styles.formIcon}><Send/></div><h2>Check Your Inbox</h2><p>We’ve sent a verification email to <b>john.doe@email.com</b>.<br/>Click the link in that email to activate your account.</p><div className={styles.verifySteps}><span><Mail/><b>Open your email</b><small>Check your inbox and spam folder.</small></span><span><Send/><b>Click the link</b><small>Tap the verification link.</small></span><span><ShieldCheck/><b>You’re all set</b><small>Your account activates instantly.</small></span></div><button className={styles.primary} type="button">Open email app</button><div className={styles.verifyActions}><button onClick={resend} type="button">Resend verification email</button><Link href="/signup">Change email address</Link></div><small>Resend available in <b>00:{String(seconds).padStart(2,"0")}</b> seconds</small></>:<VerificationState state={state} resend={resend}/>}<Link className={styles.back} href="/login">← Back to sign in</Link></div></section><aside className={styles.stateRail}><VerificationMini kind="verified"/><VerificationMini kind="expired"/><VerificationMini kind="invalid"/></aside></div>
}
function VerificationState({state,resend}:{state:"verified"|"expired"|"invalid";resend:()=>void}){return <div className={styles.singleState}>{state==="verified"?<CheckCircle2/>:<XCircle/>}<h2>{state==="verified"?"Email Verified Successfully!":state==="expired"?"This Link Has Expired":"This Link Is Invalid"}</h2><p>{state==="verified"?"Your account is active. Continue into your personalized Perspective experience.":"Request a fresh verification email to securely activate your account."}</p>{state==="verified"?<Link className={styles.primary} href="/search?q=my+perspective">Continue to My Perspective</Link>:<button className={styles.primary} onClick={resend} type="button">Send new verification link</button>}</div>}
function VerificationMini({kind}:{kind:"verified"|"expired"|"invalid"}){const ok=kind==="verified";return <section className={styles.verifyMini} data-kind={kind}>{ok?<CheckCircle2/>:<XCircle/>}<div><small>{kind}</small><h3>{ok?"Email Verified Successfully!":kind==="expired"?"This Link Has Expired":"This Link Is Invalid"}</h3><p>{ok?"Your account is now active.":"Request a new verification email."}</p><button type="button">{ok?"Continue":"Send new link"}</button></div></section>}
